README.md
appveyor.yml

Build on Windows using Appveyor (#10).
Eventually we should create an Appveyor account using a "helics" email address for the builds and update the links for the badge/build status.

Add appveyor config and badge

---

CMakeLists.txt
cmake/modules/CheckLatestCXXStandardOption.cmake
cmake/modules/configGenerator.cmake

Separates the CXX standard detection out of the config generator script, and sets the standard using add_compile_options -- result gets propagated to try_compile calls.
Avoid using CMAKE_REQUIRED_FLAGS. It seems to be undocumented (internal use only?) and caused problems with FindThreads when used.

Separate CXX standard detection from config, remove CMAKE_REQUIRED_FLAGS

---

src/helics/shared_api_library/MessageFilters.h

One line change. Removes warning during  make with python extension on OSX
````
Scanning dependencies of target _helics
[100%] Building C object swig/python/CMakeFiles/_helics.dir/helicsPYTHON_wrap.c.o
In file included from /Users/bpalmint/repos/HELICS-src/build-osx/swig/python/helicsPYTHON_wrap.c:3032:
/Users/bpalmint/repos/HELICS-src/src/helics/shared_api_library/MessageFilters.h:81:66: warning: no newline at end of file
[-Wnewline-eof]
#endif /* HELICS_APISHARED_MESSAGE_FILTER_FEDERATE_FUNCTIONS_H_*/
^
1 warning generated.
````

Correct missing newline at end of shared_api_library/MessageFilters.h

---

examples/CppInterface/CMakeLists.txt
src/helics/CMakeLists.txt
src/helics/cpp98/CMakeLists.txt
src/helics/cpp98/CombinationFederate.hpp

Adds a target to make the C++98 API header files show up in IDEs (Visual Studio, issue #104). Creates a helicsCpp98 interface library that can be used for target_link_libraries command.

C++98 API library and IDE targets

---

.travis.yml

Added a set of build configurations for a daily build that are separate from the configurations used on each commit. Will eventually be used to run code coverage and valgrind on the tests. Also changed os x builds to only take place for the master and develop branches.

Set up Travis config for daily builds

---

.travis.yml
scripts/install-ci-dependencies.sh

* Uses Boost 1.65 for all builds except with gcc-4.9; configurations can be built using Boost 1.61 by adding a `MINIMUM_DEPENDENCIES=true` environment variable. Boost installation commands have been put in their own function.
* Recognizes `[update_cache]` in commit messages to purge the contents of the dependencies directory, or if the commit message also contains `boost` or `zmq`, it will only remove the dependencies mentioned in the commit message.
Addresses issues #128 and #108

Update version of Boost used on Travis, commit keyword to update cached dependencies

---

.gitignore
.travis.yml
scripts/install-ci-dependencies.sh
tests/python_helics/test_helics.py

- Imports helics extension on Travis in Python: `import helics`
- Runs the version number of HELICS function in Python: `helics.helicsGetVersion()`

Test python extension on travis

---

src/helics/application_api/Filters.cpp

@phlptp I did this as a pull request because I was just reading the code and saw this copy/paste bug and wanted to make sure it was correct before committing.

Filters addOperation() missing reroute

---

scripts/install-ci-dependencies.sh
scripts/install-dependency.sh

Installs tagged v4.2.3 zmq release instead of latest commit. Avoid potential breakage of zeromq version that is in development.

Test zmq dependency version

---

appveyor.yml

Install artifact is available at: https://ci.appveyor.com/project/nightlark/helics-src/build/artifacts
Appveyor can upload artifacts to a variety of places with either a deploy section in the config file, or by running curl/ftp to upload files to wherever we want them.

Create HELICS installer and artifact on AppVeyor

---

tests/helics/application_api/FilterTests.cpp

Basically adds a number of tests specific to the filter object creation in C++.  There were no issues that came up from the tests so this is just to add the tests into the main branch.  
A future effort will be to make a much more extensive test suite that fully exercises the built in filters.  This PR just verifies they work nominally in a defined circumstance.

This adds several test identical to previous filter tests

---

src/helics/core/FederateState.cpp
tests/helics/application_api/TimingTests.cpp

Fix for #284,  the configure message was not being processed when stuck in the queue, also deleted some commented out code.

Additional timing tests

---

src/helics/core/TimeCoordinator.cpp

this allows recorders with no defined stop time to terminate if everything connected has halted.

fix to allow recorders to terminate

---

.travis.yml
scripts/install-ci-dependencies.sh
src/helics/application_api/ValueFederate.cpp
src/helics/core/CommonCore.cpp
src/helics/core/CommsBroker.cpp
src/helics/core/CommsInterface.cpp
src/helics/core/CommsInterface.hpp
src/helics/core/FederateState.cpp
src/helics/core/FederateState.hpp
src/helics/core/NetworkBrokerData.cpp
src/helics/core/NetworkBrokerData.hpp
src/helics/core/tcp/TcpComms.cpp
src/helics/core/tcp/TcpComms.h
src/helics/core/udp/UdpComms.cpp
src/helics/core/udp/UdpComms.h
src/helics/core/zmq/ZmqComms.cpp
src/helics/core/zmq/ZmqComms.h
src/helics/shared_api_library/FederateExport.cpp
src/helics/shared_api_library/helicsExport.cpp
src/helics/shared_api_library/internal/api_objects.h
swig/python2/CMakeLists.txt
tests/helics/application_api/ErrorTests.cpp
tests/helics/core/CMakeLists.txt
tests/helics/core/networkInfoTests.cpp
tests/java_helics/ApplicationApiTest.java
tests/python_helics/test_message_filter.py

This improves the autodetection for the local interfaces.  For cores/brokers that link with a broker, the network should be detected based on the broker.  For root brokers.  it will still default to local, but a flag like --ipv4 or --ipv6 or --all can be specified to simplify the network connection interface.  without requiring --interface=XXX.XXX.XXX.XXX:port or something to that effect.  zmq will default to using tcp

Broker network specs updates

---

scripts/install-ci-dependencies.sh
scripts/install-dependency.sh

* Dependency installation script used on Travis can be run on other systems to build the full set of dependencies with the same versions as used on Travis

Remove dependency on Travis for CI dependency installation script

---

config/helics-config.h.in
src/helics/common/DualMappedVector.hpp
src/helics/common/timeRepresentation.hpp
src/helics/core/helics-time.hpp
tests/helics/application_api/CMakeLists.txt
tests/helics/application_api/TimingTests2.cpp
tests/helics/common/TimeTests.cpp

this PR fixes an issue reported about mismatching times when using very small increments in time.  The source of the issue was the rounding technique used to convert the time representation to doubles.  This issue has never arisen before due to most cases not using very small increments or doing the tests using them in C++.  
The changes here add a rounding operation to the conversion which rounds to the nearest ns instead of truncating.  It also adds a hidden option to use PICOSECOND timing, though such use would be incompatible with any part of HELICS using ns resolution

Very small time checks

---

.travis.yml

* Issue #460 allowing clang thread sanitizer cron build as a failure
* Travis doesn't support wild cards for allowable failures, entry must be an exact match

Allow clang thread sanitizer cron build to fail

---

README.md

Fixes display of Appveyor build status and code coverage badges to show the status of the master branch instead of develop.
Changes URLs for badge images and links for Appveyor and codecov from develop to master.

Fix codecov and appveyor badges to use master branch

---

src/helics/CMakeLists.txt

Adds the install include path as part of the interface for the helics-static and helics-shared CMake targets imported by projects using find_package in config mode to locate HELICS. Allows using only CMake targets without needing to use the HELICS_INCLUDE_DIR variable to add an include directory.

Add install include path to imported helics-static and helics-shared cmake targets

---

.github/PULL_REQUEST_TEMPLATE.md

Use `h3` instead of `h1` in Pull Request templates.

Change PR template to use h3 instead of h1 in markdown

---

CMakeLists.txt
config/cmake/addBoost.cmake
docs/installation/docker.md
docs/installation/linux.md
docs/installation/windows.md
scripts/build_boost_clang.sh
scripts/build_boost_gcc.sh
scripts/install-dependency.sh
src/helics/core/BrokerBase.cpp
src/helics/core/CMakeLists.txt
src/helics/core/CommonCore.cpp
src/helics/core/CoreBroker.cpp
src/helics/core/ipc/IpcComms.cpp
src/helics/core/ipc/IpcQueueHelper.cpp
tests/helics/core/CMakeLists.txt

Removes some unused headers and compiled Boost libraries that aren't used, reduces the number of Boost libraries that need to be compiled while building for CI or installed with apt.
- Remove some headers that are included but not used from several source files
- Remove unused compiled Boost libraries; chrono isn't used (std::chrono is used instead), timer isn't needed (for C++11 compilers, std::chrono is used internally), and compiled parts of date_time aren't used
- Remove unused compiled Boost libraries from libraries to build on Travis and in build instruction documents

Cleanup unused headers and remove unneeded compiled Boost libraries

---

.travis.yml
README.md

Disable Python/Java interfaces for certain build types. And update the codecov link for the develop branch badge. Addresses issues raised in #470.
- Link the develop codecov badge to the codecov page for the develop branch
- Add a mechanism for disabling building language interfaces on Travis
- Disable the Python/Java interface builds for the Travis Valgrind, sanitizer, and code coverage builds

Disable building Python/Java interfaces for Travis CI code analysis runs

---

interfaces/matlab/CMakeLists.txt

Changes to make finding and compiling Matlab extension work on Linux (#537)

Fix finding Matlab on Linux

---

.travis.yml

Allows the trigger dependent repositories step to fail (or be cancelled). Travis only allows ~10 api requests for starting builds per hour anyway.

Allow trigger dependent repositories step to fail

---

src/helics/core/NetworkBrokerData.cpp
src/helics/core/NetworkBrokerData.hpp
src/helics/core/NetworkCommsInterface.cpp
src/helics/core/NetworkCommsInterface.hpp
src/helics/core/zmq/ZmqComms.cpp
src/helics/core/zmq/ZmqCommsSS.cpp

This partially addresses Issue #578
- Have the timeout on the ZMQ comms use the connectionTimeout variable from CommInterface instead of hard coded value
- use 0 timeout for some zmqComms_ss since 10ms was not particularly useful.

update the timeout used in zmq comms

---

ThirdParty/helics_includes/variant.hpp

Include VS2017 version 15.9 in the compiler versions affected by the constexpr compiler bug.

Update variant.hpp to include constexpr fix for VS2017 15.9

---

.travis.yml
scripts/upload-ci-artifact.sh

Fixes paths for uploading CI artifacts built on Travis to BinTray, for use in HELICS-FMI builds.

Fix uploading Travis CI artifacts

---

src/helics/CMakeLists.txt

The generate expression was getting copied into the cmake-targets export file.  On import this line got copied into the targets,  and if the linkage was passed through to a higher level target the generate expression failed to evaluate.  Which meant HELICS had to be imported at the top level or it would fail.  The modification removes the generate expression and directly uses the target which should work fine in the export

modify the export lines on the cmake

---

src/helics/core/CoreBroker.cpp

Changes the summary output for brokers with a little more detail,  which is useful for spotting some types of issues.

change broker summary output

---

examples/comboFederates1/comboFed.cpp

Fixes a typo in the argument name recognized in the comboFederate example.

Fix typo in comboFed example for command line arg

---

CMakeLists.txt
config/cmake/updateGitSubmodules.cmake

If merged this pull request will add an option to the CMake configure step to ensure that the git submodules are initialized and updated.
- Add an update git submodules script to the CMake build process to automatically download git submodules (issue #675)

Autoupdate git submodules

---

.travis.yml
appveyor.yml
scripts/install-ci-dependencies.sh
scripts/setup-helics-ci-options.sh
tests/helics/CMakeLists.txt

If merged this pull request will run the in buildtree find_package test only on the gcc 4.9.3 builds (not running the rest of the test suite) by replacing the Daily/Continuous ctest labels with a Packaging label. This resolves the ubsan linking errors (#685) when attempting to run the test on the daily build.
- Replaces RUN_<sanitizer> environment variables on Travis for test scripts with a RUN_SANITIZER=<sanitizer> variable
- Use the "Packaging" CTest label for find_package tests instead of "Daily" and "Continuous" labels
- Run "Packaging" tests on gcc 4.9.3 build (runs on commit and daily)

Run packaging tests on one build configuration

---

src/helics/application_api/queryFunctions.cpp
src/helics/common/JsonProcessingFunctions.cpp

If merged this pull request will include the sstream header to JsonProcessingFunctions.cpp to fix a compile error encountered on MSVC.
- Add sstream header to JsonProcessingFunctions.cpp to fix compile error
- Remove JsonCpp include from a file that doesn't use it

Add sstream header to JsonProcessingFunctions

---

src/helics/core/JsonMapBuilder.hpp

If merged this pull request will add a missing string header to JsonMapBuilder.hpp that MSVC2019 complains about, to make HELICS compiler with VS2019. Errors due to the missing header can be seen at line 200 of [this HELICS-Examples build log](https://dev.azure.com/HELICS-test/HELICS-Examples/_build/results?buildId=505&view=logs&jobId=022b0a5d-2698-5f72-7610-a845972a8b4c&taskId=fb4a47ce-9e3e-59af-1bc9-5f0d015ee903&lineStart=200&lineEnd=201&colStart=1&colEnd=1)
- Add string header to JsonMapBuilder.hpp

Fix VS2019 build by adding missing string header

---

docs/doxygen/index.md
docs/index.md
src/helics/core/helicsCLI11.hpp

If merged this pull request will clean up the ReadTheDocs navigation sidebar with sections and a link to the Doxygen for the version being viewed. Convert helicsCLI11.hpp to utf-8 to fix the RTD build.
- Convert helicsCLI11.hpp encoding to utf-8
- Organize ReadTheDocs navigation into sections
- Add a link to the sidebar for the Doxygen matching the version of the docs being viewed

Clean-up the RTD navigation and fix the RTD build

---

config/cmake/FindZeroMQ.cmake
config/cmake/addZeroMQ.cmake
src/helics/core/BrokerFactory.cpp
src/helics/core/CoreFactory.cpp
src/helics/core/MessageTimer.cpp
src/helics/core/MessageTimer.hpp
tests/helics/core/MessageTimerTests.cpp
tests/helics/core/TestCore-tests.cpp

If merged this pull request will fix a recurring sporadic issue with the message Timer and some potential ZMQ issues if ZMQ happened to be installed on Windows without the headers.  
- reorder some operations in the message timer to eliminate a potential pathway for stack corruption
- deal with the case of an expired timer starting out.  
- add an additional test case to specifically test the expired timer pathway.  
- use the chrono literals to clean up code.

Message timer fixes

---

CHANGELOG.md
CMakeLists.txt
README.md

If merged this pull request will install miscellaneous documents (LICENSE, NOTICE, README.md, CHANGELOG.md) to the [standard GNU install directory](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) for docs (also conforms with the [Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html)). The files could also be installed to the DATADIR, instead of the doc subfolder -- though it looks like most packages put these types of files in the doc subfolder.
- Add README.md and CHANGELOG.md to the files installed
- Install LICENSE, NOTICE, CHANGELOG.md, and README.md to the GNU docdir
- Change the README to say ReadTheDocs instead of GitHub for documentation links
- Make all bullets for changes in 2.1 start with a lower-case letter

Install misc docs to the standard GNU/FHS directories

---

config/HELICSConfig.cmake.in

If merged this pull request will use the HELICS CMake targets to set the include and library variables.
- Use CMake targets to set the include and library variables
- Change HELICS_INCLUDE_DIR to HELICS_INCLUDED_DIRS to reflect that several directories may be needed (most CMake modules use *_INCLUDE_DIRS, and most of the ones with *_INCLUDE_DIR seem to have it deprecated)
- Use a single variable for each type of library instead of having multiple variants; only half of the variables had valid values before, and the typical generators (other than MSVC) only support a single build type when configuring. Most other CMake modules seem to just have a single library variable rather than separate Release/Debug variables.

Set HELICS CMake package variables using target properties

---

.travis.yml
scripts/setup-helics-ci-options.sh

If merged this pull request will allow the CXX_STANDARD env var on Travis used for setting up the CMake options to be set to any value (14, 17, 20, etc). Using 17 or higher may require a user to have newer versions of CMake (3.8+) and/or compiler than the minimum required to build HELICS.
This fixes issue #693.
- Allows any value for CXX_STANDARD in the env var on Travis
- Fix the Travis CI CXX_STANDARD=17 test (wrong variable was getting set with the CMake option)
- Use CMake 3.14.5 for the Clang 5 Travis build (CMake 3.4 doesn't support C++17)

Allow any value for CXX_STANDARD env var on Travis

---

src/helics/shared_api_library/MessageFederateExport.cpp

If merged this pull request will remove the empty field initializer list. For some reason gcc 4.9.3 has issues with it and prints warnings.
- Remove the empty field initializer list when creating a helics_message object in the shared API library

Get rid of GCC 4.9.3 missing-field-initializers warning

---

README.md

If merged this pull request will add a link back to the HELICS GitHub repository in the README. Just in case someone gets a tarball of the code and wants to know where it came from.
- Add a link back to the HELICS GitHub repo in the README

Add a link to the HELICS GitHub repo in the README

---

.travis.yml

If merged this pull request will stop running the XCode 8.3 build on pull requests to develop due to the Travis issues that require a (very slow +26min) Homebrew update for each build. XCode 8.3 builds will still be run daily for develop, and for pushes and PRs to master.
- Remove the XCode 8.3 build for PRs to develop

Remove the XCode 8.3 build for PRs to develop

---

scripts/trigger-dependent-ci-builds.sh

If merged this pull request will use the HELICS branch that was just built as the source branch to use in the dependent repository build. This should help make the result reported for builds to master/develop a bit more meaningful (Examples master branch needs updating for the release) and help ensure the master branches in different repositories are compatible.
- Test the branch in the dependent repository whose name matches
- Refactor the curl invocation into a bash function

Set dependent repo build branch to HELICS branch

---

src/helics/core/NamedInputInfo.cpp
tests/helics/system_tests/flagTests.cpp

If merged this pull request will fix a potential issue in the federate level update_only_on_change flag
- fix potential out of bounds memory issue with the update_only_on_change flag
- add some test cases for federate level flags for only update on change and only transmit on change

add some flag tests for federate level update only on change flag

---

CMakeLists.txt
interfaces/CMakeLists.txt

If merged this pull request will install a copy of the main swig interface files needed to create a language wrapper using swig to the helics/swig subfolder of the GNU datadir. This is typically share/helics/swig.
- Install the main swig interface files to datadir

Install the main swig interface files to datadir

---

CMakeLists.txt
appveyor.yml
interfaces/CMakeLists.txt
scripts/setup-helics-ci-options.sh
src/helics/CMakeLists.txt
src/helics/core/CommonCore.cpp
src/helics/core/HandleManager.cpp
src/helics/core/zmq/ZmqRequestSets.h

and not even give the option if CSHARP, PYTHON2, or OCTAVE interfaces are enabled.  move the definitions of the options to the interfaces folder CMAKE and create a DISABLE_C_SHARED_LIB option to explicily disable the C_SHARED_LIB otherwise by default it is enabled.
If merged this pull request will change the options for ENABLE_SWIG, the default is off unless one of the interfaces that needs to be generated is selected.  Then it is required.  Also move the interface options to the interfaces folder, and then make an advanced option for DISABLE_C_SHARED_LIB to explicitly disable it otherwise it is on by default.
This resolves issue #765

set the default ENABLE_SWIG to OFF 

---

CMakeLists.txt
ThirdParty/netif/gmlc/netif/NetIF.hpp
src/helics/core/NetworkBrokerData.cpp
src/helics/core/NetworkBrokerData.hpp

If merged this pull request will improve the reliability of the external interface selection when using the resolver could return an incorrect result, such as in emulated networks.
- Uses OS syscalls to get all network interface addresses
- Makes sure the resolved network interface address exists on the system
- Prioritizes picking addresses that both the OS syscall and resolver returned
- Falls back to picking a non-loopback address if no interface with an address matching the resolved address exists
- Uses resolved addresses that aren't assigned to an interface last

Improve external network interface selection reliability

---

interfaces/helics.i
interfaces/matlab/matlab_maps.i
interfaces/octave/octave_maps.i
interfaces/python/python_maps.i
interfaces/python2/python_maps2.i
src/helics/application_api/Federate.hpp
src/helics/helics_enums.h
src/helics/shared_api_library/FederateExport.cpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
src/helics/shared_api_library/api-data.h
src/helics/shared_api_library/helics.h
src/helics/shared_api_library/internal/api_objects.h
tests/helics/shared_library/FilterTests.cpp
tests/helics/shared_library/test-message-federate.cpp

If merged this pull request will add a new message object API for better access to messages in the C and language API's, and fixes an inability to access raw data in the language API's for messages.
- add messageObject api to the C shared library
- add a few test cases using the API
The old API is still there and functional but will likely be deprecated in HELICS 2.3
This new api actually could be faster in C, since it allows access to the messages with no copying.  
and a much cleaner way to potentially do custom filters in the language API's

New message api

---

config/cmake/addUnits.cmake

If merged this pull request will fix order of option parameters in addUnit.cmake, so value is actually set for HELICS_UNIT_OBJLIB. 
Refer to [CMake option](https://cmake.org/cmake/help/latest/command/option.html) for syntax. 
-

Fix addUnits Option parameter for CMake to match option parameter order

---

src/helics/apps/helics-broker.cpp
src/helics/common/zmqContextManager.cpp
src/helics/common/zmqContextManager.h
src/helics/shared_api_library/helicsExport.cpp
tests/helics/application_api/application-api-tests.cpp
tests/helics/common/common-tests.cpp
tests/helics/core/core-tests.cpp
tests/helics/system_tests/helics_system_tests.cpp

If merged this pull request will make zmq leaking on delete the default, and remove the excess calls for that in the various executables.  
- make zmqleakonDelete the default
- add functions to turn that off
- add some documentation on the zmqcontextmanager

Zmq leak on delete

---

interfaces/matlab/CMakeLists.txt
src/helics/CMakeLists.txt
src/helics/shared_api_library/CMakeLists.txt

If merged this pull request will stop installing copies (some of which are non-functional due to symlinks) of the helics shared library outside of the lib folder on non-Windows systems, in favor of relying on a system installed copy or properly set PATH/LD_LIBRARY_PATH environment variables.
- Remove install of shared library files in BINDIR, except on Windows
- Remove non-functioning install of helicsSharedLib from the Matlab extension folder on non-Windows

Shared library install file location changes

---

CHANGELOG.md
config/Docker/Dockerfile-HELICS

If merged this pull request will build the HELICS apps docker container using a multistage build to reduce the size, along with doing a Release build of the apps.
Some numbers for the effect of the changes on sizes-- the image size shown by `docker images` goes from 1.01GB -> 265MB from the multistage build, setting the CMake build type to Release decreased the size from 265MB to 132MB. On DockerHub, the size listed next to the tag went from 300MB to 58MB with both changes.
- Change the CMAKE_BUILD_TYPE to Release
- Use a multi-stage build to create the HELICS apps Docker image

Use a multi-stage Docker build for the HELICS apps container

---

CMakeLists.txt

If merged this pull request will only include the gtest license file if the tests using gtest were built.
- Include the gtest license only if the tests are built

Include the gtest license only if the tests are built

---

scripts/run-nighly-circleci-tests.sh
tests/helics/CMakeLists.txt
tests/helics/apps/BrokerServerTests.cpp
tests/helics/apps/CMakeLists.txt
tests/helics/apps/CloneTests.cpp
tests/helics/apps/EchoTests.cpp
tests/helics/apps/PlayerTests.cpp
tests/helics/apps/RecorderTests.cpp
tests/helics/apps/SourceTests.cpp
tests/helics/apps/TracerTests.cpp
tests/helics/apps/combo_tests.cpp
tests/helics/apps/exeTestHelper.h
tests/helics/apps/helics_apps_tests.cpp
tests/helics/apps/multi_player_tests.cpp
tests/helics/apps/multi_tests.cpp
tests/helics/core/TcpCore-tests.cpp

If merged this pull request will convert the apps test to use gtest
- convert helics_apps test to use gtest instead of boost
- add some debugging output to an occasional failing test in tcpcore tests
- add apps_tests to circle ci build tests

Apps test to gtest

---

src/helics/core/CommonCore.cpp
src/helics/core/CommonCore.hpp
src/helics/core/FederateState.cpp
src/helics/core/FederateState.hpp

If merged this pull request will fix the race condition in queries to federates coming from a core
- add support for CMD_QUERY in the federateState object
- actually lock the federateState when doing the query (with a few known exceptions)  
- if the try_lock fails then generate a actionMessage request
- use the lock function throughout the federateState instead of manually locking of the atomic_flag

Race cond fix in queries

---

.github/workflows/release-all-submodules-archive.yml
scripts/_git-all-archive-python.sh

If merged this pull request will add a GitHub Action that runs when a release is published (release + prerelease) to create and upload a source archive with the code for all submodules included.
Example release: https://github.com/nightlark/HELICS/releases/tag/v2.2.0.4
- Create separate bash-only and python versions of the git all archive script
- Create archive for the tagged git ref and upload to the published release

Create and upload source archive with all submodules for releases

---

src/helics/core/TimeCoordinator.cpp
tests/helics/system_tests/TimingTests2.cpp

generating negative times on overflow.  This fix will resolve it for the time being but some changes are needed in the timeRepresentation to completely resolve it.  This fix just makes it significantly harder to generate the bug.  like (2^24X harder) in numerical terms.
If merged this pull request will fix an issue with small periods and large time request generating an int overflow.  
- add a test of this situation
- change the int and leave it as a double so it can't overflow.  longer term fix is to make some changes in the timeRepresentation library to handle int64 multiplies better.

Fix an issue with very small periods and large time requested

---

.ci/Brewfile-minimal.travis
.ci/Brewfile.travis
.travis.yml

If merged this pull request will get the XCode 8.3 build passing again on Travis. Build results: https://travis-ci.com/GMLC-TDC/HELICS/builds/130787542
- Separate XCode 8.3 build brewfile from the brewfile used for newer macOS versions
- Removes Boost from the Travis brewfiles; version installed on the VMs is new enough
- Remove swig and pcre from the Travis brewfile used for the XCode 8.3 build

Get XCode 8.3 building again on Travis

---

src/helics/core/CommonCore.cpp
src/helics/core/CoreBroker.cpp
src/helics/core/FederateState.cpp
src/helics/core/InterfaceInfo.cpp
src/helics/core/NamedInputInfo.cpp
src/helics/core/NamedInputInfo.hpp
tests/helics/application_api/ValueFederateKeyTests.cpp
tests/helics/core/InfoClass-tests.cpp

If merged this pull request will fix the spurious "remove target" failure with CI builds
- add a test which forced the failure
- fix the failure by storing the target name directly and then removing it inline with the other federate messages,  
- make sure the appropriate message information propagates through the to the correct destinations
- allow double removal which can happen now.

Spurious removal failure

---

config/HELICSConfig.cmake.in

If merged this pull request will fix a bug with the HELICSConfig.cmake file in cases when the static library was not installed and no helics-static target exists.
- Add checks to HELICSConfig.cmake to make sure the helics-static target exists before using it.

Fix HELICS CMake config bug when helics-static library is not exported

---

CHANGELOG.md
CMakeLists.txt
README.md
appveyor.yml
docs/ROADMAP.md
src/helics/core/CommonCore.cpp
src/helics/core/CoreBroker.cpp
src/helics/core/TimeoutMonitor.h
tests/helics/system_tests/brokerTimeoutTests.cpp
tests/python/test_value_federate.py

If merged this pull request will add a new timeout test in Python for a value federate. It initializes a federate, enters execution and waits 60 seconds, and then checks if the broker is still connected.
This test can be run explicitly by using the following:
```
pytest -sv tests/python/test_value_federate.py -k test_value_federate_runFederateTimeoutTest
```
Related to #853

Add timeout test

---

README.md
docs/installation/package_manager.md
docs/introduction/python.md

Resolves #843 
Most people likely want to use HELICS with Python. `conda` is the recommended way to install HELICS with Python. The `brew` recipe builds from source anyway and only allows configuring a limited number of options. 
Users can just directly build from source and configure any option they want manually. This allows them to build Python2/Python3, build with GCC/Clang or any of the other options available in `cmake`.

Remove `brew install helics` instructions

---

CMakeLists.txt
benchmarks/helics/echoBenchmarks.cpp
benchmarks/helics/echoMessageBenchmarks.cpp
benchmarks/helics/messageLookupBenchmarks.cpp
benchmarks/helics/ringBenchmarks.cpp
config/helics-config.h.in
src/helics/core/BrokerFactory.cpp
src/helics/core/CMakeLists.txt
src/helics/core/CommsBroker.cpp
src/helics/core/CoreFactory.cpp
src/helics/core/core-types.cpp
src/helics/core/core-types.hpp
src/helics/core/inproc/InprocBroker.cpp
src/helics/core/inproc/InprocBroker.h
src/helics/core/inproc/InprocComms.cpp
src/helics/core/inproc/InprocComms.h
src/helics/core/inproc/InprocCore.cpp
src/helics/core/inproc/InprocCore.h
src/helics/helics_enums.h
tests/helics/core/CMakeLists.txt
tests/helics/core/InprocCore-Tests.cpp
tests/helics/coreTypeLists.hpp

If merged this pull request will split the test core used in HELICS into two parts which can have different goals.  The inproc core will be intended to provide in process memory transfer between federates and can be optimized for that purpose.  The test core will be focused on provided convenient means of testing communication robustness in HELICS.  Previously the test core provided both of these purposes however these roles have started to come into conflict necessitating a split.  
- add two new core type definitions
- split the test core into two (mostly similar at this point) core types
- add dedicated tests for the in proc core
- add compiler option for the core
- change most tests to use the inproc core

Add inproc core

---

interfaces/java/javaSwigGenerateOnly.cmake
interfaces/python/pythonSwigGenerateOnly.cmake

If merged this pull request will add a -doxygen flag for updating the generated Java and Python interfaces code.
- Add `-doxygen` flag when generating updated Python and Java interface files with SWIG

Add -doxygen flag to Python and Java swig interface generation-only option

---

benchmarks/helics/messageSendBenchmarks.cpp

If merged this pull request will add a set of benchmarks that exercise sending messages of various sizes and quantities. Related to issue #848.
Message count benchmarks go up to 512 because beyond that there wasn't much of interest happening (no crashes), just much longer run times.
Message size benchmarks caused certain cores to crash (ipc and tcp both can't handle 4096, udp core packets are too long at 65K).
Combining the message size and count benchmarks enables interesting results, mostly that show how for many core types increasing the message size (up to a certain point) has no affect compared to sending more messages.
- Add message send size and count benchmarks

Add benchmarks varying message size and count

---

CMakeLists.txt
config/Docker/Dockerfile-HELICS

If merged this pull request will rename some instances of CMake options that have been renamed to have a HELICS_ prefix.
- Update ZMQ option names using old names to new HELICS_ name
- Update option names used in Dockerfile-HELICS

Update some CMake option names to use their new HELICS_ name

---

.github/workflows/release-build.yml

If merged this pull request will add builds for a macOS and Linux shared library, and a macOS archive that includes some extras like the compiled apps to the releases workflow.
Latest test run at https://github.com/nightlark/HELICS/releases/tag/vMac.7 (MSVC archive builds failed due to swig archive not downloading, probably sourceforge issues -- rerun is at https://github.com/nightlark/HELICS/releases/tag/vMac.8)
- Add a macOS and Linux shared libraries (+ headers and swig *.i files) to the release build workflow
- Add a macOS archive that includes pre-compiled apps and some interfaces to the release build workflow

Add macOS installers and Linux shared library to release build workflow

---

CHANGELOG.md
CMakeLists.txt
config/helics-config.h.in
docs/installation/helics_cmake_options.md
docs/installation/index.md
src/helics/application_api/FederateInfo.cpp
src/helics/common/CMakeLists.txt
src/helics/core/BrokerBase.cpp
src/helics/core/CMakeLists.txt
src/helics/core/FederateState.cpp
src/helics/core/MessageTimer.hpp
src/helics/core/NetworkBrokerData.cpp
tests/helics/core/CMakeLists.txt
tests/helics/system_tests/CMakeLists.txt
tests/helics/system_tests/ErrorTests.cpp
tests/helics/system_tests/TimingTests.cpp
tests/helics/system_tests/networkTests.cpp

If merged this pull request will add a cmake option to disable linking with ASIO.  This can be useful in some environments where ASIO isn't supported.  Such as cygwin 64 bits.  It turns off the TCP and UDP cores as well as any timeout capabilities, and real time capabilities of HELICS.  Some of options related to real time operation have been disabled and will result in an error if used.  Others are left in place since there wasn't a good way to disable them.  Some potential options in the future may be available in later version of CLI11.  But the use cases for this are expected to be rare.  
- Add cmake (advanced option) to disable ASIO
- disable code and tests that make use of ASIO
- disable some options and configurations based on ASIO
will resolve Issue #877

Disable asio option

---

CMakeLists.txt
benchmarks/helics/CMakeLists.txt
src/helics/common/CMakeLists.txt
src/helics/core/CMakeLists.txt
tests/helics/coreTypeLists.hpp

and require the inproc core for benchmarks and the test core for the tests
- add checks to fail the build if the inproc core is not enabled for the benchmarks and the test core is not built for the tests.  
Remove some options from the cmake-gui if they are required.

clean up some of the core options 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support-or-design-question.md
.github/SUPPORT.md

If merged this pull request will update the new bug report issue template to automatically add a bug label, and add a link to open the HELICS Gitter to the list of options when creating a new issue.
- Add Gitter link to the new issue creation page
- Add default metadata to the bug report issue template to automatically add a `bug` label

Update issue templates

---

.github/actions/create-file-update-pr/action.yml
.github/actions/create-file-update-pr/entrypoint.sh
.github/workflows/clang-format.yml

If merged this pull request will open automated clang-format PRs for commits to develop and master that don't match the format given in the `.clang-format`. Updates to code in the ThirdParty folder or automated swig generated source files in the interfaces folder will not trigger a formatting run.
~A manual run can be triggered by commenting on a PR with `/format`. A PR with the formatting changes will be opened that can be merged into the PR (or the base branch could be changed to develop for merging later).~
The `format-trigger-testing` branch shows the results of some tests of the path/file triggers from some commits that did not result in any open PRs (or workflow runs) and two that did (#927 and #928).
Update on comment triggers: the Git SHA in the comment trigger is for the latest …

Add a clang-format actions workflow

---

.github/workflows/clang-format.yml

If merged this pull request will remove the changed file hash from the branch names used in PRs opened by the clang-format action. This avoids the filename length error from a formatting change that affects a large number of errors.
- Remove the hash from the clang-format action PR branch names
- Add the GitHub ref to the body of the PR message

Always use no-hash branches for clang-format PRs

---

.ci/azure-pipelines.yml

If merged this pull request will update the Azure Windows CI builds to use Python 3.5, since a colorama update broke Python 3.4 builds and the 5.x versions of pytest require Python 3.5 as a minimum.
- Update to use Python 3.5 on Azure Windows CI builds

Update Azure Windows CI builds to use Python 3.5

---

interfaces/matlab/matlab_maps.i

If merged this pull request will fix the two `cannot convert argument of incomplete type 'void *' to 'const char *'` errors for #961.
- Cast void* to char* for the SWIG_FromCharPtrAndSize function call

Fix void* to char* conversion error in Matlab interface

---

.github/actions/linux-release-builder/entrypoint.sh
.github/workflows/interface_gen_script.sh
.github/workflows/release-build/installer-Windows.sh
.github/workflows/release-build/installer-macOS.sh
.github/workflows/release-build/msvc-Windows.sh
.github/workflows/release-build/shared-library-Linux.sh
.github/workflows/release-build/shared-library-Windows.sh
.github/workflows/release-build/shared-library-macOS.sh
.github/workflows/upload-release-asset.sh
scripts/_git-all-archive-python.sh
scripts/_git-all-archive.sh
scripts/cleanup-cmake.sh
scripts/git-archive.sh
scripts/install-ci-dependencies.sh
scripts/install-dependency.sh
scripts/lcov-helper.sh
scripts/mktempdir.sh
scripts/run-ci-tests.sh
scripts/test_example.sh
scripts/trigger-dependent-ci-builds.sh
scripts/upload-ci-artifact.sh

If merged this pull request will fix various shellcheck warnings and errors. Mostly quoting variables to make sure spaces in the value work correctly, replacing `which` with the more standard `command -v` to get program paths, and adding `|| exit/return` for failed directory changes.
- Fix shellcheck warnings, including some bugs
- Remove no longer used Boost sanitizer and compilation step; copy the Boost headers instead (160 seconds -> 50 seconds for installing dependencies without a cache on Travis)

Fix shellcheck issues on shell scripts

---

scripts/_git-all-archive.sh

If merged this pull request will add better handling for the edge cases where the checkout tag and release tag arguments aren't provided for creating a git archive with all submodules.
- Handle the case of no checkout tag argument provided
- Set a nicer output file name when no release tag is given

Handle edge cases with git archive creation script tag arguments

---

interfaces/CMakeLists.txt

If merged this pull request will fix the formatting for the `HELICS_USE_NEW_PYTHON_FIND` option and disable formatting this block of code.
- Fix `HELICS_USE_NEW_PYTHON_FIND` by changing the formatting
- Disable formatting the `HELICS_USE_NEW_PYTHON_FIND` option code block

Fix HELICS_USE_NEW_PYTHON_FIND option

---

.travis.yml

If merged this pull request will run the code coverage Travis jobs on branch names containing "codecov" or commit messages with "codecov" in them.
- Update the condition for the Travis code coverage job to also run on branch names or commit messages containing "codecov"

Run Travis Code Coverage job if the branch name or commit message has "codecov"

---

interfaces/python/CMakeLists.txt

If merged this pull request will change the extension when building the Python interface on Windows without Swig to `pyd`. Fixes #979.
- Set the Python module extension on Windows builds to `pyd` when not using swig

Fix Windows Python module extension for builds without swig

---

.github/workflows/release-build.yml
.github/workflows/release-build/installer-macOS.sh
.github/workflows/setup-macos-10.10-sdk.sh
CMakeLists.txt

If merged this pull request will build the macOS installer and shared library release assets using a macOS 10.10 SDK to support older versions of macOS.
- Setup a copy of the macOS 10.10 SDK and use it to build macOS release assets
- Cleanup some of the macOS release package settings
- Switch macOS installer CPack generator from TGZ to ZIP

Build macOS release assets with the macOS 10.10 SDK

---

docs/installation/mac.md

If merged this pull request will fix a broken link to a github issue about matlab, switch to using $HOME as a more stable path than /Users/<name> (given some changes in Catalina...), and add links to guides on using a shell including a short thing on how PATH works.
The last part addresses issue #766 by providing resources to basics on how shells and `PATH` work, along with a note about custom install locations that discusses running programs to point users in the right direction.
- Add unix shell basic guide/tutorial links
- Add a short primer on CMake custom install locations and `PATH` environment variables
- Change example install paths from /Users/<name> to $HOME for macOS install guide
- Fix a broken link to a GH issue in the macOS Matlab install docs

Fix minor issues with macOS install docs and add useful terminal/shell basics information

---

.githooks/pre-commit

Resolves #987 
Makes git-hook no longer blocking, and verify availability of clang-format before attempting to execute.

Fix pre-commit hook to no longer block

---

CMakeLists.txt
config/cmake/updateGitSubmodules.cmake
docs/installation/helics_cmake_options.md

If merged this pull request will add a non-blocking CMake function to Git Submodules logic to check if all submodules are current.
Uses the `git submodule status --recursive` command to verify all submodules are
up to date with the parent repository, and displays a non-blocking warning if any
module is out of date, as well as the command to update submodules.
Output from git is piped through grep on *nix style machines, and powershell Select-String on Win32 machines to verify all submodules and their dependencies are clean. 
If submodules are out of date, the user is notified with a CMake warning, and the command to update the submodules is displayed.

Adds a CMake function to Git Submodules logic to check if all submodules are current

---

docs/installation/language.md
interfaces/python/CMakeLists.txt
interfaces/python/pythonSwigGenerateOnly.cmake

If merged this pull request will remove the dependency on Python when only generating updated interface files with swig.
- Handle the swig generate only option before finding Python (removes dependency on Python)
- Include the directory helics.i is in for swig generate only builds so that it can work standalone
- Add a note to the docs mentioning support for building the Python3 interface using an existing HELICS install

Remove dependency on Python for generating the swig interface

---

interfaces/python/CMakeLists.txt

If merged this pull request will put a copy of the helicsSharedLib file in the same folder as the Python module was built with on Windows, because it doesn't have anything like rpath.
- Copy helicsSharedLib on Windows to the same folder the Python module is in

Make sure the python module can find a copy of helicsSharedLib

---

config/cmake/GitUtils.cmake
config/cmake/ucm.cmake
interfaces/python/CMakeLists.txt

If merged this pull request will ensure all cmake message() calls have a mode set to STATUS instead of no mode. ucm and cmake_clone_git modules are updated to the latest versions.
- Update cmake_clone_git
- Update ucm
- Add STATUS mode to a message() call in the python interface CMakeLists.txt

Add STATUS mode to all cmake message() calls

---

CMakeLists.txt
interfaces/python/CMakeLists.txt

If merged this pull request will set the rpaths on macOS so that installs can be moved around (useful for tar.gz release download for language interfaces). Some CMake rpath settings will also no longer be forced to their default values, or override a user that configures a different setting; this is aimed at making packaging for different systems more flexible.
- Add relative path to lib folder to macOS rpath
- Don't override user set CMake rpath settings or force the default values

Set macOS rpaths to make installs movable

---

.github/workflows/clang-format.yml

If merged this pull request will disable the automated formatting for PRs from forks. The permissions with the GitHub token don't allow creating the PR. Address #971 (and duplicate #1037).
- Only run automated formatting on PRs originating from this repository (or pushes as usual, so once PR from a fork gets merged it could be automatically formatted)
- Change some of the variables used so that testing changes to the workflow in a fork works better

Disable automated formatting for PRs from forks

---

.github/workflows/release-build.yml
.github/workflows/release-build/installer-Linux.sh

If merged this pull request will add a Linux installer release archive (manylinux2010 compliant, CentOS 6+). The main difference from the shared library archive is that it includes HELICS app binaries that have been static linked to the system stdlibc++ and libgcc for portability. It does not include pre-built Python/Java interfaces (likely requires compiling Java from source and installing a copy of Python; pip install is easier than picking a single Python version to include).
- Add a Linux installer with the HELICS apps and shared library to the release builds

Add a Linux installer to the release builds

---

.gitattributes

If merged this pull request will set the hunk headers to use for several common source files types in the HELICS repository. These are the lines of text that show up when doing a `git diff` or using the `-p` (`--show-function`) or `-W` (`--function-context`) arguments to `git add`, `git grep`, and `git diff`.
Further details:
https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header
https://github.blog/2019-08-16-highlights-from-git-2-23/
https://github.blog/2020-01-13-highlights-from-git-2-25/
- Set git hunk header built-in patterns to use for common source file types

Set gitattributes hunk headers for common source file types

---

interfaces/python/CMakeLists.txt
interfaces/python/addHelicsPy3Lib.cmake
interfaces/python/pythonSwigGenerateOnly.cmake

If merged this pull request will get the right shared library platform tag from Python (e.g. `.cpython-37m-x86_64-linux-gnu.so`) in a way that matches the behavior of using the `python-config --extension-suffix` (without needing to find the right python-config or python3-config executable). Also several small fixes for generating new interface files, and setting the CMP0074 policy so that `HELICS_ROOT` can be used to set the path to a HELICS install.
If an error happens getting the extension suffix from Python, it leaves the default shared library extension on *nix and `.pyd` on Windows.
- Get the right Python extension suffix for the platform in a portable way
- Set policy CMP0074 so that `HELICS_ROOT` can set the location of a HELICS install
- Update python swig generate only code to …

Get Python extension suffix and fix several minor issues

---

CONTRIBUTORS.md

The gulrak/filesystem link on the CONTRIBUTORS page was pointing to mpark/variant.

Fix CONTRIBUTORS.md link to gulrak/filesystem

---

.travis.yml
scripts/run-ci-tests.sh
scripts/run-core-ci-tests.sh
scripts/setup-helics-ci-options.sh

If merged this pull request will add options to the CI test running script to filter the tests run using a matching and/or excluding regex. The mingw and msys tests on Travis are updated to use the new filter to only run the core ci tests, and the macOS XCode 10.2 build is updated to exclude the (very slow) application api and system tests.
- Add match and exclude regex options to the CI test running bash script
- Remove the core ci test running bash script
- Use the test matching option to run only the core ci tests on the mingw and msys builds
- Use the test excluding option to disable running the application api and system tests on the macOS XCode 10.2 build

Filter CI tests run on Travis

---

config/cmake/addGitHooks.cmake

When building in an external directory, the git repository would
be detected, but git would be unable to run in-folder. This fix
simply ensures that git is run from within the project directory
and not the build directory.
A new branch has been created, to avoid the "error" trigger word from the previous version of this issue. 
Resolves #996

Fix issue where git --local flag would cause fatal error

---

docs/apps/Broker.md
docs/apps/Recorder.md
docs/apps/Tracer.md
src/helics/apps/Recorder.cpp
src/helics/apps/Tracer.cpp
src/helics/apps/helics-broker.cpp

Found a note about fixing these doc/help string issues.
If merged this pull request will fix the docs and help strings for using the `--autorestart` flag (not subcommand) and clarify that `--capture` can take a semicolon or comma separted list.
Trying to use `autorestart` without `--` gives an error.

Apps docstring fixes

---

interfaces/CMakeLists.txt

If merged this pull request will set the `HELICS_ENABLE_SWIG` option to on when building an interface that requires swig -- this fixes a bug where the Python2 interface couldn't build as a subproject because the `cmake_dependent_option` macro was forcing `HELICS_ENABLE_SWIG` to off.

Always set HELICS_ENABLE_SWIG when building an interface requiring swig

---

.cirrus.yml
CHANGELOG.md
CMakeLists.txt
docs/developer-guide/continuous-integration.md

If merged this pull request will add a FreeBSD 12.1 CI build running on Cirrus CI. Resolves #840.
It compiles and runs with the IPC core enabled, however there were 5 system CI tests that consistently failed with the IPC, so it is disabled. In all those cases, the error is:
```
unknown file: Failure
C++ exception with description "core is unable to register and has timed out, federate cannot be registered" thrown in the test body.
forcing disconnect
```
The test summary for a failed build with the IPC core enabled is:
```
[==========] 134 tests from 14 test suites ran. (250625 ms total)
[  PASSED  ] 129 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] query_tests/query_type_tests.publication_queries/2, where GetParam() = "ipc_2"
[  FAILED  ] …
```

Add FreeBSD CI build

---

.github/workflows/release-build.yml
CHANGELOG.md

If merged this pull request will send an event after all HELICS release binaries are built to helics-packaging telling it that a new version has been released.
The action that handles the event in `helics-packaging` updates the version file, but doesn't open a PR yet -- it shows a [git diff](https://github.com/GMLC-TDC/helics-packaging/runs/483558701?check_suite_focus=true#step:4:10) of the change that would be in a PR.
- Send a `helics-version-update` event to `helics-packaging` after the the release build is finished

Send helics-version-update event to helics-packaging after new releases

---

.github/workflows/release-build.yml
CHANGELOG.md

If merged this pull request will add a win32 zip archive to the set of release assets. Primarily for making actual Windows 32-bit helics_app packages instead of labeling them as win32 with a 64-bit executable.
Test release with the added win32 asset: https://github.com/nightlark/HELICS/releases/tag/v2.4.0.2
- Add a win32 zip archive to the release builds

Add win32 release zip archive

---

.github/workflows/clang-format.yml
.github/workflows/release-build.yml
.github/workflows/swig-interface-gen.yml
CHANGELOG.md

If merged this pull request will update the GH actions checkout action to v2 (only checks out a single commit instead of all history). Checkouts for release builds now consistently take <=5s, whereas with the v1 checkout action it was taking 8 to 13+.
A test release build using the new checkout action can be found here: https://github.com/nightlark/HELICS/releases/tag/v2.4.0.3
- Update the GH checkout action used to v2

Update GitHub actions to use actions/checkout@v2

---

CHANGELOG.md
CMakeLists.txt

If merged this pull request will change CPack settings to make the Windows installer nicer to use and look a bit more polished.
Recent test installer build here: https://github.com/nightlark/HELICS/releases/download/v2.4.0.7/Helics-2.4.1-win64.exe
- Clean-up component names and descriptions
- Set Windows NSIS display names (e.g. show `HELICS v2.4.0` instead of `helics_2_4_0` as the program name)
- Add Gitter link to the installer
- Group `Headers` and `Libraries` components under a `Development` group
- Set `SWIG` component to depend on the `Headers` component

Windows installer clean-up

---

.github/workflows/release-build.yml
CHANGELOG.md

If merged this pull request will add an alternate way to trigger building release artifacts, either all of the assets or a subset based on asset "type", and with an option to set which branch/tag they should be built for.
It can't limit by os/arch yet because the matrix information isn't available for use in conditionals at the job level.
- Trigger release builds for 'helics-release-build' events -- recognizes `everything`, `archive`, `msvc`, `installer*`, and `sharedlib*` package names.

Add 'helics-release-build' dispatch event trigger

---

docs/developer-guide/swig.md
docs/installation/index.md
docs/installation/package_manager.md
docs/introduction/python.md

If merged this pull request will add pip to the install docs and make some small updates to the swig developer docs.
I'm not sure if helics-apps should be mentioned yet or if that should be included in a PR to master after the package is up on PyPI.
It feels like the install docs could use some cleanup to get rid of duplication and maybe the source build instructions could be made more consistent across platforms.
- Adds pip to several places in the install docs
- Updates the swig developer docs; makes apply to most unix/posix environments

Add pip to install docs

---

interfaces/python/CMakeLists.txt

If merged this pull request will fix a missed `_helics` target rename in the Python interface CMake file that breaks building the Python interface on macOS with swig. A Python 2 interface is unbuildable on macOS with the 2.4.1 release.
- Switch the missed instance of `_helics` to `${SWIG_MODULE_helics_REAL_NAME}`

Fix macOS Python interface build

---

docs/user-guide/index.md

User guide link is missing a `s`.

Fix link in user guide

---

benchmarks/helics/TimingHubFederate.hpp
benchmarks/helics/TimingLeafFederate.hpp

If merged this pull request will fix the timing hub and leaf federate names
- Change `echohub` to `timinghub`
- Change `echoleaf_` to `timingleaf_`

Fix the timing benchmark federate names

---

interfaces/csharp/CMakeLists.txt

If merged this pull request will change the namespace in the csharp interface to helics to better match other modules.  
FIx #1147 
and https://github.com/GMLC-TDC/HELICS-Examples/issues/31

change CSharp interface module name to be helics instead of csharp

---

README.md
docs/installation/index.md
docs/installation/package_manager.md

If merged this pull request will add spack to the list of package managers for installing HELICS.
- Add spack to the various docs listing package managers that can be used to install HELICS
- Add pip to the install options in the README

Add spack install to list of package managers

---

.ci/azure-pipelines.yml

If merged this pull request will fix the failed Boost find on Windows Azure Pipelines builds. It seems Azure Pipelines and GitHub Actions are using the same VM images, and Boost was removed from the PATH environment variable (or BOOST_ROOT is just no longer set).
- Set BOOST_ROOT to the Boost 1.72.0 install on Azure pipelines Windows images
- Disables Java interface builds on Windows

Set BOOST_ROOT to Boost 1.72.0 on Windows Azure CI

---

.github/workflows/static-analyzers.yml
CPPLINT.cfg

If merged this pull request will add a cpplint job running on GitHub Actions. Whitespace, multiline comment, and disallowed c++11 feature checks are disabled in cpplint; the first two seem to be primarily for following google style guidelines (and result in a huge number of errors [13000+]), and the latter is C++ headers that google doesn't allow using (regex, thread, etc).
Directories with source files checked (recursive) are: examples, benchmarks, src, tests
When the final set of categories is decided, a subsequent PR will be needed to fix the identified issues to make the test pass.
- Add a cpplint job running on GitHub Actions

Add cpplint job on GitHub Actions

---

src/helics/helics_enums.h

If merged this pull request will change the ordering for the `helics_error_types` enum.
Fixes #1193

Change helics_error_types enum ordering

---

src/helics/cpp98/Endpoint.hpp
src/helics/cpp98/Filter.hpp
src/helics/cpp98/Input.hpp
src/helics/cpp98/Publication.hpp
src/helics/cpp98/helics.hpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
src/helics/shared_api_library/MessageFilters.h
src/helics/shared_api_library/MessageFiltersExport.cpp
src/helics/shared_api_library/ValueFederate.h
src/helics/shared_api_library/ValueFederateExport.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/shared_library/evilInputTests.cpp
tests/helics/shared_library/test-message-federate.cpp
tests/helics/shared_library/test-value-federate1.cpp

If merged this pull request will add some missing C and C++98 API functions including set/get Info on inputs and isValid functions for endpoints, publications, inputs, and filters in the C API
Fixes Issues #1211 and #1213 
- add isValid to the C++98 and C API for inputs, publications, endpoints, and filters
- add get/setInfo to the C++98 input objects.
- add a few test of the added functions

missing C++98 functions

---

.clang-tidy
src/helics/application_api/Federate.cpp
src/helics/application_api/Federate.hpp
tests/helics/application_api/FederateTests.cpp

If merged this pull request will deprecate the error method in the Application_api federate object.  this function is duplicative of localError and `localError` or `globalError` should be used for better control over the error process.

Deprecate error method in federate

---

README.md
docs/installation/index.md
docs/installation/linking.md
docs/installation/package_manager.md

If merged this pull request will add a few notes saying to make sure the latest Visual C++ Redistributable is installed in the Windows installers/package manager docs, and a blurb on a tool to use for troubleshooting Windows dependency issues with the HELICS shared library.
Based on debugging dependency problem in #1139.
- Add links to Visual C++ Redistributable
- Add Windows shared library troubleshooting blurb

Add info on Windows dependency issues to install docs

---

tests/helics/webserver/webServerWebSocketTests.cpp

The http sporadic failure can also occur in the websocket test program so needs the same fix as PR #1250
If merged this pull request will fix a sporadic failure in the websocket server tests.  This has only been observed once, but that could be because the HTTP test would often fail in the same circumstances.

sporadic websocket failure fix

---

.github/workflows/release-build.yml
CHANGELOG.md

If merged this pull request will swap Python 3.6 for Python 3.8 in the release build workflow. Theoretically addresses #1290, but not the recommended way to install (requires users to manually figure out how to setup search paths for loading the package).
- Use Python 3.8 instead of Python 3.6 in release builds

Use Python 3.8 for release builds

---

CHANGELOG.md
src/helics/cpp98/Endpoint.hpp
src/helics/cpp98/MessageFederate.hpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
tests/helics/shared_library/test-message-federate_cpp.cpp

If merged this pull request will add some missing functions to the C++98 interface for message operations
- add missing operations to the C++98 interface
- add `helicsEndpointCreateMessage`
- add `helicsMessageClone`
- add `helicsMessageFree`

Missing message functions

---

CHANGELOG.md
src/helics/application_api/Federate.cpp
src/helics/application_api/Federate.hpp
src/helics/core/CommonCore.cpp
src/helics/core/CoreBroker.cpp
src/helics/core/CoreBroker.hpp
src/helics/cpp98/Broker.hpp
src/helics/cpp98/Core.hpp
src/helics/cpp98/Federate.hpp
src/helics/shared_api_library/helics.h
src/helics/shared_api_library/helicsExport.cpp
tests/helics/shared_library/CMakeLists.txt
tests/helics/shared_library/QueryTests_cpp.cpp
tests/helics/system_tests/QueryTests.cpp

If merged this pull request will add some exists queries to the core and broker and make them work a little cleaner.  
- add some tests to for the exists queries in the C++ and C++98 interfaces.
- add query operations to the Core and Broker Classes in the C++98 API. 
- change the getCorePointer() method in the C++ federate to return a reference instead of a new shared pointer to allow it to be copied if needed and just used as a reference if not.

Fix some issues with the exists query not working on core or brokers.

---

benchmarks/.clang-tidy
benchmarks/helics/BenchmarkMain.cpp
benchmarks/helics/CMakeLists.txt
benchmarks/helics/PholdFederate.hpp
benchmarks/helics/WattsStrogatzFederate.hpp
benchmarks/helics/wattsStrogatzBenchmarks.cpp

If merged this pull request will add a benchmark that implements a modified Watts-Strogatz network for communication. The key difference from the [Watts-Strogatz model described here](https://en.wikipedia.org/wiki/Watts%E2%80%93Strogatz_model) is that the links constructed by individual federates are directional.
From trying some different default parameters, increasing the initial message count created by each federate can make the benchmark hang when using the udp core as it gets near ~50 messages. Also, a large number of initial messages (100) resulted in the lower degrees of connectivity (1 link) being slower than higher degrees of connectivity (I think this is something that one of the message send benchmarks already exercises).
- add a modified Watts-Strogatz benchmark
- some …

(Modified) Watts-Strogatz Benchmark

---

docs/developer-guide/index.md
docs/developer-guide/porting-2-to-3.md

If merged this pull request will add a page that will try to track breaking changes in HELICS 3 and suggest changes to port HELICS 2 code to HELICS 3.
- Add a porting guide to the docs for develoeprs

Add HELICS 2 to 3 porting guide

---

benchmarks/helics/BenchmarkMain.cpp

If merged this pull request will add a `--print_systeminfo` flag to the root helics_benchmark command that prints system/compilation info and exits as an easy way to get system info without needing to kill the process later.
- Add print_systeminfo flag to root helics_benchmark command

Add print_systeminfo flag to root helics_benchmark command

---

CMakeLists.txt
benchmarks/helics/CMakeLists.txt

If merged this pull request will add an option for installing the benchmark binaries. Tested the change with spack and it provides a potentially easy way to get the HELICS benchmarks built on any systems that support spack.
- Install HELICS benchmark binaries when they are built
- Include benchmarks component in installers when built with the benchmarks enabled

Add option to install benchmark executables

---

CMakeLists.txt

If merged this pull request will make CMake exit with an error if the install prefix is set to the build folder. Setting install prefix to the build folder is the likely cause of #1445, due to build files conflicting with install files when the install path is set to the build folder.
- Exit CMake configure with an error if a user sets the install prefix to the build folder

CMake error if user sets the install prefix to the build folder

---

.github/actions/benchmark-build/benchmark-Linux.sh
.github/actions/benchmark-build/benchmark-Windows.sh
.github/actions/benchmark-build/benchmark-macOS.sh
.github/workflows/benchmark-package.yml

If merged this pull request will add a workflow to build a package with the benchmarks for Windows/macOS/Linux that can be triggered by an API call (or manually once the workflow is in the master branch). Once it makes its way into master it will also run every 2nd day of the week (3/4 times/week, something like Sunday, Tuesday, Thursday, Saturday or Monday, Wednesday, Friday).
- Add a workflow for building packages with the benchmark binaries

Benchmark build workflow

---

ThirdParty/frozen/bits/pmh.h
ThirdParty/frozen/string.h
src/helics/application_api/ValueFederateManager.cpp
src/helics/application_api/ValueFederateManager.hpp
src/helics/application_api/helicsTypes.cpp
src/helics/application_api/helicsTypes.hpp
src/helics/common/JsonProcessingFunctions.cpp
src/helics/common/JsonProcessingFunctions.hpp
tests/helics/application_api/PrimaryTypeConversionTests.cpp
tests/helics/application_api/helicsTypeTests.cpp
tests/helics/shared_library/test-value-federate1.cpp
tests/helics/system_tests/updateTests.cpp

If merged this pull request will use JSON strings as the vector and complex vector conversion operations.  
- update vector to string operations
- update complex vector to string operations
- update named point to string operations
- update complex number to string operation now `[real, imag]` instead of using the i/j notation, though the ability to read that notation remains in place.

make the vector/complex number conversions to fit JSON standard.

---

src/helics/network/tcp/TcpHelperClasses.cpp

If merged this pull request will set no_delay on TCP sockets to disable Nagle's algorithm. This significantly improves the performance of the tcpss core when running on multiple machines.
From some limited test runs with various combinations of the broker and federates with no_delay enabled using the MessageExchange benchmark:
| broker no_delay | bm fed no_delay | Benchmark Time |
| --- | --- | --- |
| no | no | > .2 sec |
| no | yes | > .2 sec |
| yes | no | .006 - .06 sec |
| yes | yes | .002 - .02 sec |
Nagle's algorithm is why the tcpss benchmark is consistently slow. The worst case is with the broker using Nagle's algorithm. Setting no_delay on the broker results in the benchmark speed improving by at least an order of magnitude (typical times with it set on the broker but not on the …

Set no_delay on TCP sockets

---

tests/java/JavaHelicsApiTests.java
tests/python/test_message_federate.py

If merged this pull request will update the Java and Python interface tests to use message functions instead of manipulating message struct fields directly.
- Update Java and Python interface tests to use functions instead of message struct fields

Update Python and Java interface tests

---

.ci/azure-pipelines-daily.yml
.ci/azure-pipelines.yml
scripts/setup-helics-ci-options.sh

Setup commit and some daily jobs on Azure Pipelines
If merged this pull request will add Linux and macOS jobs to runs on Azure Pipelines, and some scheduled daily jobs for checking (possibly less common) variants.
- Add Linux and macOS jobs to Azure Pipelines
- Make some aspects of the CI build/test scripts use-able on services other than Travis CI

Setup CI jobs on Azure pipelines

---

CMakeLists.txt

If merged this pull request will quote the variables used as part of the `install prefix == build dir` to handle an empty install prefix without triggering an error.
- Quote variables used in getting install prefix and build dir components to avoid errors if either happens to be empty

Handle empty install prefix without an error

---

docs/user-guide/queries.md
src/helics/common/JsonBuilder.hpp
src/helics/core/CommonCore.cpp
src/helics/core/CommonCore.hpp
src/helics/core/CoreBroker.cpp
src/helics/core/CoreBroker.hpp
tests/helics/system_tests/QueryTests.cpp

If merged this pull request will add a reset counter to some of the broker queries, dependecy_graph, data_flow_graph,and some others.  
- add reset counter to detect changes in the federation
- add a query for the counter to cores and brokers

Create mechanics for some queries of the broker to reset on changes

---

docs/user-guide/queries.md
src/helics/core/CommonCore.cpp
src/helics/core/TimeCoordinator.cpp
tests/helics/system_tests/QueryTests.cpp

and fix a bug that could potentially cause deadlock if particular queries were made while a federate was using an async call.
- add requested_time field to `current_time` query
- fix potential block issue with the federate query making a query while processing an async call.

add a requested time field to the current_time query result 

---

.github/workflows/release-build.yml

If merged this pull request will add a workflow_dispatch trigger to the release build workflow in the master branch to enable manual test runs of the release build workflow from the GitHub Actions tab. With tests on a fork, the option to trigger workflow runs didn't show up until the change to the workflow made it to the default/main branch.
- Add `workflow_dispatch` as a trigger to the release builds workflow

Add workflow_dispatch trigger to test releases

---

.ci/Brewfile-minimal.travis
.ci/Brewfile.travis
.travis.yml

If merged this pull request will remove the macOS and Linux jobs from Travis that were moved to Azure Pipelines. Adds an empty Linux job that does nothing, because Travis doesn't like it when all the jobs in a config file are conditional.
Build job testing Windows mingw and msys builds using keywords in commit message: https://travis-ci.com/github/GMLC-TDC/HELICS/builds/187930088
- MinGW seems to start compiling, but has build errors
- MSYS build is having issues; repo.msys2.org connection fails, likely issues with the msys2 repos
- Remove Linux jobs from Travis
- Remove macOS jobs from Travis
- Remove Travis Brewfiles
- Add empty Linux job

Remove Travis Linux/macOS jobs migrated to Azure

---

src/helics/core/core-data.hpp
src/helics/cpp98/Endpoint.hpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
tests/helics/shared_library/test-message-federate.cpp

partially Address Issues #1596 
Need to verify this actually does drop the message seamlessly yet but not in this PR.
add helicsMessageClear to C api
add clear method to C++ interfaces

add a message clear operation for Message to the C++/C/C++98 APi's

---

src/helics/application_api/Endpoints.cpp
src/helics/application_api/Endpoints.hpp
src/helics/application_api/MessageFederate.cpp
src/helics/application_api/MessageFederate.hpp
src/helics/application_api/MessageFederateManager.cpp
src/helics/application_api/MessageFederateManager.hpp
src/helics/cpp98/Endpoint.hpp
src/helics/cpp98/MessageFederate.hpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
tests/helics/application_api/FilterTests.cpp
tests/helics/application_api/MessageFederateAdditionalTests.cpp
tests/helics/application_api/MessageFederateKeyTests.cpp
tests/helics/apps/combo_tests.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/shared_library/badInputTests.cpp
tests/helics/shared_library/evilInputTests.cpp
tests/helics/shared_library/test-message-federate.cpp
tests/helics/shared_library/test-message-federate_cpp.cpp
tests/java/JavaHelicsApiTests.java

as per recommendation in Issue #1654
If merged this pull request will rename all methods helicsPendingMessages to helicsPendingMessageCount to better clarify what the function does.
Fix Issue #1654

move pendingMessages method to pendingMessagesCount

---

docs/user-guide/simulator_integration.md
interfaces/octave/octave_maps.i
src/helics/application_api/Inputs.cpp
src/helics/application_api/Inputs.hpp
src/helics/application_api/Publications.cpp
src/helics/application_api/ValueFederate.cpp
src/helics/application_api/ValueFederate.hpp
src/helics/application_api/helicsTypes.hpp
src/helics/cpp98/Endpoint.hpp
src/helics/cpp98/Input.hpp
src/helics/cpp98/Publication.hpp
src/helics/shared_api_library/MessageFederate.h
src/helics/shared_api_library/MessageFederateExport.cpp
src/helics/shared_api_library/ValueFederate.h
src/helics/shared_api_library/ValueFederateExport.cpp
tests/helics/application_api/ValueFederateAdditionalTests.cpp
tests/helics/application_api/ValueFederateKeyTests.cpp
tests/helics/application_api/subPubObjectTests.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/shared_library/TimingTests.cpp
tests/helics/shared_library/badInputTests.cpp
tests/helics/shared_library/evilInputTests.cpp
tests/helics/shared_library/test-message-federate.cpp
tests/helics/shared_library/test-value-federate1.cpp
tests/helics/shared_library/test-value-federate2.cpp
tests/helics/shared_library/test-value-federate2_cpp.cpp
tests/java/JavaHelicsApiTests.java
tests/octave/messageFedTests.m
tests/octave/messageFilterTests.m

If merged this pull request will address Issue #1647.  It removes a redundent raw from a few API calls related to messages

remove a redundant raw from some of the method names

---

.github/actions/setup-macos-10.9-sdk.sh
.github/workflows/release-build.yml
CMakeLists.txt

Install macOS 10.14 SDK and set macOS 10.14 as the deployment target for release builds.
If merged this pull request will set `LIBGUARDED_NO_DEFAULT` when the macOS deployment target is < 10.12, so if someone wants to try to mess with the default macOS stdlib to build on older versions of macOS < 10.14 they can try.
- Install macOS 10.14 SDK for release builds
- Update macOS deployment target version to 10.14 for release builds
- Set `LIBGUARDED_NO_DEFAULT` when building for macOS SDKs < 10.12
- Sets some workflow_dispatch things for testing

Update macOS deployment target to 10.14

---

.github/workflows/formatting.yml

Due to a CVE, set-env has been deprecated in GitHub Actions and will be disabled Nov 16. Looks like we only use it in the formatting action. Blog post: https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
If merged this pull request will replace the use of set-env with environment files. Docs on the new method: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
- Replace GitHub Actions set-env with environment files

Replace deprecated set-env in GitHub Actions

---

src/helics/core/CoreBroker.cpp
tests/helics/system_tests/QueryTests.cpp

If merged this pull request will address Issue #1667.
It will add a test for queries on disconnected targets and respond appropriately.  
It will also fix a bug in the marking of disconnected federates in the case of a multilayer broker scheme.

add a test for queries on disconnected targets

---

.github/workflows/compress-images.yml

If merged this pull request will add a workflow that tries to compress added images. For PRs the compressed images can be committed directly if they originated from the same repository.
A later addition (or change to this PR) could make it comment on PRs coming from forks with the results of compressing images, and open a PR when commits result in images that were able to be compressed.
- Add a compress images GitHub actions workflow

Create compress images GitHub Actions workflow

---

.github/actions/linux-release-builder/Dockerfile
.github/workflows/release-build.yml

If merged this pull request will pin the base docker image builds to hbb 2.1.0, one of the last ones using CentOS 6, and ensures a checkout step runs regardless of what triggered the workflow run. Workflow file change needs to get made to the master branch, pinning the docker image will need to make its way to the develop/helics3 branches. This PR will fix the nightly builds once merged into master+develop.
Latest test run: https://github.com/GMLC-TDC/HELICS/actions/runs/516313478
* Pin base docker image to HBB 2.1.0
* Run event ref checkout step for anything that isn't a scheduled build. If the ref (from client_payload) is set to nothing, then it defaults to checking out the current branch for the event.

Pin Linux release build Docker base image version to hbb 2.1.0

---

.pre-commit-config.yaml

If merged this pull request will pin the jumanjihouse pre-commit-hooks to the tagged 2.1.5 version, the latest release that fixes the shellcheck error.
- pin jumanjihouse/pre-commit-hooks rev to 2.1.5 tag

Pin jumanjihouse/pre-commit hooks to tag rev 2.1.5

---

.ci/.drone.yml

If merged this pull request will pin the Docker image used for ARM32 builds on Drone Cloud to `alpine:3.12`. If docker manages to fix their arm32 issues, newer versions of the alpine image should work again. 
* Pin the Docker image used for ARM32 builds on Drone Cloud to `alpine:3.12`

Pin Drone Cloud ARM32 build to alpine:3.12

---

src/helics/core/CommonCore.cpp
src/helics/core/TimeCoordinator.cpp
tests/helics/system_tests/TimingTests2.cpp

FIx issue using 'offset' property if the first interval is not used.  
brought up in [Gitter](https://gitter.im/GMLC-TDC/HELICS?at=6050e015d74bbe49e0fb1ac0)
fix a few warnings as well

Fix offset timing bug

---

.ci/.drone.yml
.ci/azure-pipelines.yml
.circleci/config.yml
.cirrus.yml
.github/workflows/formatting.yml
appveyor.yml

If merged this pull request will add a keyword for skipping ci builds to the PR title and modify the config files for the various CI services to run less frequently (never on the pre-commit formatting branch).
The ci skipping keyword shouldn't propagate into the squashed commit messages with this setup.
* Include ci skipping keyword in PR title to skip running on Drone on formatting PRs
* Run Drone for all non-formatting PRs and commits to `master`, `main`, `develop`, and `helics3`
* Run CircleCI and Cirrus for pushes and PRs except those in or from a `pre-commit/` branch
* Run Appveyor only for PRs/pushes to `master`, `main`, `develop`, and `helics3`
* Exclude Azure Pipelines from running on `pre-commit` branches
* Run Azure Pipelines for PRs targeting `master`, `main`, `develop`, and …

Skip CI builds for automated formatting PRs/commits

---

src/helics/core/CommonCore.cpp
src/helics/core/FilterFederate.cpp
src/helics/core/TimeCoordinator.cpp
src/helics/core/TimeCoordinator.hpp
src/helics/core/TimeDependencies.cpp
src/helics/core/TimeDependencies.hpp
tests/helics/apps/RecorderTests.cpp
tests/helics/system_tests/TimingTests2.cpp

If merged this pull request will add a few checks to the barrier clear operation and fix a potential issue with the timings.  
also resolve some Msan failures from previous merges. 
Attempt to resolve #1750

Barrier check

---

.github/actions/benchmark-build/benchmark-Windows.sh
.github/actions/common/Windows/find-cpack.sh
.github/actions/common/Windows/install-boost.sh
.github/actions/release-build/installer-Windows.sh
.github/actions/release-build/msvc-Windows.sh
.github/actions/release-build/shared-library-Windows.sh

If merged this pull request will install the Boost 1.74 headers needed to build HELICS for the GitHub Actions workflows running on Windows -- release builds and benchmark installers.
This addresses the same issue of Boost getting removed from the virtual environments as Azure Pipelines had.
Benchmarks run: https://github.com/GMLC-TDC/HELICS/actions/runs/680686297
Releases run: https://github.com/GMLC-TDC/HELICS/actions/runs/680686725
- Install Boost 1.74 for Windows release build packaging and benchmark installer GitHub Actions workflows
- Comment and minor clean-up of the scripts used for the Windows GHA workflows

Install Boost for Windows GitHub Actions Workflows

---

.ci/azure-pipelines.yml
.travis.yml
scripts/setup-helics-ci-options.sh

If merged this pull request will add the Linux and macOS builds on Azure Pipelines from HELICS 3 to the HELICS 2 develop branch. Deprecated Python SWIG interface build+test doesn't run on the Linux or macOS builds.
- Backport Azure Pipelines Linux and macOS builds for each commit from HELICS 3 to HELICS 2
- Remove macOS builds and most of the Linux builds from the HELICS 2 Travis CI config

Switch HELICS 2 develop branch CI from Travis to Azure Pipelines

---

.cirrus.yml

If merged this pull request will update the FreeBSD CI build to 12.2, which seems to resolve the zmq related build error.
- Update FreeBSD CI build to 12.2

Update HELICS 2 FreeBSD CI build to 12.2

---

CMakeLists.txt
docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md
vcpkg.json

If merged this pull request will enable vcpgk to be used as a dependency manager for HELICS dependencies when building from source.
- Adds vcpkg.json manifest file
- Add some info on using vcpkg to manage dependencies to docs on building HELICS from source

Add vcpkg manifest file

---

config/cmake/FindZeroMQ.cmake

If merged this pull request will add ZMQ 4.3.3 and 4.3.4 to the ZeroMQ versions lists when searching for ZMQ libraries compiled for MSVC.
- Add ZeroMQ 4.3.3 and 4.3.4 to the version list in FindZeroMQ.cmake

Add support for finding MSVC ZMQ library versions 4.3.3 and 4.3.4

---

config/cmake/addZeroMQ.cmake
docs/installation/helics_cmake_options.md

If merged this pull request will default the `HELICS_USE_ZMQ_STATIC_LIBRARY` to `ON` if only the static zmq library is found. Otherwise, it will continue to default to `OFF`.
- Default HELICS_USE_ZMQ_STATIC_LIBRARY=ON if only the static zmq library is found

Default HELICS_USE_ZMQ_STATIC_LIBRARY=ON if only the static zmq library is found

---

.github/workflows/compress-images.yml

If merged this pull request will fix the condition for the compress images workflow so it compresses images automatically for branches originating from the HELICS repo.
After this change, the next PR that updates images will also optimize the existing images in the repo -- https://github.com/GMLC-TDC/HELICS/pull/1888 has a test run.
- Change `==` to `!=` when deciding whether or not to open a PR for the compress images workflow

Fix compress images workflow condition

---

.github/workflows/code-coverage.yml

If merged this pull request will disable building the Java interface for the code coverage CI workflow.
- Disable Java interface for code coverage builds

Disable Java interface for code coverage builds

---

src/helics/application_api/Federate.cpp
src/helics/application_api/FederateInfo.cpp
src/helics/application_api/FederateInfo.hpp
src/helics/core/ActionMessage.cpp
src/helics/core/ActionMessageDefintions.hpp
src/helics/core/BrokerBase.cpp
src/helics/core/BrokerBase.hpp
src/helics/core/CommonCore.cpp
src/helics/core/CommonCore.hpp
src/helics/core/CoreBroker.cpp
src/helics/core/CoreBroker.hpp
tests/helics/application_api/ValueFederateAdditionalTests.cpp
tests/helics/core/CMakeLists.txt
tests/helics/core/CoreOperationsTests.cpp
tests/helics/test_files/name_config1.json
tests/helics/test_files/name_config2.json

If merged this pull request will remedy the issues highlighted in #1747 by changing the default way core names are generated to include a random string component in all names.  
-  fix core naming issue
- add a maximum federate option to cores and brokers
- add some tests of the naming issue and max federate fields

Core naming fix

---

src/helics/common/JsonBuilder.cpp
src/helics/common/JsonBuilder.hpp
src/helics/core/BrokerBase.cpp
src/helics/core/BrokerBase.hpp
src/helics/core/CommonCore.cpp
src/helics/core/CommonCore.hpp
src/helics/core/CoreBroker.cpp
src/helics/core/CoreBroker.hpp
src/helics/core/FederateState.cpp
src/helics/core/FederateState.hpp
tests/helics/system_tests/QueryTests.cpp

If merged this pull request will add timeouts for queries, In the rare case that a disconnect and query cross paths.  The query will timeout and result in a timeout result.  
The query timeout can be controlled via command line 
- add the command line option for query timeouts
- add timeout management code for local queries
- add tickforwarding controls in the broker base with reasons (and flexibility for adding more reasons in the future).  
- update the concurrency library with some new methods to the the delayedObject class.
- clean up the queries on disconnect from a core
This is in response to some reported bugs about queries hanging

Query timeouts

---

vcpkg.json

If merged this pull request will update the HELICS version in vcpkg.json to 2.7.1; probably should've been done for the tagged release, but I think the only effect of this is that the version number will be misreported by vcpkg.
- Update vcpkg.json to 2.7.1

Update HELICS version to 2.7.1 in vcpkg file

---

.github/workflows/compress-images.yml

If merged this pull request will switch to using `calibreapp/image-actions@main` instead of `calibreapp/image-actions@master`
- Use calibreapp/image-actions@main for compressing images workflow

Use calibreapp/image-actions@main for compressing images

---

tests/helics/application_api/FederateTests.cpp
tests/helics/application_api/FilterAdditionalTests.cpp
tests/helics/application_api/FilterTests.cpp
tests/helics/application_api/LoggingTests.cpp
tests/helics/application_api/ValueFederateKeyTests.cpp
tests/helics/application_api/zmqSSTests.cpp
tests/helics/apps/BrokerAppTests.cpp
tests/helics/apps/BrokerServerTests.cpp
tests/helics/apps/CloneTests.cpp
tests/helics/apps/CoreAppTests.cpp
tests/helics/apps/EchoTests.cpp
tests/helics/apps/PlayerTests.cpp
tests/helics/apps/RecorderTests.cpp
tests/helics/apps/TracerTests.cpp
tests/helics/core/CoreFactory-tests.cpp
tests/helics/core/MessageTimerTests.cpp
tests/helics/network/IPCcore_tests.cpp
tests/helics/network/TcpCore-tests.cpp
tests/helics/network/TcpSSCore-tests.cpp
tests/helics/network/UdpCore-tests.cpp
tests/helics/network/ZeromqCore-tests.cpp
tests/helics/network/ZeromqSSCore-tests.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/system_tests/ErrorTests.cpp
tests/helics/system_tests/TimingTests2.cpp
tests/helics/system_tests/brokerTimeoutTests.cpp
tests/helics/system_tests/commandInterfaceTests.cpp
tests/helics/system_tests/federateRealTimeTests.cpp
tests/helics/system_tests/iterationTests.cpp

If merged this pull request will add missing `#include <thread>` to various tests to fix compile errors related to `sleep_for` with gcc 11
[Test run with successful compilation using the changes in this PR + the gcc 11 builder](https://dev.azure.com/HELICS-test/HELICS/_build/results?buildId=9443&view=logs&j=5d41f8ef-4f47-598d-e8d3-02d64667fe0e&t=9664420a-373e-55ce-5034-64407dcf183d)
- Add `#include <thread>` to tests using `sleep_for`

Add missing #include <thread> to tests

---

.ci/azure-pipelines.yml
scripts/ci-build.sh

If merged this pull request will bump the CI builds for the newest gcc and clang builds from gcc 10 to gcc 11, and clang 10 to clang 12. Addresses #1962 and #1963 
- Update the gcc-10 builder to gcc-11
- Update the clang-10 builder to clang-12

Use latest gcc and clang releases for CI builds

---

tests/helics/application_api/FederateTests.cpp
tests/helics/application_api/FilterAdditionalTests.cpp
tests/helics/application_api/FilterTests.cpp
tests/helics/application_api/LoggingTests.cpp
tests/helics/application_api/ValueFederateKeyTests.cpp
tests/helics/application_api/zmqSSTests.cpp
tests/helics/apps/BrokerAppTests.cpp
tests/helics/apps/BrokerServerTests.cpp
tests/helics/apps/CloneTests.cpp
tests/helics/apps/CoreAppTests.cpp
tests/helics/apps/EchoTests.cpp
tests/helics/apps/PlayerTests.cpp
tests/helics/apps/RecorderTests.cpp
tests/helics/apps/TracerTests.cpp
tests/helics/core/CoreFactory-tests.cpp
tests/helics/core/MessageTimerTests.cpp
tests/helics/network/IPCcore_tests.cpp
tests/helics/network/TcpCore-tests.cpp
tests/helics/network/TcpSSCore-tests.cpp
tests/helics/network/UdpCore-tests.cpp
tests/helics/network/ZeromqCore-tests.cpp
tests/helics/network/ZeromqSSCore-tests.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/system_tests/ErrorTests.cpp
tests/helics/system_tests/TimingTests2.cpp
tests/helics/system_tests/brokerTimeoutTests.cpp
tests/helics/system_tests/federateRealTimeTests.cpp
tests/helics/system_tests/iterationTests.cpp

If merged this pull request will add `#include <thread>` to test files that use `sleep_for`.
- Add `#include <thread>` to test files that use `sleep_for`

Add missing #include <thread> to tests (backported)

---

.ci/azure-pipelines.yml
scripts/ci-build.sh

If merged this pull request will backport the CI build updates from HELICS3 and update CI builds to use gcc 11 and clang 12.
* Use latest gcc and clang releases for CI builds
- Update the gcc-10 builder to gcc-11
- Update the clang-10 builder to clang-12
* Update CI job names to match new compiler versions
* Load mpi module on Fedora builders
* Check if the module command exists before trying to run it

Use latest gcc and clang releases for HELICS 2 CI builds

---

docs/user-guide/advanced_topics/advanced_topics_index.md

Final user guide changes for the v3 release
Shuffling files around, cleaning up links, getting content linked into the RTD TOC correctly.

Rtd link cleanup

---

README.md

If merged this pull request will remove the html details tags surrounding the optional 3rd party components in the README -- the markdownlint ruby gem doesn't handle the markdown links correctly when they are in that section.
There is a nodejs markdownlint tool that could be considered as an alternative, but the config file format might not be compatible with the current tool used.
- Remove html `<details>` tags surrounding the optional 3rd party components in the README

Remove README in-line html details tag to fix linting error

---

docs/references/api-reference/index.md
scripts/render-doxyfile.py

Replace PROJECT_SOURCE_DIR instead of CMAKE_CURRENT_SOURCE_DIR when creating the Doxyfile for RTD builds

Fix doxygen read the docs build

---

.github/workflows/formatting.yml
.pre-commit-config.yaml

If merged this pull request will update the formatting workflow to use pre-commit/action v2.0.3
- update the formatting workflow to use pre-commit/action v2.0.3
- update hooks to latest versions
- set ci skip so pre-commit.ci doesn't try to run clang-format (fails due to no docker)

Upgrade pre-commit hooks and skip clang-format on pre-commit.ci

---

src/helics/network/tcp/TcpHelperClasses.cpp
src/helics/network/tcp/TcpHelperClasses.h

If merged this pull request will switch to use functions for reading and writing to sockets that are compatible with the AsyncReadStream and AsyncWriteStream interfaces, and ensure that low level socket operations are done on the underlying. This is a step towards making the tcp helper classes useable for encrypted communication.
- Use AsyncReadStream and AsyncWriteStream interface compatible I/O functions for sockets
- Ensure the asio basic_stream_socket is used for several lower level socket functions that might not be exported by various stream wrappers

Use ASIO AsyncWriteStream and AsyncReadStream compatible functions for I/O and lowest layer socket for low level socket operations

---

src/helics/common/AsioContextManager.h

If merged this pull request will remove a fix for `ASIO_ERROR_CATEGORY_NOEXCEPT` not getting set correctly due to Boost 1.58 not setting `BOOST_NOEXCEPT`. This change will be needed to use anything included from the asio ssl headers.
- Removed redefinition of `ASIO_ERROR_CATEGORY_NOEXCEPT` that was needed for Boost 1.58 compatibility

Remove fix for ASIO_ERROR_CATEGORY_NOEXCEPT definition bug affecting Boost 1.58

---

src/helics/common/AsioContextManager.h
src/helics/core/FederateState.cpp
src/helics/core/TimeCoordinator.cpp
src/helics/core/TimeCoordinator.hpp
src/helics/helics_enums.h
src/helics/shared_api_library/api-data.h
tests/helics/system_tests/commandInterfaceTests.cpp

which triggers like the event_driven flag, and a fix for a command call if none exists.
tweaking the timing a little on cases with requests for infinite time, see if that fixes any of the sporadic failures

Add in a check for requesting large times 

---

.ci/.drone.yml

If merged this pull request will replace the docker:git container (often unavailable) used for the git submodule clone step on Drone CI with alpine/git for the aarch64 job, and alpine:3.12 with apk install for git on arm32 builds.
- Replace docker:git container with alpine/git container for aarch64 Drone CI build
- Replace docker:git container with alpine:3.12 and an apk install command for git on arm32 Drone CI build

Replace docker:git container for git submodule clone step on arm Drone CI builds

---

.ci/azure-pipelines.yml

If merged this pull request will update the clang-12 build to clang-13.
Changes options to only enable MPI for the gcc builds -- the mpicc wrappers were ignoring CC/CXX set to clang and turning the clang builds into just another gcc build; the docs mention setting MPICH_CC, MPICH_CXX variables (and OMPI equivalents for OpenMPI), but notes that using a compiler different than the one used to build MPICH can cause problems.
- Update Azure Pipelines clang12 CI build to clang13
- Disable MPI for the clang builds

Update CI build to clang13-builder

---

interfaces/CMakeLists.txt

If merged this pull request will add an error message that can't be ignored for if a user tries to build the Python interface, pointing them to `pip install helics` and the pyhelics docs/repository, with instructions on how to unset the CMake variable to dismiss the error message.
The two old option were `BUILD_PYTHON_INTERFACE` and `BUILD_PYTHON2_INTERFACE`. To catch users that thought the option names may have been changed to match the other interfaces, checks for `HELICS_BUILD_PYTHON_INTERFACE` and `HELICS_BUILD_PYTHON2_INTERFACE`.
- Add error message notifying user about the new Python interface if cmake is configured with an argument for building the python interface

Give an error for attempted Python interface builds

---

config/cmake/addBoost.cmake
src/helics/network/ipc/IpcQueueHelper.cpp

If merged this pull request will backport the Boost 1.77 fix to HELICS 2 for the IPC core.
* Fix building IPC core with Boost 1.77.0
* Use type aliases for posix_time and microsec_clock

Backport Boost 1.77 fix to HELICS 2

---

src/helics/application_api/BrokerApp.hpp
src/helics/application_api/CoreApp.hpp
src/helics/apps/helicsWebServer.cpp

If merged this pull request will backport the LIBCPP aligned alloc fix to HELICS 2.
- Backport the libcpp aligned alloc fix to HELICS 2

Backport libcpp aligned alloc fix to HELICS 2

---

src/helics/network/CMakeLists.txt

If merged this pull request will only link with the helics::zmq library when the ZeroMQ core is disabled -- even with an empty helics::zmq imported target, it can still factor into the CMake calculating targets that must be in an export set.
- Only link `helics` C shared library with helics::zmq when the ZeroMQ core is enabled

Remove helics::zmq target dependency when ZMQ core is disabled

---

CMakeLists.txt

If merged this pull request will remove setting a FindThreads output result variable that signals WIN32 threads are being used, and combine all the non-Windows thread cases into a single check.
- Remove (redundant) setting the FindThreads.cmake output variable `CMAKE_USE_WIN32_THREADS_INIT`
- Combine the conditions for setting `THREADS_PREFER_PTHREAD_FLAG`

Remove setting of FindThreads output result variable

---

src/helics/core/CommonCore.cpp
src/helics/core/EndpointInfo.hpp
src/helics/core/flagOperations.hpp
tests/helics/application_api/MessageFederateAdditionalTests.cpp

If merged this pull request will tweak the operation of `sendTo` and `sendToAt` for targeted endpoints.  Basically setting and empty destination will result in equivalent behavior to `send` and `sendAt`.  And if a destination is specified it must be in the target list,  if not an exception is generated.  
This is a change from previous behavior where those function would just generate a blanket exception for  targetedEndpoints.  This allows specific messages to be sent to specific destinations within known targets.

Targeted endpoint target specification

---

docs/user-guide/installation/linux.md
examples/comboFederates1/comboFed.cpp
examples/comboFederates1/run.sh
examples/comboFederates1/run3.sh

Small documentation changes to fix the instructions for installing under Ubuntu. Small changes to get the comboFederate example working to validate the installation. I've tested to confirm comboFed builds and runs properly with the new run shell scripts.
Fixes issue #2263.
A similar PR will be made provide these fixes to develop. This PR is being applied directly to main so that the public documentation will be fixed more quickly.

Update Linux install and comboFed examples - hotfix main

---

.github/workflows/code-coverage.yml
.github/workflows/release-build.yml

If merged this pull request will run the code coverage job nightly on the develop branch instead of on PRs to main/develop or pushes to develop. Some of the flaky tests that seem to happen more consistently with the code coverage builds need to get fixed before the job becomes useful again -- workflow dispatch trigger can be used to trigger it on individual branches to test if a change resolves some of the failing tests.
- Add nightly scheduled code coverage build for the develop branch
- Remove PR and push triggers for the develop branch code coverage builds
- Remove PR trigger for main branch code coverage builds

Switch Code Coverage job to running nightly

---

src/helics/apps/CMakeLists.txt
tests/helics/application_api/CMakeLists.txt
tests/helics/application_api/FederateTests.cpp
tests/helics/application_api/zmqSSTests.cpp
tests/helics/apps/MultiBrokerTests.cpp
tests/helics/network/InprocCore-Tests.cpp
tests/helics/system_tests/ErrorTests.cpp
tests/helics/system_tests/networkTests.cpp

If merged this pull request will update a few more spots where the HELICS option names changed for enabling cores, that had resulted in tests being disabled. It will also update HELICS_BROKER_LOC to actually point to the build folder where the helics_broker binary is located.
- Update `HELICS_BROKER_LOC` and `HELICS_BROKER_SERVER_LOC` to point to `${CMAKE_RUNTIME_OUTPUT_DIRECTORY}` (runtime output build folder was changed to place all binaries in a top level build/bin folder instead of scattered around)
- Update several places where the old option to check if a core was enabled had still been used, re-enabling several tests
- Update `helics::core_type` to `helics::CoreType` in tests that are now re-enabled
- Update `helics_error_user_abort` to `HELICS_ERROR_USER_ABORT` in re-enabled tests

Update HELICS options for network tests and helics_broker build location

---

docs/user-guide/installation/windows.md

If merged this pull request will fix some markdown linting errors from pre-commit that were missed in #2313.
- Fix markdown linting errors from pre-commit
```shell
docs/user-guide/installation/windows.md:19: MD026 Trailing punctuation in header
docs/user-guide/installation/windows.md:76: MD026 Trailing punctuation in header
docs/user-guide/installation/windows.md:127: MD040 Fenced code blocks should have a language specified
docs/user-guide/installation/windows.md:147: MD040 Fenced code blocks should have a language specified
docs/user-guide/installation/windows.md:154: MD040 Fenced code blocks should have a language specified
docs/user-guide/installation/windows.md:161: MD040 Fenced code blocks should have a language specified
```

Fix pre-commit markdown linting errors on Windows installation doc file

---

scripts/_git-all-archive.sh

If merged this pull request will fix the script that generates the HELICS source archive that includes submodule code for the HELICS releases.
- recursive git submodule update to ensure submodules used by dependencies also get checkedout (e.g. NetIF in the `networking` submodule)
- use `$displaypath` instead of `$path` (or `$sm_path`, https://git-scm.com/docs/git-submodule/2.24.0 has more info on these variables) for the prefix, so the full relative path (from the HELICS repo root folder) to submodule folder is preserved (so that e.g. `ThirdParty/networking/ThirdParty/concurrency` is unpacked to `ThirdParty/networking/ThirdParty/concurrency` instead of `ThirdParty/concurrency`; or so `ThirdParty/networking/ThirdParty/NetIF` doesn't get unpacked to `ThirdParty/NetIF`)
- include …

Fix missing submodule source code in the HELICS release source archive

---

src/helics/core/TimeCoordinator.cpp
src/helics/core/TimeDependencies.cpp
src/helics/core/TimeDependencies.hpp
tests/helics/system_tests/iterationTests.cpp

Fix a bug when moving to executing mode with wait for current time flag and other federates are requesting iteration at time 0.
Address at least part of the remaining issues with #2342.

bug fix on iteration, enter executing mode, and wait for current time flag

---

tests/helics/application_api/LoggingTests.cpp
tests/helics/system_tests/QueryTests.cpp

If merged this pull request will try to resolve some deadlock issues with the log buffer tests
I suspect the issue was destructor ordering on some compilers combined with sporadic delayed logging on some of the tests which could have caused a deadlock in the destructors.

look at the failures in the log buffer tests

---

CMakeLists.txt
src/helics/core/CoreFactory.cpp
src/helics/core/FederateState.cpp
src/helics/cpp98/Federate.hpp
src/helics/shared_api_library/CMakeLists.txt
src/helics/shared_api_library/FederateExport.cpp
src/helics/shared_api_library/MessageFederateExport.cpp
src/helics/shared_api_library/MessageFiltersExport.cpp
src/helics/shared_api_library/TranslatorExport.cpp
src/helics/shared_api_library/ValueFederateExport.cpp
src/helics/shared_api_library/backup/helics/helics.h
src/helics/shared_api_library/backup/helics/helics_api.h
src/helics/shared_api_library/helicsCore.h
src/helics/shared_api_library/helicsExport.cpp
src/helics/shared_api_library/internal/api_objects.h
tests/helics/shared_library/SystemTests.cpp

so federates can be found later if freed but not destroyed
If merged this pull request will add helicsFederateProtect and helicsFederateUnProtect

add protection functions in the C API 

---

.github/workflows/code-coverage.yml

Fixes the errors when fetching submodules using CMake for the nightly Code Coverage build about a different user owning the repository by having the checkout action clone submodules.

Fetch submodules using actions/checkout for scheduled Code Coverage build

---

.github/actions/setup-macos-sdk.sh
.github/workflows/release-build.yml

Removing ghc::filesystem has made the minimum required version of macOS 10.15 due to functions not provided in std::filesystem until 10.15 or later.

Increase minimum macOS target version to 10.15

---

docs/user-guide/installation/helics_cmake_options.md

Adds a missing advanced option to the HELICS docs page on CMake options.

Add HELICS_DISABLE_C_SHARED_LIB to CMake Options

---

.gitignore
CMakeLists.txt
vcpkg.json

If merged this pull request will add the encryption feature to the vcpkg.json file that adds openssl as a dependency to install, along with a few other vcpkg related tweaks.
- Add encryption feature to vcpkg.json for installing OpenSSL
- Add `vcpkg_installed/` directory to `.gitignore` (local cache of compiled copies of all dependencies built by vcpkg, both debug and release variants by default)
- Set `VCPKG_MANIFEST_FEATURES` variable based on CMake options used; if vcpkg isn't getting used, this variable will just be ignored

Add encryption feature to vcpkg support

---

.ci/azure-pipelines.yml

If merged this pull request will update the macOS versions used for Azure CI tests. Closes #2404.
- Change newest macOS build to XCode 13 on macOS 12
- Change oldest macOS build to XCode 11 on macOS 11

Change macOS Azure CI images to XCode 13 on macOS 12 and XCode 11 on macOS 11

---

.ci/.drone.yml

If merged this pull request will disable the arm32 builds on Drone Cloud -- they no longer have arm32 servers, unknown if they'll be able to find a replacement: https://community.harness.io/t/drone-cloud-arm-builds-step-stuck-pending-forever/12437/3
- Disable arm32 pipeline for Drone Cloud configuration

Disable arm32 builds on Drone Cloud

---

.ci/azure-pipelines-daily.yml
.ci/azure-pipelines.yml
.github/actions/benchmark-build/benchmark-Linux.sh
.github/actions/benchmark-build/benchmark-Windows.sh
.github/actions/benchmark-build/benchmark-macOS.sh
.github/actions/release-build/installer-Linux.sh
.github/actions/release-build/installer-Windows.sh
.github/actions/release-build/installer-macOS.sh
.github/actions/release-build/msvc-Windows.sh
.github/actions/release-build/shared-library-Linux.sh
.github/actions/release-build/shared-library-Windows.sh
.github/actions/release-build/shared-library-macOS.sh
.github/workflows/benchmark-package.yml
.github/workflows/code-coverage.yml
.github/workflows/msys2.yml
CMakeLists.txt

If merged this pull request will unset VCPKG_ROOT in GitHub Actions virtual environments used for building HELICS. This addresses a recent change to the default runtime environment made by GitHub.

Disable VCPKG_ROOT in GHA and Azure builds

---

.github/RELEASE_CHECKLIST_TEMPLATE.md
.github/workflows/create-release-checklist.yml

If merged this pull request will add a workflow that opens a checklist of tasks for new HELICS releases.
An example of what the resulting issue looks like can be seen [here](https://github.com/nightlark/HELICS/issues/20).
- Add create release checklist workflow to open an issue with the release checklist
- Add a template file with the contents of the checklist

Add workflow to open checklist of tasks for new HELICS releases

---

src/helics/core/TimeDependencies.cpp
tests/helics/system_tests/commandInterfaceTests.cpp

If merged this pull request will try to fix some of the sporadic failures in the CI tests.  
There was a potential case where one federate would have advanced to granted but the other federate was still waiting to be granted executing mode but the condition didn't check for that.  If that is the case this fix will resolve that edge case.  It is also likely that the edge case would be extremely unlikely to occur in actual practice since most federates do not operate like that and there simply would have been a slight delay before progressing, which could explain why this bug had never been observed in any real situation, only in the test environment on low thread count systems and why it is very rare even in the CI tests.

tweak the exec check when using wait for current time flag

---

CHANGELOG.md
docs/user-guide/advanced_topics/advanced_topics_index.md
docs/user-guide/advanced_topics/encrypted_communication.md
docs/user-guide/orientation.md
src/helics/application_api/FederateInfo.cpp
tests/helics/test_files/encryption_config/openssl_certs/ssl_encryption_config.json.in

If merged this pull request will add documentation on using encrypted communication.
- Add documentation on using encrypted communication
- Add support for environment variables to enable encryption for federates (to match support in the broker)
- Remove unused encryption test file
- Update CHANGELOG

Add documentation on encrypted communication

---

README.md

If merged this pull request will remove the Drone CI build status badge from the README. Drone CI has been deactivated since builds just haven't been starting.
- Remove Drone CI build status badge from the README

Remove Drone CI badge from the README

---

.github/workflows/swig-interface-gen.yml

If merged this pull request will switch the swig interface update workflow from using our gmlc-tdc/create-pr-action (which seems to be having some issues) to peter-evans/create-pull-request. This action is likely to be much better maintained than our own, and at this point has all of the features that had previously led to us creating our own action for opening a PR.
- Switch from gmlc-tdc/create-pr-action to peter-evans/create-pull-request for opening PRs with the swig-interface-gen workflow

Switch from gmlc-tdc/create-pr-action to peter-evans/create-pull-request

---

docs/user-guide/installation/windows.md

Adds note about additional environment variable to set when building on Windows.

Add note for Windows to set `Boost_INCLUDE_DIR`

---

docs/user-guide/installation/docker.md

If merged this pull request will update the docker instructions to build using a base image of Ubuntu 22.04 rather than 18.04 which no longer builds.  This fixes #2593.
Change the build instructions to use Ubuntu 22.04 as base.  Within the documented Dockerfile the changes are:
- Install `libboost-all-dev` rather than individual boost package for the `builder` (since we don't care about size for this)
- clone with `--recurse-submodules`
- use modern `cmake --build` syntax to eliminate steps
- specify "Release" build to make smaller image
- combine installation steps in target version
- update install to include `pip` and up-to-date versions of boost components

Update docker instructions to use Ubuntu 22.04

---

.github/workflows/benchmark-package.yml
.github/workflows/release-build.yml

If merged this pull request will change the uploaded artifact name to be unique; this is a new requirement for the upload-artifact v4 action. The separate download-artifact steps are also combined into a single step (by omitting the `name`).
- Make the upload artifact name unique for benchmark package artifacts
- Make the upload artifact name unique for release package artifacts
- Combine the download-artifact steps into a single step
- Switch type of input for which release artifacts to build to a choice instead of free-form input field

Fix workflow artifacts

---

.github/workflows/release-build.yml

Switches from using repository_dispatch events (which require sending a json payload) to sending a workflow_dispatch event to trigger the helics-packaging workflow for release builds. Enables easier manual triggering of the same helics-packaging workflow if necessary (e.g. some step in the release build failed).

Trigger helics-packaging workflows using workflow_dispatch

---

CHANGELOG.md
CMakeLists.txt

Update the release date in the docs to match the actual date 3.5.2 is coming out.

Bump 3.5.2 release date in docs to Apr 5

---

.ci/azure-pipelines.yml

The macOS-12 runner is going away at the start of December, and we'll start seeing random failures during brownouts in the next couple of weeks. Bump the oldest macOS version tested to macOS-13, and the newest version to macOS-14.

Update Azure Pipelines macOS CI runner VMs

---

src/helics/application_api/Federate.cpp
src/helics/application_api/Federate.hpp
src/helics/application_api/FilterOperations.cpp
src/helics/application_api/FilterOperations.hpp
src/helics/application_api/Filters.cpp
src/helics/application_api/Filters.hpp
src/helics/cpp98/Filter.hpp
src/helics/helics_enums.h
src/helics/shared_api_library/FederateExport.cpp
src/helics/shared_api_library/MessageFilters.h
src/helics/shared_api_library/MessageFiltersExport.cpp
src/helics/shared_api_library/backup/helics/helics.h
src/helics/shared_api_library/backup/helics/helics_api.h
src/helics/shared_api_library/helicsApps.h
src/helics/shared_api_library/helicsAppsExport.cpp
src/helics/shared_api_library/helicsAppsExportNull.cpp
src/helics/shared_api_library/helicsCore.h
src/helics/shared_api_library/internal/api_objects.h
tests/.clang-tidy
tests/helics/application_api/FederateTests.cpp
tests/helics/application_api/FilterAdditionalTests.cpp
tests/helics/application_api/FilterTests.cpp
tests/helics/sequencing_tests/Sequencing1.cpp
tests/helics/shared_library/FilterTests.cpp
tests/helics/shared_library/appTests.cpp

If merged this pull request will add mechanics for getting filter properties

add mechanics for retrieving filter properties.

---

src/helics/shared_api_library/helicsAppsExportNull.cpp

If merged this pull request will fix a compile error when building with HELICS Apps, due to a missing semicolon.

Fix compile error when building without HELICS Apps

---

.github/actions/benchmark-build/benchmark-Linux.sh
.github/actions/common/Windows/install-boost.sh
.github/actions/linux-release-builder/Dockerfile
.github/actions/release-build/installer-Linux.sh
.github/actions/release-build/shared-library-Linux.sh
src/helics/shared_api_library/helicsAppsExportNull.cpp

If merged this pull request will fix the Linux release and benchmark builds by updating to a newer version of CMake (3.25) and Boost (1.75).
CMake 3.25 is roughly the last release with CMake binaries that are compiled with CentOS 5/manylinux1/glibc 2.5 support.
Depends on #2707.

Use CMake 3.25 and Boost 1.75 for Linux release builder

---

src/helics/network/mpi/MpiComms.cpp

Removes Boost from the one place it is used in the MPI core, for a scope exit macro.

Remove use of Boost for a scope exit guard in the MPI core

---

.ci/azure-pipelines-daily.yml

Updates image used for daily Azure pipelines CI jobs to Ubuntu 22.04, to meet the minimum CMake 3.22 build requirement.

Update daily Azure pipelines builds to use Ubuntu 22.04 container image

---

config/cmake/addBoost.cmake
src/helics/apps/helicsWebServer.cpp
tests/helics/webserver/webServerWebSocketTests.cpp

If merged this pull request will remove some usages of deprecated boost features which were removed in boost 1.87 now that we only support back to 1.73

update to work with boost 1.87

---

src/helics/shared_api_library/CMakeLists.txt

The linker included with the zig c/c++ compiler doesn't support the exported_symbols_list linker option on macOS. For c/c++ compilation, I think zig is just using llvm/clang, but I guess they don't use the linker from llvm.

Add check for exported_symbols_list linker option on macOS

---

CMakeLists.txt
docs/user-guide/installation/helics_cmake_options.md
docs/user-guide/installation/linux.md

Adds a check to determine if a system requires linking to libatomic. This makes so the riscv builds on Yggdrasil no longer need to apply a patch to our CMake build scripts, and should make so users no longer need to specify `HELICS_BUILD_CONFIGURATION=PI` when building on a Raspberry Pi.
Resolves #2718

Add check for systems that require linking to libatomic
