GMLC-TDC/HELICS

- .travis.yml
- scripts/install-ci-dependencies.sh
- src/helics/application_api/Filters.cpp
Mac Travis CI config that builds on OSX 10.10 and 10.11
> Mac Travis CI config

- swig/python/CMakeLists.txt
> Fix long long warnings

- swig/python/CMakeLists.txt
> Fix no-overlength-strings warnings

- CMakeLists.txt
- appveyor.yml
Merge this when you are ready to update master and tag a new release
> Version update

- src/helics/common/AsioServiceManager.cpp
- src/helics/common/AsioServiceManager.h
- src/helics/core/helicsVersion.cpp
This is a potential fix for issue #135 and possibly #134.  I think it deals with one possible symptom of that problem, but I am not totally convinced it totally solved the problem.  Still working on that.
> Possible fix for issue #135.

- tests/helics/application_api/test-message-federate.cpp
- tests/helics/common/CMakeLists.txt
- tests/helics/common/TimeTests.cpp
add tests for the time object and for endpoint callbacks
> Tests for endpoint callbacks and time  Issues #142 and #140

- .travis.yml
- CMakeLists.txt
- appveyor.yml
merge in version string updates
> update version string in a few spots

- .codacy.yml
- CMakeLists.txt
- docs/CMakeLists.txt
- docs/apps/App.md
- docs/apps/Broker.md
- docs/apps/index.md
- docs/configuration/CoreTypes.md
- docs/configuration/Federate.md
- docs/configuration/Filters.md
- docs/configuration/MessageFederate.md
- docs/configuration/Timing.md
- docs/configuration/ValueFederate.md
- docs/configuration/index.md
- examples/CppInterface/nonlings_fed1.cpp
- examples/CppInterface/pi_receiver2.cpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/core-data.hpp
- src/helics/core/helics-broker.cpp
- src/helics/cpp98/Federate.hpp
- src/helics/cpp98/ValueFederate.hpp
- tests/helics/apps/test_files/example2.record
This is some additional documentation I have been working on the last few days to finish up a few of the issues related to documentation
> Documentation update

- docs/apps/Source.md
- examples/messageFederates1/CMakeLists.txt
- examples/messageFederates1/messageFedObj.cpp
- src/helics/application_api/Endpoints.hpp
and a few minor code tweaks on endpoints
> add a message federate example using Endpoint objects

- appveyor.yml
Builds the Java interface on Appveyor
> Build Java interface on Appveyor

- src/helics/common/DualMappedPointerVector.hpp
- src/helics/common/DualMappedVector.hpp
- src/helics/common/MappedPointerVector.hpp
- src/helics/common/MappedVector.hpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- tests/helics/application_api/CMakeLists.txt
- tests/helics/application_api/ErrorTests.cpp
this is the first of the error check tests,  dealing with duplicate names.  Turns out there was some bugs in how that got handled previously, which explains the issues Shri was having.  This should deal with that issue for federates at least, and log a message that is somewhat indicative of the problem.  Not totally happy with the error propagation yet but I don't want to do deal with that now.
> add Error tests and deal with duplicate names properly Issue #224

- examples/CInterface/CMakeLists.txt
- examples/CInterface/comboFederates1/CMakeLists.txt
- examples/CInterface/comboFederates1/comboFed.c
- examples/CInterface/comboFederates1/openmpi-run.conf
- examples/CInterface/comboFederates1/run.sh
- examples/CInterface/comboFederates1/run3.sh
- examples/CInterface/comboFederates1/srun-mpi.conf
- examples/CInterface/messageFed1/CMakeLists.txt
- examples/CInterface/messageFed1/messageFed.c
- examples/CInterface/messageFed1/openmpi-run.conf
- examples/CInterface/messageFed1/run.sh
- examples/CInterface/messageFed1/run3.sh
- examples/CInterface/messageFed1/srun-mpi.conf
Adding c examples for message federates and combination federates. The goal is to have them be able to interact with the C++ equivalent.  I haven't run full tests yet.
> New examples

- src/helics/core/tcp/TcpComms.cpp
- src/helics/core/tcp/TcpHelperClasses.cpp
> Change all boost error_code comparison with nullptr

- src/helics/common/CMakeLists.txt
- src/helics/core/CMakeLists.txt
> add definitions to not use experimental/any on mac platform

- CMakeLists.txt
- appveyor.yml
- src/helics/application_api/Endpoints.cpp
- src/helics/application_api/Federate.cpp
- src/helics/common/AsioServiceManager.h
- src/helics/core/BrokerBase.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommsBroker.hpp
- src/helics/core/CommsBroker_impl.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/ipc/IpcBroker.cpp
- src/helics/core/ipc/IpcBroker.h
- src/helics/core/ipc/IpcCore.cpp
- src/helics/core/ipc/IpcCore.h
- src/helics/core/tcp/TcpBroker.cpp
- src/helics/core/tcp/TcpBroker.h
- src/helics/core/tcp/TcpCore.cpp
- src/helics/core/tcp/TcpCore.h
- src/helics/core/tcp/TcpHelperClasses.cpp
- src/helics/core/tcp/TcpHelperClasses.h
- src/helics/core/udp/UdpBroker.cpp
- src/helics/core/udp/UdpBroker.h
- src/helics/core/udp/UdpCore.cpp
- src/helics/core/udp/UdpCore.h
- src/helics/core/zmq/ZmqBroker.cpp
- src/helics/core/zmq/ZmqBroker.h
- src/helics/core/zmq/ZmqCore.cpp
- src/helics/core/zmq/ZmqCore.h
- tests/helics/core/ZeromqCore-tests.cpp
Some race condition fixes for the core components and some tweaks to a couple tests to make them less likely to fail spuriously.
> Thread safety improvements2

- tests/helics/application_api/FilterTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/MessageFederateKeyTests.cpp
- tests/helics/application_api/QueryTests.cpp
- tests/helics/application_api/TimingTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateExtendedTests.cpp
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/application_api/heat-transfer-tests.cpp
- tests/helics/application_api/iterationTests.cpp
- tests/helics/application_api/subPubObjectTests.cpp
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
- tests/helics/shared_library/test-message-federate_cpp.cpp
> #issue #333

- CMakeLists.txt
- ThirdParty/fmt/support/cmake/cxx14.cmake
- src/helics/apps/Player.cpp
- src/helics/apps/Player.hpp
- src/helics/apps/PrecHelper.cpp
- src/helics/apps/PrecHelper.hpp
- src/helics/apps/Recorder.cpp
- src/helics/common/base64.cpp
- src/helics/common/base64.h
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/cpp98/Broker.hpp
- src/helics/cpp98/Core.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/cpp98/MessageFederate.hpp
- src/helics/cpp98/ValueFederate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/application_api/MessageFederateKeyTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/application_api/federateRealTimeTests.cpp
- tests/helics/apps/CMakeLists.txt
- tests/helics/apps/combo_tests.cpp
- tests/helics/apps/helics_apps_tests.cpp
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/shared_library/cpptestFixtures.cpp
This fixes a number of the little issues that were targetted at the 1.2 release
> Issue fixes

- CHANGELOG.md
- CMakeLists.txt
- CONTRIBUTING.md
- CONTRIBUTORS.md
- README.md
- ROADMAP.md
- appveyor.yml
- code-of-conduct.md
- docs/apps/Player.md
- docs/configuration/CoreTypes.md
- docs/configuration/Federate.md
- docs/configuration/FederateInfo.md
- docs/configuration/Filters.md
- docs/configuration/Timing.md
- docs/configuration/index.md
- src/helics/shared_api_library/MessageFiltersExport.cpp
- src/helics/shared_api_library/helics.h
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
there will be one more after this to update the API files after everything is merged, to make sure the included code is correct for Python, Java, and Matlab api's
this includes some documentation updates, the code-of-conduct and C api fixes from Andy
> update the documentation, and version info

- examples/python/timing-demo/timing-federate1.py
- examples/python/timing-demo/timing-federate2.py
- src/helics/shared_api_library/ValueFederateExport.cpp
- tests/python_helics/test_helics.py
- tests/python_helics/test_message_federate.py
- tests/python_helics/test_message_filter.py
- tests/python_helics/test_value_federate.py
> Fix codacy python tests

- config/cmake/addMPI.cmake
Changes to addMPI.cmake from LLNL/GridDyn
> Improve exported MPI::MPI_C target handling of multiple MPI libraries

- src/helics/application_api/Subscriptions.cpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/core/FederateState.cpp
- swig/python/helics.py
- swig/python/helics_wrap.c
- tests/helics/application_api/PrimaryTypeConversionTests.cpp
- tests/helics/shared_library/ctestFixtures.hpp
- tests/helics/shared_library/test-value-federate1.cpp
- tests/python_helics/test_value_federate.py
- Adds named_point and bool tests
Fixes #305
> Update python tests

- CMakeLists.txt
- swig/matlab/helicsStartup.m
- tests/matlab_helics/CMakeLists.txt
- tests/matlab_helics/messageFedTests.m
- tests/matlab_helics/messageFilterTests.m
- tests/matlab_helics/runTestsUNIX.m.in
- tests/matlab_helics/runTestsWIN32.m.in
- tests/python_helics/test_message_federate.py
- tests/python_helics/test_message_filter.py
add more matlab tests, and a few tweaks to the python tests
> Additional matlab tests

- docs/conf.py
- src/helics/core/InterfaceInfo.cpp
- src/helics/core/InterfaceInfo.hpp
- src/helics/core/JsonMapBuilder.cpp
- src/helics/core/JsonMapBuilder.hpp
- src/helics/core/MessageTimer.hpp
- src/helics/core/fmt_wrapper.h
- src/helics/core/queryHelpers.hpp
- Update conf.py with correct relative path
- Update copyright symbols
> Fix c api reference files for documentation

- docs/installation/docker.md
- docs/installation/index.md
- docs/installation/linux.md
I teased some of these out while trying to get the code to compile.
> Some suggested documentation updates based on my install experience.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-of-design-question.md
Split out the issue templates into 3 templates that can used instead of the single issue template.
> Update issue templates

- README.md
Updates GridLab-D branch information in the README.
> Update GridLab-D info in the README

- scripts/install-ci-dependencies.sh
> Fix missing pytest

- interfaces/python/python_maps.i
- src/helics/shared_api_library/helics.h
- tests/python_helics/CMakeLists.txt
- tests/python_helics/test_message_federate.py
- tests/python_helics/test_message_filter.py
- tests/python_helics/test_value_federate.py
Adds support for Python3 swig interface for HELICS 2.0
> Python swig interface updates

- scripts/run-ci-tests.sh
> add flag to tsan options for printing second stack trace

- interfaces/python/CMakeLists.txt
- interfaces/python/helics.py
- interfaces/python/helics_wrap.c
Builds the Python interface without swig as a CMake library to avoid errors on systems that have read-only pip installations.
> Python interface cmake build

- interfaces/python2/python_maps2.i
> Add python_maps2.i

- .travis.yml
- tests/helics/core/CMakeLists.txt
Change the tsan daily build test to only run a single test
> change tsan options to only run one test

- src/helics/core/TimeCoordinator.cpp
- tests/helics/system_tests/TimingTests.cpp
> fix the operation of the uninterruptible flag and add test checking it.

- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/Inputs.hpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederate.hpp
- src/helics/apps/MultiBroker.cpp
- src/helics/apps/Player.cpp
- src/helics/apps/helicsApp.cpp
- src/helics/apps/helicsApp.hpp
- src/helics/apps/playerMain.cpp
- src/helics/core/core-types.cpp
- src/helics/shared_api_library/ValueFederate.h
- src/helics/shared_api_library/ValueFederateExport.cpp
- tests/helics/apps/combo_tests.cpp
- tests/helics/apps/test_files/federate_config.json
- tests/helics/apps/test_files/test_HELICS_player.json
- tests/helics/apps/test_files/test_HELICS_recorder.json
Address issue #538 and some errors in player/recorders
add a test case to check the player errors.
> App name fix

- src/helics/core/mpi/MpiComms.cpp
- src/helics/core/mpi/MpiService.cpp
a few tweaks to the mpi core to improve the thread balance and some formatting changes
> a few tweaks with the mpi core to improve thread balance

- CMakeLists.txt
beta.2 tag updates with date and build
> update version number and date for beta.2

- ThirdParty/cereal/archives/json.hpp
- ThirdParty/cereal/archives/xml.hpp
- ThirdParty/cereal/cereal.hpp
- ThirdParty/cereal/details/polymorphic_impl.hpp
- ThirdParty/cereal/details/static_object.hpp
- ThirdParty/cereal/details/traits.hpp
- ThirdParty/cereal/types/polymorphic.hpp
- ThirdParty/cereal/types/variant.hpp
Update the cereal library with upstream changes
> pull upstream changes for cereal

- ThirdParty/helics_includes/variant.hpp
Update variant.hpp with latest upstream changes
> update variant.hpp with upstream changes

- src/helics/application_api/Endpoints.hpp
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/application_api/Filters.cpp
- src/helics/application_api/Filters.hpp
- src/helics/application_api/Inputs.cpp
- src/helics/application_api/Inputs.hpp
- src/helics/application_api/MessageFederate.cpp
- src/helics/application_api/MessageFederate.hpp
- src/helics/application_api/MessageFederateManager.cpp
- src/helics/application_api/MessageFederateManager.hpp
- src/helics/application_api/Publications.hpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederate.hpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/apps/Recorder.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/Core.hpp
- src/helics/core/NamedInputInfo.cpp
- src/helics/shared_api_library/ValueFederateExport.cpp
- tests/helics/application_api/CombinationFederateTests.cpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/core/TestCore-tests.cpp
- tests/helics/system_tests/ErrorTests.cpp
This addresses issue #551  
- change the getInputType and getOutputType function to getInjectionType and getExtractionType(),  
- make all the interfaces consistent in the use of getName/ getKey functions, 
- add getInterfaceUnits function and remove separate calls for each interface type.
> Type function name update

- config/cmake/FindZeroMQ.cmake
- config/cmake/buildlibZMQ.cmake
- tests/helics/application_api/ValueFederateKeyTests.cpp
and fix a test case that failed on my computer but not on travis
Update autobuild zmq version to 4.3.0
> update autobuild zmq version to v4.3.0

- ThirdParty/fmt/CMakeLists.txt
- ThirdParty/fmt/ChangeLog.rst
- ThirdParty/fmt/README.rst
- ThirdParty/fmt/include/fmt/chrono.h
- ThirdParty/fmt/include/fmt/color.h
- ThirdParty/fmt/include/fmt/core.h
- ThirdParty/fmt/include/fmt/format-inl.h
- ThirdParty/fmt/include/fmt/format.h
- ThirdParty/fmt/include/fmt/printf.h
- ThirdParty/fmt/include/fmt/time.h
- ThirdParty/fmt/src/format.cc
Update the fmt library with the latest upstream changes
> update fmt library with latest release

- src/helics/application_api/ValueFederate.hpp
- src/helics/apps/helics-broker.cpp
- src/helics/core/BrokerFactory.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/InterfaceInfo.cpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- tests/helics/apps/SourceTests.cpp
- tests/helics/common/DualMappedPointerVectorTests.cpp
fix some issues shown by klokwork a static analysis tool.  Mostly potential uses of NULL return and a few other odds and ends.
> make some fixes recommended by Klokwork

- src/helics/application_api/FederateInfo.cpp
- src/helics/apps/BrokerApp.cpp
- src/helics/apps/appMain.cpp
- src/helics/apps/helics-broker.cpp
- src/helics/core/NetworkBrokerData.cpp
- tests/helics/apps/PlayerTests.cpp
- tests/helics/apps/RecorderTests.cpp
- tests/helics/apps/TracerTests.cpp
- tests/helics/core/MessageTimerTests.cpp
Address most of issue #560.
remove a few duplicated options
move to --coretype, or -t as the preferred way to specify which core type to use on the command line
tweak a few other options
> Tweak a few of the command line options

- CMakeLists.txt
Update the version number of beta.3 release
> Update the version build number

- ThirdParty/helics_includes/variant.hpp
Updates the mpark/variant.hpp with upstream fixes for MSVC 2017 and 2019 preview compiler bugs.
> Update mpark/variant.hpp with upstream MSVC fixes

- src/helics/core/ipc/IpcComms.cpp
- src/helics/core/ipc/IpcQueueHelper.cpp
- src/helics/core/tcp/TcpComms.cpp
- src/helics/core/udp/UdpComms.cpp
review the timeout usage in the TCP, UDP, and IPC cores as per Issue #580 
- add some retries to the UDP and IPC cores
> Timeout checks

- src/helics/application_api/FederateInfo.hpp
- src/helics/apps/helics-broker.cpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/helicsExport.cpp
- src/helics/shared_api_library/internal/api_objects.h
- tests/helics/shared_library/badInputTests.cpp
Fixes segfaults on a Mac in Python when incorrectly free-ing objects.
> Fix mac broker segfaults

- CHANGELOG.md
- CMakeLists.txt
- README.md
- docs/ROADMAP.md
- src/helics/application_api/FederateInfo.cpp
and a few other docs and update the version string to 2.0.0.rc1
last revisions before 2.0.0 rc unless someone comes up with a bug that can be fixed quickly
> Update to README 

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Some commits from master cherry-picked for develop.
> Cherry-picked changes from master

- docs/installation/index.md
Updates documentation with some information about installation instructions.
> Update installation documentation instructions

- docs/installation/index.md
Update documentation with `conda install -c gmlc-tdc helics` for installation.
> Add conda channel gmlc-tdc installation

- docs/Makefile
- docs/conf.py
- docs/index.md
- docs/installation/language.md
- docs/installation/mac.md
- docs/requirements.txt
- scripts/render-doxyfile.py
Makes docs readthedocs compatible and fix some installation documentation.
> Make read the docs compatible

- .github/PULL_REQUEST_TEMPLATE.md
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- docs/index.md
…pull request to remove the check boxes as they are redundant with the github terms of usage and somewhat annoying.
If merged this pull request will update the links in the readme and documentation and remove the check boxes from the PR template 
- Readme Updates
- Fix some links in readme and documentation
- Update the PR template
> Fix some document links and a few updates to the readme. 

- docs/404.md
- docs/Makefile
- docs/configuration/FederateInfo.md
- docs/index.md
- docs/user-guide/queries.md
- docs/user-guide/simulator_integration.md
- docs/user-guide/value_federates.md
If merged this pull request will redirect all documentation to helics.readthedocs.org
> Update documentation url links

- README.md
- docs/Public_API.md
- docs/ROADMAP.md
to point directly to readthedocs and a few tweaks to Public_API and Roadmap
If merged this pull request will update the links in the README to point to Readthedocs
> Update links in readme 

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- docs/404.md
- docs/Makefile
- docs/configuration/FederateInfo.md
- docs/index.md
- docs/installation/language.md
- docs/installation/linux.md
- docs/installation/mac.md
- docs/installation/windows.md
- docs/user-guide/index.md
- docs/user-guide/queries.md
- docs/user-guide/simulator_integration.md
- docs/user-guide/value_federates.md
- interfaces/matlab/README.md
- interfaces/python/README.md
> Update mac.md for gcc instructions

- interfaces/python/CMakeLists.txt
> Fix Python swig-less build

- .github/PULL_REQUEST_TEMPLATE.md
- CMakeLists.txt
- LICENSE
- README.md
If merged this pull request will update the readme with some additional badges and update the release date.
> Tweak the readme with some more badges, and update the date on Version

- LICENSE
so github detect the license.
If merged this pull request will change some line breaks in the license file so Github detects it properly
close #649
> remove some line breaks in the license file 

- docs/conf.py
- docs/index.md
- docs/requirements.txt
Fixes #656 
This also pins the readthedocs build as well, so it should prevent future issues. We'll have to update dependencies every now and then.
> Fix readthedocs build

- docs/user-guide/queries.md
- docs/user-guide/simulator_integration.md
- docs/user-guide/value_federates.md
Updates links to installation guide on readthedocs for User Guide
Updated links
> HELICS installation link update

- docs/conf.py
- docs/index.md
- docs/requirements.txt
- docs/user-guide/queries.md
- docs/user-guide/simulator_integration.md
- docs/user-guide/value_federates.md
PR to merge some doc updates on Master into develop
> Doc updates from Master to Develop

- docs/developer-guide/swig.md
- docs/installation/index.md
- docs/introduction/Endpoints.md
- docs/introduction/Inputs.md
- docs/introduction/LanguageAPIs.md
- docs/introduction/Publications.md
- docs/introduction/filters.md
- docs/introduction/hello-world.md
- docs/introduction/matlab.md
- docs/introduction/pubsub-vs-message.md
- docs/introduction/python.md
- docs/introduction/terminology.md
A few more documentation fixes from master to develop.
> Tutorial fixes master to develop

- CMakeLists.txt
- config/HELICSConfig.cmake.in
which defaults false everywhere but visual studio
-
> Add and option switch for installing cereal 

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTORS.md
- ThirdParty/helics/external/filesystem.hpp
- ThirdParty/helics/external/variant.hpp
- docs/ROADMAP.md
If merged this pull request will update some of the included libraries and submodules and some of markdown file to reflect recent changes.  
- update variant and filesystem headers
- update fmtlib and google test submodules
-update markdown files with recent changes (roadmap, contributors, changelog)
> Library updates

- .travis.yml
- scripts/trigger-dependent-ci-builds.sh
If merged this pull request will trigger Azure CI builds of the https://github.com/GMLC-TDC/HELICS-Examples repository for PRs and commits to the master or develop branches of this repository.
- Trigger Azure CI builds in the HELICS-Examples repository for PRs/commits to the master or develop branches of this repository
> Add triggering CI builds in the HELICS-Examples repository

- scripts/trigger-dependent-ci-builds.sh
If merged this pull request will pass variables needed for testing a HELICS PR to the helics-ns3 repo builds.
- Pass variables needed for testing a PR merge to the helics-ns3 Azure builds
- Trigger helics-ns3 builds for commit/PR to master
> Trigger helics-ns3 repo builds with PR variables

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update the included copy of ghc::filesystem to include a fix that better supports different compiler implementations of systemerror_r (GNU returns a char*, other compilers return int; preprocessor conditional directive didn't choose correctly for all compilers).
- Update ghc::filesystem to the latest version
> Update ghc::filesystem to include systemerror_r fix

- ThirdParty/helics/external/filesystem.hpp
- ThirdParty/helics/external/variant.hpp
- src/helics/core/tcp/TcpHelperClasses.cpp
If merged this pull request will update the included files for filesystem and variant, and update the submodule version for fmtlib and gtest.
> Bump filesystem version

- CHANGELOG.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
- README.md
If merged this pull request will fix some codacy issues with the markdown files
- codacy recommended changes
> fix some codacy issues in the markdown formatting

- tests/helics/CMakeLists.txt
- tests/helics/application_api/testFixtures.cpp
- tests/helics/common/common-tests.cpp
- tests/helics/system_tests/CMakeLists.txt
- tests/helics/system_tests/ErrorTests.cpp
- tests/helics/system_tests/QueryTests.cpp
- tests/helics/system_tests/TimingTests.cpp
- tests/helics/system_tests/TimingTests2.cpp
- tests/helics/system_tests/federateRealTimeTests.cpp
- tests/helics/system_tests/flagTests.cpp
- tests/helics/system_tests/heat-transfer-tests.cpp
- tests/helics/system_tests/helics_system_tests.cpp
- tests/helics/system_tests/iterationTests.cpp
- tests/helics/system_tests/networkTests.cpp
- tests/helics/system_tests/updateTests.cpp
If merged this pull request will convert the system_tests to use google_test and enable a few more of them in the CI runs
- system tests to google tests
> System tests to google tests

- .ci/undef_blacklist.txt
- scripts/.travis-tsan.yml
- scripts/ubsan-cache.cmake
- src/helics/common/JsonProcessingFunctions.cpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommsInterface.cpp
- src/helics/core/CommsInterface.hpp
- src/helics/core/tcp/TcpComms.cpp
- src/helics/core/tcp/TcpComms.h
- src/helics/core/tcp/TcpCommsCommon.cpp
- src/helics/core/tcp/TcpCommsCommon.h
- src/helics/core/tcp/TcpCommsSS.cpp
- src/helics/core/tcp/TcpCommsSS.h
- src/helics/core/zmq/ZmqCommsSS.cpp
- src/helics/core/zmq/ZmqCommsSS.h
- tests/helics/core/CMakeLists.txt
- tests/helics/core/ZeromqSSCore-tests.cpp
- tests/helics/shared_library/ctestFixtures.cpp
- tests/helics/shared_library/ctestFixtures.hpp
- tests/helics/system_tests/CMakeLists.txt
- tests/helics/system_tests/ErrorTests.cpp
If merged this pull request will fix a series of issues from undefined behavior sanitizer, thread sanitizer,  valgrind, and klockwork, and some occasionally failing test cases.  
- fix a vptr race with the ZMQSSComms
- fix a race condition with transfer of interfaceInfo to the CommonCore
- fix undefined behavior with the actionMessage Serialization
- change the threadSanitizer to run on the system tests
- make a blacklist of the zmq unaligned access since that is not part of HELICS
- fix memory leak in json writer usage
> Test issue fixes

- src/helics/apps/CMakeLists.txt
- src/helics/apps/appMain.cpp
- src/helics/apps/helics-broker.cpp
- tests/helics/apps/CMakeLists.txt
If merged this pull request will fix issue #736 
- helics_broker return 0 on `--version` and `--help`, `--help_all` flags
- helics_app return 0 on `--version` and `--help`, `--help_all` flags
recorder and player didn't have this issue
> Broker version return

- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/cppshared-library-tests.cpp
- tests/helics/shared_library/cpptestFixtures.cpp
- tests/helics/shared_library/cpptestFixtures.hpp
- tests/helics/shared_library/test-message-federate_cpp.cpp
- tests/helics/shared_library/test-value-federate2_cpp.cpp
If merged this pull request will convert the c++98 test to use google test
> convert the cpp98 test to use googletest

- src/helics/CMakeLists.txt
- src/helics/shared_api_library/CMakeLists.txt
If merged this pull request will set the SO version for the HELICS shared libraries.
- Set SO version for the HELICS shared libraries.
> Set SO version for HELICS shared libraries

- .codacy.yml
- docs/conf.py
- examples/comboFederates1/comboFed.cpp
- examples/user_guide_examples/Example_1a/Transmission/Transmission_simulator.py
- examples/user_guide_examples/Example_1b/EV_Controller/EV_Controller.py
- examples/user_guide_examples/Example_1b/Transmission/Transmission_simulator.py
- examples/user_guide_examples/Example_1c/EV_Controller/EV_Controller.py
- examples/user_guide_examples/Example_1c/Transmission/Transmission_simulator.py
- src/helics/apps/BrokerApp.cpp
- src/helics/apps/Player.hpp
- src/helics/apps/Tracer.cpp
- src/helics/apps/helics-broker.cpp
- src/helics/apps/helicsApp.cpp
- src/helics/common/logger.cpp
- src/helics/common/loggerCore.cpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/helicsCLI11.hpp
- src/helics/core/udp/UdpComms.cpp
- src/helics/core/zmq/ZmqComms.cpp
- src/helics/core/zmq/ZmqCommsSS.cpp
- src/helics/cpp98/Federate.hpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
- tests/java/ApplicationApiTest.java
If merged this pull request will clear out some of the codacy warnings
> do some cleanup of the codacy identified issues

- .travis.yml
If merged this pull request will use the old Travis Trusty images.
> Force Travis to use the old Trusty build image

- scripts/trigger-dependent-ci-builds.sh
If merged this pull request will trigger builds in the GMLC-TDC/helics-ns3 repository for PRs to master.
- Add check for TRAVIS_PULL_REQUEST_BRANCH to trigger builds for PRs to master
> Trigger ns-3 module builds on PRs to master

- CMakeLists.txt
- README.md
- docs/ROADMAP.md
If merged this pull request will fix some issue from @kdheepak from code review
-
> fix some issues from code review

- CHANGELOG.md
- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/helics.h
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/system_tests/ErrorTests.cpp
If merged this pull request will add a broker capability to HELICS.  This means if a key is specified at a broker,  cores must have that same key to connect and if a core tries to use a key and a broker doesn't have one it also errors.  
- add broker key capability
- clear a couple TODO's related core errors
- add an errorCode and errorstring storage in the broker base so it accessible later
> Broker key

- docs/user-guide/helics_co-sim_sequence.md
TIL that dissemble means "to conceal one's true motives, feelings, or beliefs"
Who knew!?
> Fix a few typos

- ThirdParty/helics/external/filesystem.hpp
- ThirdParty/netif/gmlc/netif/NetIF.hpp
If merged this pull request will update some thirdparty libs to the latest revision
- update filesystem to 1.2.4
- update googletest to latest master
- update fmtlib to latest master
> Lib update2

- .travis.yml
If merged this pull request will get use the standard script section on Travis for the MinGW build.
- Use the same script step in Travis for the MinGW build as for the other builds
- Remove the use of powershell for running MinGW build (not needed)
- Echo some of the build commands with variables expanded
> MinGW build without PowerShell

- .circleci/asan_blacklist.txt
- .circleci/config.yml
- .circleci/leak_suppression.txt
- config/Docker/Dockerfile-ASan
- config/Docker/Dockerfile-MSan
- config/Docker/Dockerfile-TSan
- examples/CppInterface/CMakeLists.txt
- src/helics/cpp98/CMakeLists.txt
If merged this pull request will update the circle_ci tests specifically to get the asan test passing
- update the build files slightly
- add a blacklist for the ASAN configuration
> try to get the circle-ci asan operational

- .circleci/asan_blacklist.txt
- .circleci/config.yml
- .circleci/leak_suppression.txt
- config/Docker/Dockerfile-ASan
- config/Docker/Dockerfile-MSan
- config/Docker/Dockerfile-TSan
- examples/CppInterface/CMakeLists.txt
- src/helics/cpp98/CMakeLists.txt
try to use separate builders for asan container
make blacklist path absolute
* add leak suppression file
* update the asan file
* update dockerFile
* fix included headers for cpp98 target
-
> try to get the circle-ci asan operational (#794)

- .ci/.drone.yml
- examples/comboFederates1/comboFed.cpp
- src/helics/application_api/MessageFederate.hpp
- src/helics/application_api/ValueConverter_impl.hpp
- src/helics/apps/BrokerServer.cpp
- src/helics/apps/Echo.hpp
- src/helics/apps/Recorder.hpp
- src/helics/apps/helics-broker.cpp
- src/helics/common/logger.h
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/HandleManager.cpp
- src/helics/core/federate_id.hpp
- src/helics/core/zmq/ZmqCommsCommon.h
- src/helics/core/zmq/ZmqCommsSS.h
- tests/helics/CMakeLists.txt
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/testFixtures.hpp
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/TimingTests.cpp
- tests/helics/shared_library/cpptestFixtures.hpp
- tests/helics/shared_library/ctestFixtures.cpp
- tests/helics/shared_library/ctestFixtures.hpp
- tests/helics/shared_library/test-message-federate.cpp
- tests/helics/shared_library/test-value-federate1.cpp
- tests/helics/shared_library/test-value-federate2.cpp
If merged this pull request will fix the 32 bit issue on drone and a several other static code analysis warnings from clang-tidy and others
- fix 32 bit issue with drone and other 32 bit compilation
- fix some warnings and possibly the undefined behavior warning we have been getting.
> Warnings and 32 bit

- CMakeLists.txt
- config/cmake/addlibzmq.cmake
If merged this pull request will fix the failed build on mingw (and MSYS)
- revert the zmq library for MINGW and MSYS to 4.3.1,  This seems to be a failure with libzmq, though still investigating.
> fix for the libzmq on mingw

- .travis.yml
If merged this pull request will remove the nightly TSAN build from Travis.
- Removes nightly Travis TSAN build
> Remove TSAN build from Travis

- .circleci/config.yml
- CMakeLists.txt
- appveyor.yml
- interfaces/matlab/overwriteMatlabFiles.cmake
- tests/helics/system_tests/TimingTests2.cpp
fix some warnings of unused variables, change appveyor version number  remove unnecessary install from circleci config
If merged this pull request will update the appveyor version number, fix a few warnings, and remove the install step from the circleci builds
> a few final tweaks for 2.2.1

- CHANGELOG.md
- README.md
- docs/installation/windows.md
If merged this pull request will update the date in the changelog for the 2.2.1 release.
> Update changelog release date for 2.2.1 and list of Windows installers

- .circleci/asan_blacklist.txt
- scripts/run-nighly-circleci-tests.sh
- tests/helics/CMakeLists.txt
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/shared_library/TimingTests.cpp
- tests/helics/shared_library/badInputTests.cpp
- tests/helics/shared_library/comboConfigTests.cpp
- tests/helics/shared_library/ctestFixtures.cpp
- tests/helics/shared_library/ctestFixtures.hpp
- tests/helics/shared_library/loggingTests.cpp
- tests/helics/shared_library/shared-library-tests.cpp
- tests/helics/shared_library/test-message-federate.cpp
- tests/helics/shared_library/test-value-federate1.cpp
- tests/helics/shared_library/test-value-federate2.cpp
If merged this pull request will convert the shared library test to use gtest and add the tests to circle ci.
> Shared lib test to gtest

- .gitmodules
- CHANGELOG.md
- CMakeLists.txt
- CONTRIBUTORS.md
- README.md
- benchmarks/CMakeLists.txt
- benchmarks/helics/ActionMessageBenchmarks.cpp
- benchmarks/helics/CMakeLists.txt
- config/cmake/AddGooglebenchmark.cmake
- config/cmake/AddGoogletest.cmake
If merged this pull request will add google benchmarks as a package and 1 benchmark test
and move google test to be a git clone instead of a submodule.  
- add google benchmark as git clone or fetch content
- change google test to use fetch Content or git clone
- add a benchmark about conversion of the ActionMessage
> Add benchmark tests

- interfaces/octave/octave_maps.i
- interfaces/python/python_maps.i
- interfaces/python2/python_maps2.i
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/ValueFederate.h
If merged this pull request will fix the naming in the C shared library to match what is in the map.i files and fix a broken path in the octave maps
- make the doxygen comments match in  the changed c shared api files
- make the function declaration match the actual implementation file and what is in the *_map.i files for swig
- fix a broken conversion code for octave
> fix some updates and warnings on the header interface files

- .travis.yml
- benchmarks/helics/ActionMessageBenchmarks.cpp
- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/conversionBenchmarks.cpp
- benchmarks/helics/echoBenchmarks.cpp
- benchmarks/helics/messageLookupBenchmarks.cpp
- benchmarks/helics/ringBenchmarks.cpp
- scripts/setup-helics-ci-options.sh
- src/helics/application_api/ValueConverter_impl.hpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreFactory.hpp
- src/helics/core/TimeoutMonitor.cpp
If merged this pull request will add additional benchmark code
- update the echo benchmark and ring benchmark to use one thread in the main benchmark loop
- add conversion benchmarks for converting different types
- add messageLookup benchmark for message broadcasts
- add different ring size benchmarks and simplify the test code
- move the ping for keep-alive to a priority channel
> Add additional benchmarks

- CMakeLists.txt
- ThirdParty/netif/gmlc/netif/NetIF.hpp
Fixes naming issues that allow cross compilation. See [HELICSBuilder](https://github.com/GMLC-TDC/HELICSBuilder).
> Fix cross compilation issues

- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/echoMessageBenchmarks.cpp
- src/helics/application_api/Endpoints.hpp
If merged this pull request will add an echoMessage Benchmark
- add echo message Benchmark
- add overload of send in Endpoint Object that uses unique_ptr<Message>
> add echo Message Benchmark tests

- .travis.yml
If merged this pull request will remove the UBSAN build from nightly Travis runs.
- Remove the nightly UBSAN build from the Travis build matrix
> Remove ubsan build from Travis daily builds

- .circleci/config.yml
- .travis.yml
If merged this pull request will fix the mingw build and revert the TSAN build to previous docker file
- add force zmq subproject to mingw build
-  revert the tsan test on circle ci to previous docker image
> fix the Mingw build and revert the tsan test to previous version of TSAN

- interfaces/python/helics.py
- interfaces/python/helicsPython.i
- interfaces/python2/helicsPython2.i
If merged this pull request will register a `atexit` call to `helicsCloseLibrary`.
Fixes #858
> Register `helicsCloseLibrary` as an `atexit` for python code generated from SWIG

- .gitmodules
This fixes issue #874 
If merged this pull request will fix the forked problem on non-GitHub repositories.
- Update the .gitmodule code to explicitly designate GitHub as the repository of choice for the GoogleTest codebase.
> Update repository for use in forked repositories that are not in Github

- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/EchoMessage.hpp
- benchmarks/helics/echoMessageBenchmarks.cpp
- benchmarks/helics/filterBenchmarks.cpp
If merged this pull request will add a set of Filter benchmarks based on echoMessageBenchmark.  It adds benchmarks with source and destination filters, and some code refactoring to split out EchoMessage class into separate file as it is used by both EchoMessageBenchmarks and filterBenchmarks.  
- add FilterBenchmarks
- split EchoMessage class into separate file for use by two Benchmarks
> Filter benchmark

- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/PholdFederate.hpp
- benchmarks/helics/pholdBenchmarks.cpp
If merged this pull request will add a PHOLD benchmark to the set of google benchmarks.
- Add PHOLD benchmark
> PHOLD gbenchmark

- CHANGELOG.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
- docs/Public_API.md
- docs/ROADMAP.md
@bpalmintier   feel free to update this branch with your changes to the readme.  
Otherwise these are the notes and doc updates that go with the 2.3 release.
> Update changelog, release notes, and other assorted docs in preparation for release

- src/helics/core/coreTypeOperations.cpp
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/shared_library/badInputTests.cpp
If merged this pull request will fix a potential leaked exception if a known core type was unavailable and used in the helicsCreateCore function.
Fixes issue #918
- add try/catch block around helicsCoreCreate section which could throw the exception.  
- add a test method to execute it.
- add "nng"  string to getCoreType so we can generate a known unavailable core type for use in the test.
> Helics create core leaked exception

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update the filesystem with some warning fixes to an official version instead of a test branch.  
- update `<filesystem>` library
> update the filesystem to latest release version

- .github/actions/create-file-update-pr/entrypoint.sh
- .github/workflows/clang-format.yml
> [TEST] Formatting action for PRs

- benchmarks/helics/messageSendBenchmarks.cpp
- src/helics/application_api/BrokerApp.hpp
- src/helics/application_api/CoreApp.hpp
- src/helics/application_api/Publications.hpp
- src/helics/apps/Source.cpp
- src/helics/apps/Source.hpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/BasicHandleInfo.hpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/ForwardingTimeCoordinator.hpp
- src/helics/core/TimeDependencies.hpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- tests/helics/shared_library/test-message-federate.cpp
If merged this pull request will fix some static analyzer issues from klokwork, clang-tidy, cpplint, and some additional warning fixes from additional warnings in clang and gcc.
> Static analyzer fixes

- interfaces/matlab/matlab_maps.i
> Fix MATLAB swig interface

- benchmarks/helics/ActionMessageBenchmarks.cpp
- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/conversionBenchmarks.cpp
- benchmarks/helics/echoBenchmarks.cpp
- benchmarks/helics/echoMessageBenchmarks.cpp
- benchmarks/helics/filterBenchmarks.cpp
- benchmarks/helics/messageLookupBenchmarks.cpp
- benchmarks/helics/messageSendBenchmarks.cpp
- benchmarks/helics/pholdBenchmarks.cpp
- benchmarks/helics/ringBenchmarks.cpp
- benchmarks/helics/timingBenchmarks.cpp
- docs/developer-guide/benchmarks.md
- docs/developer-guide/index.md
If merged this pull request will add a timing benchmark which is the echoBenchmark with the actual data transmission removed.  
- add timing benchmark
- add doc file describing the benchmarks
- rename the benchmarks to remove '_' from the first part of the name.
> Timing benchmarks

- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/echoBenchmarks_c.cpp
- benchmarks/helics/helics_benchmark_main.h
add a benchmark that runs the echoBenchmark test using the c based shared library
If merged this pull request will add a c shared library benchmark that duplicates the echoBenchmark except using the c shared library
- add echoBenchmarks_c 
- reformat benchmarks CMakeLists.txt
- some tweaks to the common header file to account for using the c shared library
> add c shared lib benchmark

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will  update the filesystem header to the latest version
> Update the filesystem header in use to the latest revision

- ThirdParty/helics/external/filesystem.hpp
- benchmarks/helics/CMakeLists.txt
- interfaces/python/CMakeLists.txt
- src/helics/cpp98/ValueFederate.hpp
> Python install helics shared lib

- ThirdParty/helics/external/variant.hpp
If merged this pull request will update variant to latest master, this includes one warning fix we noted in the variant repo.
> update the variant object in use to latest version

- scripts/_git-all-archive.sh
If merged this pull request will remove some unneeded folders from 3rd party submodules. The overall size drops from 17.9MB to 15.7MB (compressed). Addresses #1018.
- Remove unneeded files from the all source release tarball
> Slimmer all source release tarball

- benchmarks/helics/ringMessageBenchmarks.cpp
- docs/user-guide/queries.md
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/HandleManager.cpp
- src/helics/core/HandleManager.hpp
- tests/helics/apps/CloneTests.cpp
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/SystemTests.cpp
If merged this pull request will fix some potential issues with queries to cores that are not responded to when the core is disconnected or are established after the disconnect.  
- update the concurrency library with an additional function for the delayed objects
- detect making a query after the core is disconnected
- close out active queries on disconnect  
- make some tweaks to the sporadic failing test cases to try to resolve the sporadic issues.
> Try test fixes

- config/Docker/Dockerfile-HELICS-apps
- docs/CMakeLists.txt
- docs/developer-guide/continuous-integration.md
- docs/installation/helics_cmake_options.md
- docs/user-guide/index.md
- docs/user-guide/running_interaction.md
- docs/user-guide/simultaneous_cosimulations.md
- src/helics/apps/BrokerServer.cpp
- src/helics/apps/helicsWebServer.cpp
If merged this pull request will add docs for the webserver and broker server, and update the docker image to build the webserver
- add docs for the webserver
- update docs for the broker server
- fix a few bugs in the webserver
- change the docker image to use tumbleweed and build the webserver as part of the broker server
> Update webserver docs and docker

- config/packaging/mingw-w64-helics/PKGBUILD
- docs/docker.md
If merged this pull request will update the mingw package version and docker doc page versions to 2.4.0.
> Update mingw package and docker doc page versions to 2.4.0

- CHANGELOG.md
- src/helics/application_api/Federate.cpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederate.hpp
- src/helics/common/CMakeLists.txt
- src/helics/common/addTargets.hpp
- src/helics/common/configFileHelpers.cpp
- src/helics/common/configFileHelpers.hpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/test_files/example_value_fed_bad.toml
- tests/helics/test_files/example_value_fed_testb.json
- tests/helics/test_files/example_value_fed_testb.toml
- tests/helics/test_files/unusual_filters2.toml
If merged this pull request will add test for valueFederate.cpp to increase coverage to 100%, and fix a few issues that came up.
> Value federate coverage

- CHANGELOG.md
- config/Docker/Dockerfile-HELICS-builder
If merged this pull request will add a docker image for a helics builder, which will be a building block for making other docker images with specific helics-enabled apps.  
- update change log
- add helics-builder dockerfile.
> Helics builder

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update to the latest version of ghc::filesystem, which includes support for building on FreeBSD.
- Update ghc::filesystem 3rd party header
> Update ghc filesystem

- CMakeLists.txt
- appveyor.yml
- benchmarks/helics/PholdFederate.hpp
- docs/ROADMAP.md
- docs/installation/helics_cmake_options.md
- src/helics/apps/Clone.hpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.hpp
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/SystemTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
If merged this pull request will fix a few warnings from klokwork and from other compilations
- add a HELICS_DISABLE_GIT_OPERATIONS CMake hidden flag to just completely disable any of the git operations,  this is useful for some package builds to get the correct version number and some prevent some warnings from the submodules.  
-  fix a few warnings that have come up
- do a little tinkering on the core global test to see if we can resolve that sporadic failure.
> Warning fixes

- CHANGELOG.md
- src/docs/c_api_reference.dox
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/helics.h
- tests/helics/application_api/FederateTests.cpp
- tests/helics/shared_library/SystemTests.cpp
- tests/helics/shared_library/evilInputTests.cpp
If merged this pull request will expose an addDependency function for the C++ and C shared library API, that can create a dependency between two federates that would not normally be connected.  
- expose `addDependency` function
- create tests for the function
- update changelog
> Add dependency

- CHANGELOG.md
- docs/man/manpage_out/helics_app-broker.1
- docs/man/manpage_out/helics_app-clone.1
- docs/man/manpage_out/helics_app-echo.1
- docs/man/manpage_out/helics_app-player.1
- docs/man/manpage_out/helics_app-recorder.1
- docs/man/manpage_out/helics_app-source.1
- docs/man/manpage_out/helics_app-tracer.1
- docs/man/manpage_out/helics_app.1
- docs/man/manpage_out/helics_broker-term.1
- docs/man/manpage_out/helics_broker.1
- docs/man/manpage_out/helics_player.1
If merged this pull request will update the generated manpages for the HELICS apps
- Update generated HELICS apps manpages with the new options
> Update generated HELICS apps manpages

- CMakeLists.txt
- README.md
- docs/ROADMAP.md
If merged this pull request will update the date roadmap, and add a new section to the readme.
> Final Version and doc update to roadmap and readme and date.

- CHANGELOG.md
- docs/user-guide/queries.md
- src/helics/application_api/Federate.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/ForwardingTimeCoordinator.cpp
- src/helics/core/ForwardingTimeCoordinator.hpp
- src/helics/core/TimeCoordinator.cpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will add 3 new queries to brokers and cores
- add `current_state` query to get the current known status of different components
- add `current_time` query to get the current time of different objects
- add `global_time` query to run through the federation and get the current time of all components.  
- add `time` to local federates just to get the time as a string.  
- add tests for the new queries and update the docs
> New queries

- CHANGELOG.md
- src/helics/application_api/MessageOperators.cpp
- src/helics/application_api/MessageOperators.hpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/MessageFiltersExport.cpp
- src/helics/shared_api_library/helicsCallbacks.h
- src/helics/shared_api_library/internal/api_objects.h
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/evilInputTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
If merged this pull request will add a custom callback for filters to the C shared library
- add callback function
- add a messageCopy function
- add some tests for new functions
> Custom filter callback

- src/helics/core/CommonCore.cpp
- tests/helics/apps/BrokerAppTests.cpp
- tests/helics/apps/CMakeLists.txt
If merged this pull request will add a few tests for BrokerApp
- Add tests for BrokerApp 
- add a fix for sporadic coreInitTest failure
> Broker app tests

- src/helics/application_api/helicsTypes.cpp
- tests/helics/application_api/CMakeLists.txt
- tests/helics/application_api/PrimaryTypeConversionTests.cpp
- tests/helics/application_api/helicsTypeTests.cpp
- add some additional tests for type translation
- make a few fixes and get rid of some dead code paths.
> Additional type tests

- src/helics/common/JsonBuilder.cpp
- src/helics/common/JsonBuilder.hpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/InterfaceInfo.cpp
- src/helics/core/InterfaceInfo.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will actually finish the data_flow_graph query and do some cleanup work on the CoreBroker and CommonCore queries.  
- add data_flow_graph query and tests 
- allow cores to make queries that cascade into federates.  
- generalize the query capability to allow further expansion of cascading queries if necessary.
> Query cleanup

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update the filesystem library 1.3.2 and the units library to 0.4.0
> update the units library and filesystem library to latest releases

- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFilters.h
- src/helics/shared_api_library/ValueFederate.h
- src/helics/shared_api_library/api-data.h
- src/helics/shared_api_library/helics.h
- src/helics/shared_api_library/helicsCallbacks.h
I've updated the docstrings in all the header files.
And it compiles. I also ran `clang-format -i` on all the header files in the `shared_api_library` folder.
> Update c api docstrings

- .clang-tidy
- CPPLINT.cfg
- src/helics/application_api/BrokerApp.cpp
- src/helics/application_api/CoreApp.cpp
- src/helics/application_api/MessageFederateManager.cpp
- src/helics/application_api/MessageFederateManager.hpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/apps/helicsWebServer.hpp
- src/helics/core/BrokerFactory.cpp
- src/helics/core/BrokerFactory.hpp
- src/helics/helics_enums.h
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/network/ZeromqCore-tests.cpp
- tests/helics/network/ZeromqSSCore-tests.cpp
- tests/helics/webserver/webServerHttpTests.cpp
If merged this pull request will update some of the string issues in cpplint
- update cpplint issues with runtime/string  and clang-tidy issue with the associated files
> Readability string

- src/helics/network/CommsInterface.cpp
- src/helics/network/CommsInterface.hpp
- src/helics/network/loadCores.cpp
- tests/helics/network/IPCcore_tests.cpp
- tests/helics/network/TcpCore-tests.cpp
- tests/helics/network/TcpSSCore-tests.cpp
- tests/helics/network/UdpCore-tests.cpp
- tests/helics/network/ZeromqCore-tests.cpp
- tests/helics/network/ZeromqSSCore-tests.cpp
Add a commFactory to use in the MultiBroker, and eventually in some new core types, and add a few tests of the new factory
If merged this pull request will add a CommFactory for use with the MultiBroker and possibly other components.  
- CommFactory addition
- load the commFactory with the loadCore code 
- test the new factory in the network tests
> Comm Factory

- examples/user_guide_examples/Example_1a/Transmission/Transmission_simulator.py
- examples/user_guide_examples/Example_1b/Transmission/Transmission_simulator.py
- examples/user_guide_examples/Example_1c/Transmission/Transmission_simulator.py
- scripts/git-all-archive.py
If merged this pull request will cleanup some of the issues [lgtm found with Python scripts in the HELICS repo](https://lgtm.com/projects/g/GMLC-TDC/HELICS/?mode=list&lang=python).
- Fix a potential bug with identifying the right release to upload files to
- Clean-up git all archive script duplicate imports and unused variable definitions
- Catch the exceptions thrown by os.remove file instead of the generic BaseException
- Cleanup variable redefinition before use warnings before use in Transmission simulator examples (adding asserts to check every status == 0 is another option, though adding the error checks would make it more verbose than it is now)
> Fix assorted lgtm.com python issues

- CMakeLists.txt
- docs/installation/helics_cmake_options.md
- docs/installation/linux.md
If merged this pull request will add a specialized build configuration for Raspberry pi and some documentation about it.
> build configurations

- src/helics/apps/BrokerServer.cpp
- src/helics/apps/BrokerServer.hpp
- src/helics/core/MessageTimer.hpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/ValueFederate.h
- tests/helics/application_api/FederateInfoTests.cpp
- tests/helics/application_api/FederateTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/system_tests/ErrorTests.cpp
If merged this pull request will resolve some of the existing code warnings from different compilers.
> Fix some residual warnings from the different compilers.

- CHANGELOG.md
- CMakeLists.txt
- appveyor.yml
- docs/ROADMAP.md
- docs/Tools_using_HELICS.md
- docs/user-guide/index.md
- docs/user-guide/multibroker.md
- tests/helics/webserver/webServerHttpTests.cpp
If merged this pull request will update the multibroker docs and other documentation related to a 2.5.0 release.  
- documentation update
- update version numbers and dates
- update roadmap
> Release 2 5 update

- interfaces/matlab/CMakeLists.txt
- interfaces/matlab/matlabSwigGenerateOnly.cmake
If merged this pull request will add standalone build support for the Matlab interface
- Adds standalone build support for the Java interface
> Matlab interface build refactor

- src/docs/c_api_reference.dox
If merged this pull request will update the C api reference list in doxygen
> Update the C Api reference list

- src/helics/apps/helics-broker.cpp
- src/helics/core/helicsCLI11.hpp
- tests/helics/apps/MultiBrokerTests.cpp
If merged this pull request will fix a few issues for handling ENABLE_ZMQ_CORE=OFF in the multiBroker cases and fix an issue with config file not getting passed properly for using multibroker in the helics_broker app
- issues caught with the nightly build on circle-ci.
> NO ZMQ test fixes with MultiBroker tests

- src/helics/shared_api_library/MessageFiltersExport.cpp
- src/helics/shared_api_library/ValueFederateExport.cpp
If merged this pull request will update the register* calls internally to add a return value to the add operations and reduce the LOC and make things a little cleaner with fewer reinterpret casts
> clib refactor of addPublication, addInput, and addFilter to return pointer

- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- tests/helics/core/ActionMessage-tests.cpp
If merged this pull request will add some additional debug messages for showing different message types.  Issue #1174, fix the unknown message 
- add messages for some additional command types
- make some performance tweaks for the actionMessage toByteArray operations
> add some additional message interpreters for debugging.

- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/PholdFederate.hpp
- benchmarks/helics/helics_benchmark_util.h
- src/helics/core/helicsVersion.hpp
- src/helics/cpp98/helics.hpp
- src/helics/shared_api_library/helics.h
- src/helics/shared_api_library/helicsExport.cpp
If merged this pull request will add a buildFlags and compierVersion call to the C API and some constexpr values to the helicsVersion Header.
> add build flags call

- CHANGELOG.md
- benchmarks/.clang-tidy
- benchmarks/helics/BenchmarkFederate.hpp
- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/EchoMessageHubFederate.hpp
- benchmarks/helics/EchoMessageLeafFederate.hpp
- benchmarks/helics/MessageExchangeFederate.hpp
- benchmarks/helics/PholdFederate.hpp
- benchmarks/helics/echoBenchmarks.cpp
- benchmarks/helics/echoBenchmarks_c.cpp
- benchmarks/helics/echoMessageBenchmarks.cpp
- benchmarks/helics/filterBenchmarks.cpp
- benchmarks/helics/helics_benchmark_util.h
- benchmarks/helics/messageSendBenchmarks.cpp
- benchmarks/helics/pholdBenchmarks.cpp
- benchmarks/helics/ringBenchmarks.cpp
- benchmarks/helics/ringMessageBenchmarks.cpp
- benchmarks/helics/timingBenchmarks.cpp
- docs/installation/helics_cmake_options.md
- src/helics/core/helicsVersion.hpp
If merged this pull request will add a CMAKE variable to control the scaling of the benchmark tests.
> Benchmark scale

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- examples/README.md
If merged this pull request will address #1263 and update the readme to refer to more examples and organize the readme a little better.  
- update the PR template to remove a line so it fits better on common screen sizes
- add example links in the examples folder readme
- add doc download links to the main readme and shift the install section down on the page.
> update some of the readme with additional links and updates

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- examples/README.md
* update some of the readme with additional links and updates
* Apply suggestions from code review
Co-authored-by: Ryan Mast <nightlark@users.noreply.github.com>
Co-authored-by: Ryan Mast <nightlark@users.noreply.github.com>
If merged this pull request will merge recent master doc changes to develop
-
> update some of the readme with additional links and updates (#1266)

- docs/Tools_using_HELICS.md
- docs/index.md
If merged this pull request will update documentation to add HELICS supported tools to the sidebar
> Add tools using HELICS to sidebar

- .pre-commit-config.yaml
- config/Docker/Dockerfile-HELICS
- config/Docker/Dockerfile-HELICS-apps
- config/Docker/Dockerfile-HELICS-builder
- config/Docker/docker_rules.yml
If merged this pull request will add a dockerfile linter to pre-commit
> add a linter for dockerfiles

- .pre-commit-config.yaml
- CHANGELOG.md
- docs/user-guide/queries.md
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- tests/helics/core/ActionMessage-tests.cpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will address Issue #1283 and add a `version` and `version_all` query to the broker/core/federates.  
- add version query which gets the versionString for the HELICS library version
- add version_all query which returns a json object with the version string for all subbrokers/cores.  (all federates within the same core have the same helicsVersion).
- update query page and changelog
> Version query

- .circleci/config.yml
- .github/workflows/formatting.yml
- .github/workflows/static-analyzers.yml
- .github/workflows/swig-interface-gen.yml
- .travis.yml
- README.md
If merged this pull request will add the helics3 branch to the same checks as develop, basically making the helics3 branch a second development branch on which to begin the HELICS3 development effort
> Helics3 split

- examples/comboFederates1/CMakeLists.txt
- src/helics/core/BrokerFactory.cpp
Automatted pre-commmit CMake formatting for the helics_broker-comboFed-test branch. Manual PR, automated PR opening got a 500 internal server error.
> Automated formatting update from pre-commit

- examples/comboFederates1/CMakeLists.txt
- scripts/test_example.sh
- src/helics/apps/helics-broker.cpp
- src/helics/core/BrokerFactory.cpp
If merged this pull request will add a test of the standalone helics_broker using the comboFed example federate. Verifies that the helics_broker works using the default core type.
- Add a test of the comboFed example using the standalone helics_broker
> Add a test using helics_broker to run an example

- examples/CppInterface/.clang-tidy
- examples/CppInterface/nonlings_fed1.cpp
- examples/CppInterface/nonlings_fed2.cpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/MessageFiltersExport.cpp
- src/helics/shared_api_library/ValueFederateExport.cpp
- src/helics/shared_api_library/helicsExport.cpp
- src/helics/shared_api_library/internal/api_objects.h
If merged this pull request will refactor the shared_library to use an assignError function which simplifies the check and the code.  also fix a warning about variable name shadowing.
> Use assign error

- docs/c-api-reference/index.md
When merged this will fix the C API documentation.
This script was used to generate the C API markdown file:
https://gist.github.com/kdheepak/84f8da048140c3f632633fabfdec1f97
Resolves #1321
> Change C API markdown file

- docs/c-api-reference/index.md
If merged this pull request will update the docs strings in the C API reference.
Resolves #1321
> Add missing c api docstrings

- docs/c-api-reference/index.md
- src/helics/application_api/Inputs.cpp
- src/helics/application_api/Inputs.hpp
- src/helics/application_api/Publications.cpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederate.hpp
- src/helics/application_api/helicsPrimaryTypes.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/PublicationInfo.hpp
- tests/helics/application_api/data_viewTests.cpp
If merged this pull request will merge some clang-tidy fixes done in the process of helics3 changes that could be merged into develop
> App api tidy updates

- src/helics/shared_api_library/ValueFederate.h
If merged this pull request will add documentation to ValueFederate.h in the shared API.
- Adds missing parameter descriptions to src/helics/shared_api_library/ValueFederate.h for the helicsFederateClearUpdates() and helicsFederateRegisterFromPublicationJSON() functions.
> Added parameter descriptions.

- src/helics/application_api/Inputs.cpp
- src/helics/application_api/Inputs.hpp
- src/helics/application_api/helicsPrimaryTypes.cpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/core/CommonCore.hpp
- src/helics/cpp98/Input.hpp
- src/helics/cpp98/Publication.hpp
- src/helics/cpp98/ValueFederate.hpp
- src/helics/helics_enums.h
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/MessageFilters.h
- src/helics/shared_api_library/MessageFiltersExport.cpp
- src/helics/shared_api_library/ValueFederate.h
- src/helics/shared_api_library/ValueFederateExport.cpp
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/MultiInputTests.cpp
- add multi-input tests to the c++98 API tests
- update the C shared library functions to match the C++ API changes
- fix a few bugs in the publish vector for C++98
- make a few more tweaks to the input class
> add multiInput test for the C++98 interface 

- .github/workflows/formatting.yml
- .github/workflows/swig-interface-gen.yml
> Switch pr action

- config/helics-config.h.in
If merged this pull request will replace a (last?) copyright symbol with `(c)`. Also changes the encoding from ISO-8859-1 to UTF-8 to match the other files in the repository.
- Replace copyright symbol in helics-config.h.in with `(c)`
> Replace copyright symbol

- .circleci/tsan_suppression.txt
- docs/user-guide/queries.md
- src/helics/apps/helicsWebServer.cpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CoreBroker.cpp
- tests/helics/system_tests/QueryTests.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will add uuid support for broker names and the field in some queries, and support for generating UUID broker names in the webserver.  
- uuid support in webserver
- appropriate respond fields from generating a broker
- uuid field in some queries if a uuid was used as the broker name
> Add uuid support in the webserver

- docs/configuration/FederateFlags.md
- docs/user-guide/index.md
- docs/user-guide/multiSourceInputs.md
- src/helics/application_api/Federate.cpp
- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/application_api/Inputs.cpp
- src/helics/application_api/Inputs.hpp
- src/helics/application_api/MessageFederate.cpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/common/CMakeLists.txt
- src/helics/common/addTargets.cpp
- src/helics/common/addTargets.hpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/InterfaceInfo.cpp
- src/helics/helics_enums.h
- tests/helics/application_api/MultiInputTests.cpp
- tests/helics/system_tests/ErrorTests.cpp
- tests/helics/test_files/multi_input_config.json
- tests/helics/test_files/multi_input_config.toml
If merged this pull request will add some docs and configure capability for the multi-input handling
- add a docs page
- add configure capability for the options from json/toml files
> Docs and config

- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/common/addTargets.cpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/helics.h
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/test_files/bes_config.json
- tests/helics/test_files/bes_config.toml
- tests/helics/test_files/bes_config2.json
- tests/helics/test_files/bes_config2.toml
add simpler files and fix the loading of the configuration file
Merge branch 'docs_and_config' into config_tests
add a test of the configure file and checks to make sure it sets the correct flags
If merged this pull request will add some config tests to make sure flags are getting loaded properly. 
Fixes #1395 
- add config tests
- add a processing loop for the flags
- add a getFlagIndex function to the C and C++ api to get flag specific indices
- refactor some of the code in the federateInfo.cpp
> add some more config tests to make sure the flags are working properly

- tests/helics/application_api/ValueFederateKeyTests.cpp
If merged this pull request will remove flag config tests if zmq is disabled
> fix the new flag config cases if zmq is disabled

- CMakeLists.txt
- interfaces/python/CMakeLists.txt
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/InputInfo.cpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- tests/helics/system_tests/TimingTests2.cpp
- tests/java/CMakeLists.txt
- tests/java/JavaHelicsApiTests.java
If merged this pull request will fix an issue with the wait_for_current_time flag and fix some of the java test that were only passing since there was a bug in time handling.
> Wait for current time fix

- src/helics/application_api/BrokerApp.cpp
- src/helics/application_api/BrokerApp.hpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/Broker.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/flagOperations.hpp
- src/helics/cpp98/Broker.hpp
- src/helics/network/tcp/TcpComms.cpp
- src/helics/shared_api_library/helics.h
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/timingTests_cpp.cpp
- tests/helics/system_tests/TimingTests2.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will add a global time barrier for debugging.
- address #479 
- add a global time barrier and an ability to update it.  
- add some test for the global time barrier
- add time barrier functions to the C api
- add time barrier functions to the C++98 API
> Global time block

- docs/user-guide/debugging.md
- docs/user-guide/index.md
- docs/user-guide/webserver.md
If merged this pull request will add some documentation for the time Barrier operations
> add some docs for the time barrier operations

- docs/user-guide/queries.md
- src/helics/application_api/Federate.cpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/application_api/queryFunctions.cpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/common/CMakeLists.txt
- src/helics/common/JsonGeneration.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/InputInfo.cpp
- src/helics/core/queryHelpers.hpp
- tests/helics/application_api/FederateTests.cpp
- tests/helics/common/CMakeLists.txt
- tests/helics/common/JsonGenerationTests.cpp
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/system_tests/QueryTests.cpp
- tests/helics/webserver/webServerHttpTests.cpp
If merged this pull request will convert all queries to respond with valid json strings
- string vectors are json string vector as are numerical vectors
- invalid queries respond with http response code and message.
> All queries JSON

- .github/workflows/formatting.yml
- .github/workflows/swig-interface-gen.yml
If merged this pull request will get a full clone of the git repository for workflows that generate PRs.
- fetch all git history for swig update workflow
- fetch all git history for formatting workflow
> HELICS 3 PR generation full git clone

- src/helics/application_api/ValueConverter.cpp
- src/helics/application_api/ValueConverter.hpp
- tests/helics/application_api/ValueConverterTests.cpp
If merged this pull request will add serializers and deserializers for the primary helics data types
- to/from binary converters for common data types 
- tests of the converters
> Helics3 converters

- .github/workflows/formatting.yml
- .github/workflows/swig-interface-gen.yml
If merged this pull request will cherry-pick the helics3 workflow changes to do a full git clone for PR generating workflows.
- Cherry pick commit 8f3e915
> Backport git full clone workflow changes

- benchmarks/helics/echoBenchmarks_py.py
If merged this pull request will add a Python version of the echoBenchmark.
Once the function run time issues for core types ipc, tcp, and tcpss using this Python version of echoBenchmark are resolved, add these core types to the overall echoBenchmark run.
> Benchmark python testing

- src/helics/common/CMakeLists.txt
- src/helics/common/SmallBuffer.cpp
- src/helics/common/SmallBuffer.hpp
- tests/helics/common/CMakeLists.txt
- tests/helics/common/SmallBufferTests.cpp
If merged this pull request will add a SmallBuffer implementation to the Helics/common library
- SmallBuffer Implementation
- tests for Small Buffer
NOTE:  this has not been integrated into usage, that will be the next PR
> Small buffer

- benchmarks/helics/echoBenchmarks_py.py
- interfaces/csharp/CMakeLists.txt
- interfaces/java/CMakeLists.txt
- interfaces/python/CMakeLists.txt
If merged this pull request will remove debug postfix on interface libraries(python, java, c#)
FIx issue #1491
> remove the debug postfix on interface libraries(python, java, csharp)

- src/helics/application_api/ValueFederate.cpp
- src/helics/common/JsonProcessingFunctions.cpp
- src/helics/common/TomlProcessingFunctions.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/test_files/example_value_fed.json
If merged this pull request will allow the use of "unit"  in addition to "units"  and fix the fact that most config files were incorrect with regard to the units since they had "unit"
> Unit eq units

- benchmarks/helics/multinode/README.md
- benchmarks/helics/multinode/echo-sbatch-submitter.sh
- benchmarks/helics/multinode/index-bm.sbatch
- benchmarks/helics/multinode/index-hub-bm.sbatch
- benchmarks/helics/multinode/index-maxindex-bm.sbatch
- benchmarks/helics/multinode/index-msg_size-msg_count-bm.sbatch
- benchmarks/helics/multinode/launch_node_federates.sh
- benchmarks/helics/multinode/messageexchange-sbatch-submitter.sh
- benchmarks/helics/multinode/mpi-sbatch-submitter.sh
- benchmarks/helics/multinode/phold-sbatch-submitter.sh
- benchmarks/helics/multinode/phold.sbatch
- benchmarks/helics/multinode/ringtransmit-sbatch-submitter.sh
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz1-cnt1.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz1-cnt16.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz1-cnt64.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz2048-cnt1.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz2048-cnt16.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz2048-cnt64.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz256-cnt1.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz256-cnt16.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz256-cnt64.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz64-cnt1.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz64-cnt16.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange-sz64-cnt64.conf
- benchmarks/helics/multinode/srun-multi-prog/MessageExchange.conf
- benchmarks/helics/multinode/submit-mpi.sbatch
- benchmarks/helics/multinode/timing-sbatch-submitter.sh
- benchmarks/helics/multinode/wattsstrogatz-sbatch-submitter.sh
If merged this pull request will add the latest version of the scripts used to run benchmarks on clusters using slurm.
> Benchmark scripts

- src/helics/application_api/Inputs.hpp
- src/helics/application_api/ValueConverter_impl.hpp
- src/helics/core/helicsCLI11.hpp
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/shared_library/test-value-federate1.cpp
If merged this pull request will add some additional tests for default values and more descriptive error messages
> Complex test

- src/helics/cpp98/Endpoint.hpp
- src/helics/cpp98/helics.hpp
free functions and fix output type for endpoint getType
If merged this pull request will add inline to free functions in the C++98 API and fix a type inconsistency in one function.
> add inline to cpp98 

- scripts/run-circleci-tests.sh
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/shared_library/SystemTests.cpp
If merged this pull request will make sure to clear valid bits after closeLibrary to make sure there is no double free
> Test after close library

- src/helics/cpp98/Endpoint.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/cpp98/MessageFederate.hpp
- tests/helics/shared_library/test-message-federate_cpp.cpp
If merged this pull request will add some creation functions and tests for the Message object in the C++98 API.
> add some Message constructors and tests in the C++98 API

- src/helics/core/CommonCore.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/InputInfo.cpp
- src/helics/core/InputInfo.hpp
> make sure to log the send_message operation through the federate logging

- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
If merged this pull request will Update the console loggers to use a specific one instead of the default.  Then flush according to the policy.
> Change default console logger

- src/helics/network/mpi/MpiComms.cpp
If merged this pull request will update handling of the NEW_ROUTE command in MpiComms to work with the SmallBuffer changes.
- Convert SmallBuffer payload to a string for NEW_ROUTE commands in MpiComms
> Update NEW_ROUTE command in MpiComms to work with SmallBuffer

- CHANGELOG.md
- CMakeLists.txt
If merged this pull request will add some update docs for the alpha release
> release docs for alpha release

- config/cmake/addlibzmq.cmake
Update default libzmq to 4.3.3
> update the default libzmq for build

- src/helics/network/tcp/TcpHelperClasses.cpp
If merged this pull request will address  the bug #1380 
resend the non sent part of the buffer up to 5 times
> Retry partial TCP buffer sends

- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/cpp98/Federate.hpp
- src/helics/cpp98/config.hpp
- src/helics/shared_api_library/api-data.h
- src/helics/shared_api_library/helicsCallbacks.cpp
- src/helics/shared_api_library/helicsCallbacks.h
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will add a callback for a federate to respond to custom queries.
> C api query callback

- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/InputInfo.cpp
- src/helics/core/InputInfo.hpp
- src/helics/core/PublicationInfo.cpp
- src/helics/core/PublicationInfo.hpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/test_files/fed1_config.json
- tests/helics/test_files/fed2_config.json
If merged this pull request will handle a call to registerInterface with the same file as in the create step and deal with duplicate targets appropriately.
- fix a bug in the json file handler in the case of duplicate subscriptions
- handle duplicate targets for publications and subscriptions appropriately
- add a warning for duplicate targets for inputs.  
- Fix Issue #1552   not by error but just handling the situation appropriately
> Add handling for duplicate target specification

- src/helics/network/NetworkBrokerData.cpp
- src/helics/network/NetworkCommsInterface.cpp
- tests/helics/system_tests/networkTests.cpp
If merged this pull request will fix a potential mechanism to force the system to try to bind to negative port numbers if custom port numbers are used.
> Broker port tests

- docs/configuration/FederateFlags.md
- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/helics_definitions.hpp
- src/helics/helics_enums.h
- tests/helics/system_tests/brokerTimeoutTests.cpp
If merged this pull request will add a flag to indicate a user debugging session may occur.  This turns off some timeouts and enables the slow_responding indicator.  There is nothing new here other than support for the flag to trigger others.
> add debugging flag

- CHANGELOG.md
- CMakeLists.txt
- docs/ROADMAP.md
- src/helics/application_api/ValueFederateManager.cpp
> Update release docs for a 2.6.1 release

- .circleci/config.yml
- config/cmake/copy_key_files.cmake
- interfaces/octave/octave_maps.i
- tests/octave/messageFedTests.m
- tests/octave/messageFilterTests.m
- tests/octave/runTestsCIRCLECI.m
- tests/octave/valueFedTests.m
If merged this pull request will fix the octave build and tests
> Octave build

- config/cmake/addfmt.cmake
If merged this pull request will update fmtlib to 7.1.1
> update fmtlib to 7.1.1

- config/cmake/addlibzmq.cmake
If merged this pull request will update zmq to 4.3.3
> update libzmq to 4.3.3

- src/helics/cpp98/Endpoint.hpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFederateExport.cpp
- tests/helics/shared_library/evilInputTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
If merged this pull request will address Issue #1652 and rename helicsMessageCheckFlag to helicsMessageGetFlagOption for better symmetry between the the set and get methods and for clarity.
> Issue #1652

- .ci/azure-pipelines.yml
- docs/developer-guide/swig.md
- docs/user-guide/simulator_integration.md
- scripts/setup-helics-ci-options.sh
- src/helics/application_api/MessageFederate.cpp
- src/helics/core/SmallBuffer.hpp
- tests/helics/application_api/ValueConverterTests.cpp
If merged this pull request will attempt to fix a few code warnings in the different builds for HELICS 3
> Fix a few warnings in mac and other builds

- .gitattributes
- docs/introduction/hello-world-VS.md
- docs/introduction/hello-world.md
- docs/user-guide/queries.md
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/application_api/FederateInfo.cpp
- src/helics/common/JsonBuilder.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/core-data.hpp
- src/helics/cpp98/Endpoint.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/cpp98/config.hpp
- src/helics/network/tcp/TcpHelperClasses.cpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/api-data.h
- src/helics/shared_api_library/helicsCallbacks.cpp
- src/helics/shared_api_library/helicsCallbacks.h
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/PropertyIndexTests.cpp
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will merge in another set of changes from HELICS2 for bug fixes and improvements
> H3 merge h2 3

- benchmarks/helics/EchoMessageLeafFederate.hpp
- benchmarks/helics/MessageExchangeFederate.hpp
- benchmarks/helics/PholdFederate.hpp
- benchmarks/helics/WattsStrogatzFederate.hpp
- benchmarks/helics/echoBenchmarks_c.cpp
If merged this pull request will fix the benchmarks for helics3 based on previous API changes
> adjust the benchmarks with API changes for HELICS3

- CMakeLists.txt
- docs/ROADMAP.md
- tests/helics/system_tests/networkTests.cpp
If merged this pull request will update docs and fix no_zmq test failure
> doc update for alpha.2 release

- src/helics/core/ActionMessage.cpp
- src/helics/core/CoreBroker.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
If merged this pull request will add a warning message to a federate if a message is sent to an unknown destination and cannot be delivered.  Also included are test cases for this situation.
> Add a warning message if a message is sent to an unknown destination

- docs/user-guide/queries.md
- src/helics/application_api/BrokerApp.hpp
- src/helics/application_api/CoreApp.hpp
- src/helics/core/Broker.hpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/cpp98/Broker.hpp
- tests/helics/application_api/CMakeLists.txt
- tests/helics/application_api/FederateTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/apps/CoreAppTests.cpp
- tests/helics/core/BrokerClassTests.cpp
- tests/helics/shared_library/SystemTests.cpp
If merged this pull request will make the "global" compliant with JSON
add a "global_value" target that is explicitly not compliant with JSON
Address Issue #1712
> make the "global" query target compliant with JSON, 

- .github/actions/linux-release-builder/Dockerfile
- .github/workflows/release-build.yml
If merged this pull request will merge the workflow updates for nightly release build tests from master to develop
> Sync release build workflow changes with develop

- .github/workflows/code-coverage.yml
If merged this pull request will add a code coverage build for HELICS 3 running on GitHub Actions for PRs and commits to the main, develop, and helics3 branches.
* Add a code coverage workflow running on GitHub Actions
> Add code coverage build for HELICS 3 on GHA

- .ci/azure-pipelines.yml
> Install Boost 1.74 on Windows Azure Pipelines builds

- src/helics/application_api/Endpoints.hpp
- src/helics/application_api/Federate.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/EndpointInfo.hpp
- src/helics/core/FilterFederate.cpp
- src/helics/core/FilterFederate.hpp
- src/helics/core/InterfaceInfo.cpp
- src/helics/shared_api_library/MessageFederate.h
- tests/helics/application_api/FilterTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/system_tests/iterationTests.cpp
fix some warnings and make it possible to set default for messages to have a required destination
> message required destinations

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update the units library to the latest master and the filesystem library to the latest version.
> Update units library and filesystem header

- tests/helics/application_api/FilterTests.cpp
If merged this pull request will fix a failing test when the ZMQ core was turned off.
> Fix a test that was failing under the no-zmq condition

- src/helics/application_api/ValueFederate.cpp
- src/helics/apps/helics-broker-server.cpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/BrokerFactory.cpp
- src/helics/core/BrokerFactory.hpp
- tests/helics/system_tests/networkTests.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will fix broken NO_ZMQ tests and fix some issues with broker_server
> Broker server tests

- src/helics/application_api/Endpoints.hpp
- src/helics/application_api/Federate.cpp
- src/helics/apps/Clone.cpp
- src/helics/apps/Recorder.cpp
- src/helics/apps/Recorder.hpp
- src/helics/apps/Tracer.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/FilterFederate.cpp
- src/helics/core/FilterFederate.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- src/helics/core/core-types.hpp
- src/helics/core/flagOperations.hpp
- src/helics/shared_api_library/api-data.h
- tests/helics/application_api/FederateTests.cpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/apps/RecorderTests.cpp
- tests/helics/apps/combo_tests.cpp
- tests/helics/system_tests/QueryTests.cpp
to force the registration for the clone and recorder filters to resolve sporadic failure
If merged this pull request will add a global_flush query that will flush the system and try to resolve the sporadic failures on the apps.
> Try a flush query

- .cirrus.yml
- src/helics/application_api/Federate.cpp
- src/helics/apps/Clone.cpp
- src/helics/apps/Recorder.cpp
- src/helics/apps/Recorder.hpp
- src/helics/apps/Tracer.cpp
- src/helics/apps/helics-broker-server.cpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/core/BrokerFactory.cpp
- src/helics/core/BrokerFactory.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/FilterFederate.cpp
- src/helics/core/FilterFederate.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- src/helics/core/flagOperations.hpp
- src/helics/shared_api_library/api-data.h
- tests/helics/application_api/FederateTests.cpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/apps/RecorderTests.cpp
- tests/helics/apps/combo_tests.cpp
- tests/helics/system_tests/QueryTests.cpp
- tests/helics/system_tests/networkTests.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will merge in recent updates and fixes from develop into the HELICS 3 branch
> Flush merge 3

- interfaces/CMakeLists.txt
If merged this pull request will add swigwin-4.0.2 to the list of directories on Windows to search for swig.
- Add swigwin-4.0.2 to list of search path hints on Windows
> Add swigwin-4.0.2 to list of search paths

- src/helics/core/FilterFederate.cpp
- src/helics/core/FilterFederate.hpp
- src/helics/core/TimeCoordinator.cpp
- tests/helics/application_api/FilterTests.cpp
If merged this pull request will fix some timing issues with filters
- add a failing test
- add the fixes to the failing test
> Timing fix try4

- docs/user-guide/debugging.md
If merged this pull request will add additional information about logging, players and recorders to the userguide
Added two new sections to that doc page
> Add logging, player, + recorder to debug note in User Guide

- docs/user-guide/program_termination.md
- src/helics/application_api/Federate.cpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/BrokerFactory.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreFactory.cpp
- src/helics/network/CommsInterface.cpp
- src/helics/network/CommsInterface.hpp
- src/helics/network/tcp/TcpComms.cpp
- src/helics/network/udp/UdpComms.cpp
- src/helics/shared_api_library/helics.h
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/application_api/FederateTests.cpp
- tests/helics/shared_library/SystemTests.cpp
> Pre commit/update test signal handler

- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/network/tcp/TcpHelperClasses.cpp
- tests/helics/core/TimeCoordinatorTests.cpp
- tests/helics/system_tests/TimingTests2.cpp
If merged this pull request will tweak the time granting for wait for current time,  add some specific tests related to #1926
- tweak time grant under wait_for_current_time_flag
- add some testing support in TimeCoordinator.cpp
> add a test case and try to fix the wait for current time bug

- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- tests/helics/system_tests/QueryTests.cpp
to meet the requirements of HE…LICS3 and fix the tests
If merged this pull request will change the added helics 2 query errors to be in json format and fix some missing disconnect code.
> update the queries added from HELICS 2 

- src/helics/common/AsioContextManager.cpp
- src/helics/shared_api_library/helicsExport.cpp
Signed-off-by: Ed Beroset <beroset@ieee.org>
If merged this pull request will fix #1960 
Minimal change to add missing #include <thread>
> Fix #1960 by adding missing #include <thread>.

- docs/developer-guide/style.md
- src/helics/application_api/FederateInfo.cpp
If merged this pull request will standardize the names of the federate options to conform to the v3 standard.
> V3b cmd line cleanup

- src/helics/application_api/Federate.cpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/ForwardingTimeCoordinator.cpp
- src/helics/core/ForwardingTimeCoordinator.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- src/helics/core/flagOperations.hpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/apps/TracerTests.cpp
- tests/helics/core/ForwardingTimeCoordinatorTests.cpp
- tests/helics/system_tests/TimingTests2.cpp
If merged this pull request will fix some issues with `wait_for_current_time_flag` and its use with endpoints.  
-  add some tests
- add error checks for multiple federates using the flag
- change the timing so wait_for_current_time works on time 0 as well
- make it so wait_for_current_time works with endpoints
> Wait flag endpoint update

- docs/user-guide/examples/fundamental_examples/fundamental_fedintegration.md
- src/helics/application_api/Federate.cpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/ForwardingTimeCoordinator.cpp
- src/helics/core/ForwardingTimeCoordinator.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- src/helics/core/flagOperations.hpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/apps/TracerTests.cpp
- tests/helics/core/ForwardingTimeCoordinatorTests.cpp
- tests/helics/system_tests/TimingTests2.cpp
* start testing and working on the wait for current time flag interaction with the forwarding time coordinator which mainly impacts endpoints
* fix more test cases
* fix blocking test
* fix failing tests
* Automated formatting of repo files (#1980)
Co-authored-by: Philip Top <top1@llnl.gov>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
If merged this pull request will merge in the recent fix from HELICS 2 for wait_for_current_time_flag and endpoints
> Wait flag endpoint update (#1979)

- docs/user-guide/installation/linux.md
- src/helics/common/AsioContextManager.cpp
- src/helics/shared_api_library/helicsExport.cpp
If merged this pull request will merge in recent PR's from master to the HELICS 3 branch
> Helics3 dev merge

- docs/developer-guide/porting-2-to-3.md
- src/helics/application_api/Federate.hpp
- src/helics/application_api/FederateInfo.cpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/loggingHelper.hpp
- src/helics/helics_enums.h
- src/helics/shared_api_library/FederateExport.cpp
- tests/helics/application_api/FederateInfoTests.cpp
- tests/helics/application_api/FederateTests.cpp
- tests/helics/application_api/LoggingTests.cpp
- tests/helics/apps/BrokerAppTests.cpp
- tests/helics/apps/CoreAppTests.cpp
- tests/helics/apps/test_files/federate_config.json
- tests/helics/core/BrokerClassTests.cpp
- tests/helics/core/CoreFactory-tests.cpp
- tests/helics/test_files/Control_test.json
- tests/helics/test_files/bes_config.json
- tests/helics/test_files/bes_config.toml
- tests/helics/test_files/bes_config2.json
- tests/helics/test_files/example_message_fed_testb.json
- tests/helics/test_files/example_value_fed_testb.json
for logging levels and update some docs and other oversights in debug logging
If merged this pull request will make it so log levels only support the text equivalent and add a debug log level.
> update the checks to only support text names 

- .gitmodules
- CMakeLists.txt
- config/cmake/addJsoncpp.cmake
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/queryHelpers.hpp
If merged this pull request will fix the docker builds by moving the jsoncpp third party library and fix a few warnings.
> Docker builds

- vcpkg.json
If merged this pull request will merge master changes back into develop to resolve conflict in previous PR
> Develop master merge

- CMakeLists.txt
- README.md
- benchmarks/helics/ActionMessageBenchmarks.cpp
- src/helics/application_api/BrokerApp.hpp
- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/GlobalFederateId.hpp
- src/helics/core/flagOperations.hpp
- src/helics/network/CommsInterface.hpp
- src/helics/network/NetworkBrokerData.cpp
- src/helics/network/NetworkBrokerData.hpp
- src/helics/network/NetworkBroker_impl.hpp
- src/helics/network/NetworkCommsInterface.cpp
- src/helics/network/NetworkCore_impl.hpp
- src/helics/network/zmq/ZmqComms.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- tests/helics/application_api/FederateTests.cpp
- tests/helics/core/ActionMessage-tests.cpp
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will add a json serialization method for the action Messages
This is step 1 for a compatibility layer.  
Step 2 is a json translation of the value layer.  
- add json serialization for the ActionMessages.   
- add some test cases to test the serialization as unit tests and as part of a federation.  
- add a benchmark test for the serialization ( basically 100x slower)
> Json serialization

- .ci/.drone.yml
- .ci/azure-pipelines-daily.yml
- .ci/azure-pipelines.yml
- .circleci/config.yml
- .github/workflows/code-coverage.yml
- .github/workflows/compress-images.yml
- .github/workflows/formatting.yml
- .github/workflows/static-analyzers.yml
- .github/workflows/swig-interface-gen.yml
- CONTRIBUTORS.md
- README.md
- appveyor.yml
- docs/conf.py
- docs/index.md
- docs/user-guide/advanced_topics/advanced_topics_index.md
- docs/user-guide/fundamental_topics/fundamental_topics_index.md
- docs/user-guide/orientation.md
- src/docs/c_api_reference.dox
If merged this pull request will clean up some links on the readme and user guide pages
> Clean up links

- src/helics/core/TimeCoordinator.cpp
- src/helics/helics_enums.h
- tests/helics/system_tests/TimingTests.cpp
If merged this pull request will add some tests for uninterruptible flag and iterations and actually make that work properly.  
- make a few fixes for uninterruptible cases and the use of periods
- fix a bug in the two-way-comms test case
- fix the uninterruptible flag and iterations
- make an attempt at fixing a crash on one of the profiling test cases.
> Uninterruptible flag check

- .github/workflows/formatting.yml
- .github/workflows/static-analyzers.yml
If merged this pull request will add workflow_dispatch triggers for the formatting and static analyzer workflows, making so they can be triggered manually.
* Add workflow_dispatch triggers to formatting and static analyzer workflows
> Add workflow_dispatch trigger to formatting and static analyzer workflows

- .github/workflows/formatting.yml
- .github/workflows/static-analyzers.yml
- .pre-commit-config.yaml
- docs/references/api-reference/index.md
- scripts/render-doxyfile.py
If merged this pull request will merge CI workflow changes (and doc fixes) from main to develop. This probably should not be squash merged.
> Merge CI/doc updates from main to develop

- docs/conf.py
- scripts/cmake-format-helper.py
- src/helics/application_api/Federate.hpp
- src/helics/core/ActionMessage.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/backup/helics/helics_api.h
If merged this pull request should run the required check needed to merge the formatting changes in #2064.
>  Automated formatting of repo files

- src/helics/core/ActionMessage.cpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/flagOperations.hpp
- src/helics/core/global_federate_id.hpp
- src/helics/network/CommsInterface.hpp
- src/helics/network/NetworkBrokerData.cpp
- src/helics/network/NetworkBrokerData.hpp
- src/helics/network/NetworkBroker_impl.hpp
- src/helics/network/NetworkCommsInterface.cpp
- src/helics/network/NetworkCore_impl.hpp
- src/helics/network/zmq/ZmqComms.cpp
- tests/helics/application_api/FederateTests.cpp
- tests/helics/core/ActionMessage-tests.cpp
If merged this pull request will merge the actionMessage serialization into HELICS 2
> Json serialization2

- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/application_api/HelicsPrimaryTypes.hpp
- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/application_api/ValueFederateManager.hpp
- src/helics/application_api/helicsPrimaryTypes.cpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/application_api/helicsTypes.hpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/helics_enums.h
- tests/helics/application_api/PrimaryTypeConversionTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/application_api/helicsTypeTests.cpp
If merged this pull request will merge in the helics2 json data serialization changes.
There will be one more related PR after this to add in the HELICS 3 data parsing layer.  This one doesn't contain new code just the HELICS 3 changes.
> merge the changes from Json data serialization into HELICS 2

- .github/workflows/compress-images.yml
- .github/workflows/formatting.yml
- .github/workflows/static-analyzers.yml
- .github/workflows/swig-interface-gen.yml
Change `helics3` triggers for workflows to `helics2` in the helics2 branch.
> Update helics2 workflows to run on PRs and pushes

- CHANGELOG.md
- CMakeLists.txt
- config/cmake/addUnits.cmake
- src/helics/core/CommonCore.cpp
If merged this pull request will update the units library to 0.5.0
> upgrade the units library to 0.5.0

- CHANGELOG.md
- CMakeLists.txt
- src/helics/cpp98/Endpoint.hpp
- src/helics/cpp98/MessageFederate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/helics.h
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/badInputTests.cpp
- tests/helics/shared_library/evilInputTests.cpp
- tests/helics/shared_library/test-message-federate.cpp
a few final deprecations and additions from HELICS 3 and update the date and changelog
> Pending count

- .pre-commit-config.yaml
- docs/user-guide/advanced_topics/multiSourceInputs.md
- docs/user-guide/advanced_topics/orchestration_monte_carlo.md
- docs/user-guide/examples/advanced_examples/advanced_examples_index.md
- docs/user-guide/examples/advanced_examples/advanced_query.md
- docs/user-guide/examples/fundamental_examples/fundamental_combo.md
- docs/user-guide/examples/fundamental_examples/fundamental_endpoints.md
- docs/user-guide/examples/fundamental_examples/fundamental_examples_index.md
- docs/user-guide/examples/fundamental_examples/fundamental_fedintegration.md
- docs/user-guide/examples/fundamental_examples/fundamental_native_filter.md
- docs/user-guide/fundamental_topics/interface_configuration.md
- docs/user-guide/fundamental_topics/logging.md
- docs/user-guide/fundamental_topics/simulator_integration.md
- docs/user-guide/fundamental_topics/stages.md
- docs/user-guide/fundamental_topics/timing_configuration.md
If merged this pull request will cherry-pick the addition of the blacken-docs pre-commit hook from #2152
- Add blacken-docs pre-commit hook
> Add blacken-docs pre-commit hook

- src/helics/core/SmallBuffer.hpp
- src/helics/shared_api_library/MessageFederateExport.cpp
If merged this pull request will add a null terminator in a few select spots in the C API for message objects.
> fix null terminator issue in the C library for message objects

- ThirdParty/helics/external/filesystem.hpp
If merged this pull request will update third party libraries to latest releases
> Third party updates

- docs/user-guide/advanced_topics/advanced_topics_index.md
- docs/user-guide/advanced_topics/dynamic_federations.md
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/application_api/FederateInfo.cpp
- src/helics/application_api/FederateInfo.hpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/core/flagOperations.hpp
- src/helics/network/CommsInterface.cpp
- src/helics/network/CommsInterface.hpp
- src/helics/network/NetworkBrokerData.hpp
- src/helics/network/NetworkBroker_impl.hpp
- src/helics/network/NetworkCore_impl.hpp
- src/helics/network/inproc/InprocComms.cpp
- src/helics/network/test/TestComms.cpp
- src/helics/shared_api_library/FederateExport.cpp
- tests/helics/system_tests/CMakeLists.txt
- tests/helics/system_tests/dynamicFederationTests.cpp
If merged this pull request will add the capability for dynamic observer federates
> Observer feds

- .pre-commit-config.yaml
If merged this pull request will set pre-commit.ci to make autoupdate PRs against the develop branch; using the newly added `autoupdate_branch` setting (https://github.com/pre-commit-ci/issues/issues/37). This change will take effect once we make our next release to `main` this upcoming week.
- Set autoupdate branch for pre-commit.ci to develop
> pre-commit.ci: autoupdate the develop branch

- ThirdParty/helics/external/filesystem.hpp
- config/cmake/addlibzmq.cmake
- config/cmake/compiler_flags.cmake
- interfaces/java/CMakeLists.txt
- src/helics/application_api/HelicsPrimaryTypes.hpp
- src/helics/application_api/Inputs.cpp
- src/helics/application_api/ValueConverter.cpp
- src/helics/application_api/helicsTypes.cpp
- src/helics/apps/AsioBrokerServer.cpp
- src/helics/apps/Recorder.cpp
- src/helics/apps/Recorder.hpp
- src/helics/core/fileConnections.hpp
- src/helics/network/mpi/MpiService.cpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/application_api/ValueConverterTests.cpp
- tests/helics/apps/BrokerServerTests.cpp
- tests/helics/apps/CloneTests.cpp
- tests/helics/apps/PlayerTests.cpp
- tests/helics/apps/combo_tests.cpp
- tests/helics/common/SmallBufferTests.cpp
- tests/helics/core/ActionMessage-tests.cpp
If merged this pull request will clean up a number of warnings from various compilers and situations
and update the toml11 library.
> Fix warnings

- benchmarks/helics/BarabasiAlbertFederate.hpp
- benchmarks/helics/BenchmarkMain.cpp
- benchmarks/helics/CMakeLists.txt
- benchmarks/helics/barabasiAlbertBenchmarks.cpp
If merged this pull request will add BA federate & benchmark (w/ edits to BenchmarkMain and cmakelists)
> add Barabasi-Albert benchmark

- CHANGELOG.md
- CMakeLists.txt
- CONTRIBUTORS.md
- README.md
- appveyor.yml
- docs/Public_API.md
- docs/ROADMAP.md
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreTypes.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- tests/helics/apps/CloneTests.cpp
- vcpkg.json
If merged this pull request will update the version number and some other docs for a 3.1 release
> Final update for a HELICS 3.1 release

- CMakeLists.txt
- src/helics/core/BrokerBase.cpp
If merged this pull request will update the conditions for including syslog for mingw
> add conditions for not including syslog

- CMakeLists.txt
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
If merged this pull request will fix the tsan warning generated from fixing #2230
> Fix logging tsan

- CHANGELOG.md
- CMakeLists.txt
- appveyor.yml
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCore.h
- vcpkg.json
If merged this pull request will update changelog and version numbers for 3.1.1 release.
> update changelog and version numbers for a 3.1.1 release.

- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCallbacks.cpp
- src/helics/shared_api_library/helicsCallbacks.h
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/shared_library/timingTests_cpp.cpp
The callback executes before the value/message update callbacks.
If merged this pull request will add a timeUpdate callback and a few tests of it
> add a callback for time update in the application API. 

- src/helics/apps/AsioBrokerServer.cpp
- src/helics/apps/zmqBrokerServer.cpp
- src/helics/network/CMakeLists.txt
- src/helics/network/networkDefaults.cpp
- src/helics/network/networkDefaults.hpp
- src/helics/network/tcp/TcpComms.cpp
- src/helics/network/tcp/TcpCommsSS.cpp
- src/helics/network/udp/UdpComms.cpp
- src/helics/network/zmq/ZmqComms.cpp
- src/helics/network/zmq/ZmqCommsSS.cpp
to make it easier if we decide to use an environment variable later.
> clean up the usage of the network default ports 

- src/helics/network/tcp/TcpComms.cpp
- src/helics/network/tcp/TcpCommsSS.cpp
If merged this pull request will update the networking library to recent main which should fix some msys issues.
>  Networking update

- examples/comboFederates1/comboFed.cpp
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/Core.hpp
- src/helics/core/CoreTypes.hpp
- src/helics/core/EmptyCore.cpp
- src/helics/core/EmptyCore.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCore.h
- tests/helics/application_api/LoggingTests.cpp
If merged this pull request will add a processCommunications operation to federates to process the internal message queue with no expected result.  
This is useful to clear up some failing tests cases, and will likely be more necessary for the single core operations when those arrive.
> Process comms

- docs/user-guide/advanced_topics/commandInterface.md
- docs/user-guide/advanced_topics/queries.md
- docs/user-guide/fundamental_topics/logging.md
- src/helics/apps/MultiBroker.cpp
- src/helics/common/CMakeLists.txt
- src/helics/common/logging.cpp
- src/helics/common/logging.hpp
- src/helics/core/ActionMessage.hpp
- src/helics/core/ActionMessageDefintions.hpp
- src/helics/core/BrokerBase.cpp
- src/helics/core/BrokerBase.hpp
- src/helics/core/CMakeLists.txt
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/GlobalFederateId.hpp
- src/helics/core/LogManager.cpp
- src/helics/core/LogManager.hpp
- src/helics/core/TimeoutMonitor.cpp
- src/helics/core/loggingHelper.hpp
- src/helics/network/inproc/InprocComms.cpp
- src/helics/network/mpi/MpiComms.cpp
- src/helics/network/test/TestComms.cpp
- src/helics/network/zmq/ZmqComms.cpp
- src/helics/network/zmq/ZmqCommsSS.cpp
- tests/helics/application_api/LoggingTests.cpp
If merged this pull request will add a remote log capability into HELICS
- add remote log commands
- add remote log support in the logging system
-  move the logging operations to a dedicated class
> Remote log

- src/helics/shared_api_library/MessageFederate.h
- src/helics/shared_api_library/helicsCore.h
Fixes some doc strings that don't work well with the RTD website theme.
> Fix C API doc strings that break RTD website theme

- CHANGELOG.md
- CMakeLists.txt
- appveyor.yml
- docs/Public_API.md
- docs/ROADMAP.md
- docs/references/api-reference/C_API.md
- docs/references/configuration_options_reference.md
- docs/user-guide/fundamental_topics/logging.md
- vcpkg.json
If merged this pull request will update version numbers and release documents for 3.1.2 release.
> Update version and release docs for release 3.1.2

- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCallbacks.h
- tests/helics/application_api/ValueFederateKeyTests.cpp
- tests/helics/shared_library/test-value-federate2.cpp
If merged this pull request will add a callback that gets executed when the federate state changes
> add a state change callback to the various API's

- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- tests/helics/application_api/LoggingTests.cpp
If merged this pull request will hopefully fix the sporadic failure in the fedMonitorSwap test
> add in an additional check for the fedMonitor swap test case

- src/helics/core/FederateState.cpp
- tests/helics/system_tests/TimingTests2.cpp
If merged this pull request will fix a timing issue when subscribing to publications from an endpoint
> Fix missing timing dependency when subscribing from an endpoint

- src/helics/core/CoreBroker.cpp
- src/helics/network/tcp/TcpComms.cpp
- src/helics/network/tcp/TcpCommsSS.cpp
- src/helics/network/udp/UdpComms.h
- tests/helics/application_api/testFixtures.cpp
- tests/helics/network/CMakeLists.txt
- tests/helics/network/TcpCore-tests.cpp
- tests/helics/network/TcpSSCore-tests.cpp
- tests/helics/network/UdpCore-tests.cpp
- tests/helics/network/ZeromqSSCore-tests.cpp
- tests/helics/system_tests/brokerTimeoutTests.cpp
If merged this pull request will update the networking library and restore some of the network tests that had been inadvertently left off.
> Update network tests

- src/helics/application_api/ValueFederate.cpp
- src/helics/cpp98/Federate.hpp
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/test-combo-federate_cpp.cpp
- tests/helics/shared_library/test-message-federate_cpp.cpp
- tests/helics/test_files/combo_config.json
If merged this pull request will fix a missing call in the C++98 interface, and resolve some discrepancies' between subscription blocks and input blocks for input files.  
- add input test file
- resolve differences in block interpretation between input and subscription blocks
- add combo file tests
- add getFilterCount() to Cpp98 API
> Combo file test for CPP98

- CMakeLists.txt
- config/cmake/addUnits.cmake
If merged this pull request will update asio,  the units library, and json_cpp
> Submod updates

- src/helics/core/BasicHandleInfo.cpp
- src/helics/core/BasicHandleInfo.hpp
- src/helics/core/GlobalFederateId.hpp
- src/helics/core/HandleManager.cpp
- src/helics/core/HandleManager.hpp
If merged this pull request will attempt to resolve a somewhat confusing report of memory leak and undefined behavior report from numerical overflow for invalid federateId in certain cases.
The specific case in question could not pose a problem, but fixing it in general might prevent otherwise indeterminate issues.
> resolve some undefined behavior in certain edge cases

- src/helics/core/SmallBuffer.hpp
- src/helics/core/core-exceptions.hpp
- src/helics/cpp98/Broker.hpp
- src/helics/cpp98/Core.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/network/tcp/TcpComms.cpp
- tests/helics/apps/PlayerTests.cpp
- tests/helics/apps/combo_tests.cpp
- tests/helics/network/TcpSSCore-tests.cpp
- tests/helics/system_tests/dynamicFederationTests.cpp
- tests/helics/system_tests/iterationTests.cpp
If merged this pull request will fix some noted warnings from codacy and other compilers and analysis tools.
> Fix a few warnings from codacy and other compilers

- docs/user-guide/installation/windows.md
If merged this pull request will improve the documentation for how to build custom branches of HELICS on windows using Visual Studio and linking the custom `helics.dll` to pyhelics.
Documentation changes only.
> Windows build instructions

- src/helics/application_api/Federate.cpp
- src/helics/core/BaseTimeCoordinator.cpp
- src/helics/core/BaseTimeCoordinator.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/ForwardingTimeCoordinator.cpp
- src/helics/core/GlobalTimeCoordinator.hpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- src/helics/core/flagOperations.hpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/sequencing_tests/CMakeLists.txt
- tests/helics/sequencing_tests/Sequencing1.cpp
- tests/helics/sequencing_tests/Sequencing2.cpp
If merged this pull request will add a retry in case of try_lock spurious failure
> Sequencing fixes

- CHANGELOG.md
- CMakeLists.txt
- appveyor.yml
- docs/Public_API.md
- docs/ROADMAP.md
- vcpkg.json
If merged this pull request will update release docs for a 3.2 HELICS release
> Release update3 2

- docs/ROADMAP.md
- tests/helics/system_tests/QueryTests.cpp
If merged this pull request will merge a few final doc fixes
> final doc fixes for the release

- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
If merged this pull request will update the backup header files generated by HELICS. Not sure why the workflow to automatically update didn't open a PR -- need to look into that.
- Generate updated backup HELICS header files
> Update the backup generated HELICS header files

- .circleci/config.yml
- config/cmake/AddGoogletest.cmake
- src/helics/core/ActionMessage.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will update the google test version to a more recent commit to fix a warning and fix the noZMQ situation on the webserver tests.
> Dailies tests

- docs/references/configuration_options_reference.md
- scripts/run-circleci-tests.sh
- src/helics/core/BrokerBase.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/helics_enums.h
- src/helics/network/NetworkBrokerData.cpp
- src/helics/network/NetworkBrokerData.hpp
- src/helics/network/NetworkCommsInterface.cpp
- src/helics/network/NetworkCommsInterface.hpp
- src/helics/network/zmq/ZmqComms.cpp
- tests/helics/core/BrokerClassTests.cpp
If merged this pull request will add a force connection option to terminate existing brokers (currently only supported on ZMQ)
Also change the log level of the connection information on brokers to summary instead of connection
> Force connection

- .circleci/config.yml
- .circleci/leak_suppression.txt
- .circleci/leak_suppression_gcc.txt
- .codacy.yml
- scripts/run-circleci-tests-sanitizer.sh
- src/helics/apps/AsioBrokerServer.cpp
- src/helics/apps/AsioBrokerServer.hpp
- src/helics/apps/BrokerServer.cpp
- src/helics/apps/BrokerServer.hpp
- src/helics/apps/TypedBrokerServer.hpp
- src/helics/apps/helics-broker.cpp
- src/helics/apps/helicsWebServer.cpp
- src/helics/apps/helicsWebServer.hpp
- src/helics/apps/zmqBrokerServer.cpp
- src/helics/apps/zmqBrokerServer.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/helicsExport.cpp
- src/helics/shared_api_library/internal/api_objects.h
- tests/helics/shared_library/SystemTests.cpp
- tests/helics/shared_library/badInputTests.cpp
- tests/helics/shared_library/ctestFixtures.cpp
- tests/helics/shared_library/ctestFixtures.hpp
- tests/helics/shared_library/evilInputTests.cpp
- tests/helics/shared_library/test-value-federate1.cpp
- tests/helics/webserver/webServerHttpTests.cpp
- tests/helics/webserver/webServerWebSocketTests.cpp
If merged this pull request will clean update testing issues for the sanitizer tests and fix a few of the detected issues
> Sanitizer tests

- src/helics/core/TimeCoordinator.cpp
- tests/helics/system_tests/iterationTests.cpp
If merged this pull request will add a test for large iteration counts and reset the sequence counter more regularly.
> Large iteration count test

- src/helics/application_api/TranslatorOperations.hpp
- src/helics/shared_api_library/MessageFederateExport.cpp
- src/helics/shared_api_library/TranslatorExport.cpp
- src/helics/shared_api_library/ValueFederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCallbacks.h
- src/helics/shared_api_library/helicsData.cpp
- src/helics/shared_api_library/internal/api_objects.h
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/TranslatorTests.cpp
If merged this pull request will add some additional tests for the translator and the translator callback method for the C API
> Translator tests c

- src/helics/application_api/Inputs.hpp
- src/helics/network/zmq/ZmqCommsCommon.cpp
- src/helics/shared_api_library/ValueFederateExport.cpp
- tests/helics/shared_library/DataAPITests.cpp
- tests/helics/shared_library/SystemTests.cpp
- tests/helics/system_tests/iterationTests.cpp
If merged this pull request will fix some warnings and detected leaks in the tests
> fix some warnings and leaks from overnight tests

- src/helics/core/CoreBroker.cpp
- tests/helics/shared_library/TranslatorTests.cpp
If merged this pull request will fix a bug in the ADD_PUBLISHER code that was causing a sporadic failure in the custom_translator tests
> custom_translator_test_bug

- tests/helics/application_api/CombinationFederateTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/sequencing_tests/Sequencing1.cpp
If merged this pull request will Try to fix a few of the failing test cases potentially related to use of std::async
> test case fixes

- src/helics/application_api/MessageFederateManager.cpp
- src/helics/shared_api_library/helicsData.cpp
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/shared_library/CMakeLists.txt
- tests/helics/shared_library/DataAPITests.cpp
- tests/helics/shared_library/FilterTests.cpp
- tests/helics/shared_library/loggingTests.cpp
If merged this pull request will attempt to resolve some of the lingering sporadic failures
> Try to clear up some of the remaining sporadic failures

- src/helics/application_api/MessageFederateManager.cpp
- src/helics/application_api/MessageFederateManager.hpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/application_api/ValueFederateManager.hpp
try to make the code structures for endpoint and inputs more similar for callback in the application API.
This may also resolve some of the failing test cases related to callbacks 
If merged this pull request will refactor the EndpointData object in the application API to make it a little faster, match with the InputData object, update some of the object Names to better match conventions and hopefully resolve some of the failing test cases related to endpoint callbacks.
> EndpointData refactor

- src/helics/application_api/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/api-data.h
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCore.h
- tests/helics/shared_library/evilInputTests.cpp
If merged this pull request will add a HELICS_STATE_UNKNOWN to the helicsFederateGetState output
> add an HELICS_STATE_UNKNOWN result to the helicsFederateGetState

- .pre-commit-config.yaml
- benchmarks/helics/ActionMessageBenchmarks.cpp
- config/spelling_ignorelines.txt
- docs/man/federate-apps-common-options.adoc
- docs/man/manpage_out/helics_app-clone.1
- docs/man/manpage_out/helics_app-echo.1
- docs/man/manpage_out/helics_app-player.1
- docs/man/manpage_out/helics_app-recorder.1
- docs/man/manpage_out/helics_app-source.1
- docs/man/manpage_out/helics_app-tracer.1
- docs/man/manpage_out/helics_player.1
- docs/user-guide/fundamental_topics/simulator_integration.md
- docs/user-guide/fundamental_topics/stages.md
- docs/user-guide/installation/linux.md
- src/helics/apps/Player.cpp
- src/helics/apps/helics-broker.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.hpp
If merged this pull request will update the precommit versions and fix some accumulated warnings
> update precommit files and add an ignore file for spelling

- docs/user-guide/advanced_topics/commandInterface.md
- docs/user-guide/advanced_topics/queries.md
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/queryHelpers.hpp
- src/helics/cpp98/Federate.hpp
- tests/helics/shared_library/timingTests_cpp.cpp
- tests/helics/system_tests/TimingTests2.cpp
fix the command interface in the C++98 API
update docs
add query to get the current barriers
- add a command interface to generate/clear time barriers
- fix the command interface in the C++98 API
- update docs
- add query to get the current barriers
> add a command interface to generate/clear time barriers

- docs/user-guide/examples/advanced_examples/advanced_iteration.md
If merged this pull request will add some more background to the documentation of the iteration example as well as show plots comparing results when iteration is used versus when it is not.
Docs changes only to the iteration example.
> Improved iteration example documentation.

- src/helics/core/AsyncTimeCoordinator.cpp
- src/helics/core/BaseTimeCoordinator.cpp
- src/helics/core/BaseTimeCoordinator.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/ForwardingTimeCoordinator.cpp
- src/helics/core/ForwardingTimeCoordinator.hpp
- src/helics/core/GlobalTimeCoordinator.cpp
- src/helics/core/TimeCoordinator.cpp
- src/helics/core/TimeCoordinator.hpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/core/TimeDependencies.cpp
- src/helics/core/TimeDependencies.hpp
- tests/helics/core/ForwardingTimeCoordinatorTests.cpp
- tests/helics/core/TimeDependenciesTests.cpp
- tests/helics/system_tests/TimingTests.cpp
If merged this pull request will make some fixes to the forwarding time coordinator to handle some additional cases.  Also some code cleanup.
> Maxtime tests

- .ci/azure-pipelines.yml
If merged this pull request will enable CI job batching on Azure pipelines, which should reduce the number of queued CI jobs when more than 2 commits are made in a short time period to a branch/PR.
- Enable CI job batching on Azure Pipelines
> Enable batching CI jobs on Azure Pipelines

- src/helics/application_api/AsyncFedCallInfo.hpp
- src/helics/application_api/Federate.cpp
- src/helics/application_api/Federate.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CommonCore.hpp
- src/helics/core/Core.hpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/EmptyCore.cpp
- src/helics/core/EmptyCore.hpp
- src/helics/core/FederateState.cpp
- src/helics/core/FederateState.hpp
- src/helics/core/TimeCoordinatorProcessing.cpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCore.h
- tests/helics/application_api/FederateTests.cpp
- tests/helics/core/FederateState-tests.cpp
- tests/helics/system_tests/ErrorTests.cpp
If merged this pull request will add the initialization iteration capability
> Iterative initialize

- .github/workflows/code-coverage.yml
- config/cmake/updateGitSubmodules.cmake
- src/helics/application_api/FederateInfo.cpp
- src/helics/core/CommonCore.cpp
- src/helics/core/FederateState.cpp
- src/helics/core/InputInfo.cpp
- tests/helics/network/ZeromqCore-tests.cpp
and few other warnings and potential bug fixes
One of that static analyzers detected a use after move which might have caused an issue with some of the only update on change flag usage.
> fix some issues with the code coverage 

- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- tests/helics/system_tests/TimingTests2.cpp
even when setup prior to federate registration of federates.
> Allow broker based time barriers to work 

- src/helics/application_api/Federate.hpp
- src/helics/cpp98/Broker.hpp
- src/helics/cpp98/Core.hpp
- src/helics/cpp98/Federate.hpp
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- src/helics/shared_api_library/helicsCore.h
- src/helics/shared_api_library/helicsExport.cpp
- tests/helics/shared_library/test-value-federate2.cpp
If merged this pull request will add `addAlias` methods to the C and C++98 API
> C api aliases

- .ci/azure-pipelines.yml
- scripts/run-ci-tests.sh
- src/helics/core/BrokerFactory.cpp
- src/helics/core/CoreFactory.cpp
- src/helics/core/GlobalTimeCoordinator.cpp
- src/helics/core/GlobalTimeCoordinator.hpp
- tests/helics/application_api/FilterAdditionalTests.cpp
- tests/helics/application_api/FilterTests.cpp
- tests/helics/application_api/LoggingTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/testFixtures.cpp
- tests/helics/application_api/testFixtures_shared.hpp
a bit to try to resolve some lingering test issues
If merged this pull request will add an additional checking layer for the global time coordinator similar to what was done in the forwarding time coordinator to resolve an issue there.
> tweak the GlobalTimeCoordinator 

- tests/helics/application_api/LoggingTests.cpp
If merged this pull request will attempt to fix the sporadic failure of the remote_log_broker test
> try to adjust the remote_log_broker test to not stall

- .gitmodules
If merged this pull request will update the branch for the the containers submodule in .gitmodules to main (instead of master).
- Update containers submodule branch from master to main
> Update containers submodule branch to main

- src/helics/application_api/ValueFederate.cpp
- src/helics/application_api/ValueFederate.hpp
- src/helics/application_api/ValueFederateManager.cpp
- src/helics/application_api/ValueFederateManager.hpp
- src/helics/cpp98/Input.hpp
- src/helics/cpp98/ValueFederate.hpp
- src/helics/shared_api_library/ValueFederate.h
- src/helics/shared_api_library/ValueFederateExport.cpp
- src/helics/shared_api_library/backup/helics/helics.h
- src/helics/shared_api_library/backup/helics/helics_api.h
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/shared_library/badInputTests.cpp
- tests/helics/shared_library/comboConfigTests.cpp
- tests/helics/shared_library/evilInputTests.cpp
- tests/helics/shared_library/miscApiTests.cpp
- tests/helics/shared_library/test-value-federate1.cpp
Except helicsFederateRegisterSubscription and clean up usage of subscription in code documentation
> Deprecate all subscription methods 

- docs/requirements.txt
Fix mermaid version to allow installation graph to render correctly.
> Update sphinx-mermaid version to fix installation rendering problem.

- .circleci/config.yml
- benchmarks/helics/TcpFederate.cpp
- config/cmake/addfmt.cmake
- config/cmake/compiler_flags.cmake
- src/helics/application_api/Subscriptions.hpp
- src/helics/core/CommonCore.cpp
- src/helics/core/CoreBroker.cpp
- src/helics/core/CoreBroker.hpp
- src/helics/core/helicsTime.hpp
- tests/helics/application_api/DynamicValueFederateTests.cpp
- tests/helics/application_api/EndpointLinkingTests.cpp
- tests/helics/system_tests/heat-transfer-tests.cpp
If merged this pull request will make a few tweaks generated from warnings when building HELICS with clang-cl through Visual studio
> Make some tweaks to support clang-cl for visual studio cleanly

- src/helics/application_api/FederateInfo.cpp
- tests/helics/application_api/CombinationFederateTests.cpp
- tests/helics/application_api/MessageFederateAdditionalTests.cpp
- tests/helics/application_api/ValueFederateAdditionalTests.cpp
- tests/helics/shared_library/test-value-federate2.cpp
- tests/helics/test_files/example message fed with space.json
- tests/helics/test_files/folder with space/example_combo_fed.toml
- tests/helics/test_files/folder with space/example_value_fed.json
- tests/helics/test_files/folder with space/example_value_fed_testb.json
in the fie/path name.
If merged this pull request will fix an issue with spaces in a config file name or path given through config constructor.  And add a series of test cases to verify this
> Test and handle config files given as argument with a space 

- docs/quick-links.md
Small fix for Quick Links page in docs.
> Fix Quick Links page in docs

- src/helics/shared_api_library/.clang-tidy
- src/helics/shared_api_library/FederateExport.cpp
- src/helics/shared_api_library/helicsCallbacks.cpp
- src/helics/shared_api_library/helicsCore.h
- tests/helics/shared_library/QueryTests.cpp
- tests/helics/shared_library/QueryTests_cpp.cpp
- tests/helics/shared_library/loggingTests.cpp
If merged this pull request will try to figure out what is going with the sporadically failing logging test
> add some additional stuff to debug failing loggingTests.cpp

- CHANGELOG.md
- CMakeLists.txt
- appveyor.yml
- vcpkg.json
If merged this pull request will update docs for  3.5.2 patch release
> update docs for a 3.5.2 release

- src/helics/application_api/helicsTypes.cpp
Fix building helics with fmt-11
Fixes #2668
> Fix build with fmt-11

- src/helics/application_api/PotentialInterfacesManager.cpp
- src/helics/application_api/PotentialInterfacesManager.hpp
- src/helics/apps/Connector.cpp
- src/helics/apps/Connector.hpp
- tests/helics/apps/ConnectorTestsPotentialInterfaces.cpp
- tests/helics/apps/test_files/connector/potential_interface_test2.json
- tests/helics/apps/test_files/connector/potential_interface_test3.json
from potential interfaces.
If merged this pull request will add connector targets to potential interfaces
> Add the ability to read interface targets and alias 
